<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Bölüm 4 Çoklu Regresyon | OLC733</title>

    <meta name="author" content="Kubra Atalay Kabasakal" />
  
   <meta name="description" content="Bu notlar OLC733 dersi için hazırlanmıştır." />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="Bölüm 4 Çoklu Regresyon | OLC733" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://github.com/atalay-k/OLC733" />
  
  <meta property="og:description" content="Bu notlar OLC733 dersi için hazırlanmıştır." />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Bölüm 4 Çoklu Regresyon | OLC733" />
  
  <meta name="twitter:description" content="Bu notlar OLC733 dersi için hazırlanmıştır." />
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.6.1/transition.js"></script>
    <script src="libs/bs3compat-0.6.1/tabs.js"></script>
    <script src="libs/bs3compat-0.6.1/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
    <link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
    <script src="libs/datatables-binding-0.32/datatables.js"></script>
    <link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
    <script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
    <link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
    <script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
    <script src="libs/plotly-binding-4.10.4/plotly.js"></script>
    <script src="libs/typedarray-0.1/typedarray.min.js"></script>
    <link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
    <script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
    <script src="libs/rglWebGL-binding-1.2.8/rglWebGL.js"></script>
    <link href="libs/rglwidgetClass-1.2.8/rgl.css" rel="stylesheet" />
    <script src="libs/rglwidgetClass-1.2.8/rglClass.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/utils.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/buffer.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/subscenes.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/shaders.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/shadersrc.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/textures.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/projection.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/mouse.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/init.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/pieces.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/draw.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/controls.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/selection.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/rglTimer.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/pretty.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/axes.src.js"></script>
    <script src="libs/rglwidgetClass-1.2.8/animation.src.js"></script>
    <script src="libs/CanvasMatrix4-1.2.8/CanvasMatrix.src.js"></script>
    <script src="libs/viz-1.8.2/viz.js"></script>
    <link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet" />
    <script src="libs/grViz-binding-1.0.11/grViz.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
      <link rel="stylesheet" href="include/psyteachr.css" />
    <link rel="stylesheet" href="include/webex.css" />
    <link rel="stylesheet" href="include/style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="R ile Çok Değişkenli İstatistik ve Ölçme Uygulamaları">OLC733</a>:
        <small class="text-muted">R ile Çok Değişkenli İstatistik ve Ölçme Uygulamaları</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="çoklu-regresyon" class="section level1" number="4">
<h1><span class="header-section-number">Bölüm 4</span> Çoklu Regresyon</h1>
<ul>
<li><p>Çok değişkenli analiz, bir çalışmadaki bireylerden veya
nesnelerden elde edilen çoklu ölçümlerin aynı anda
analizidir. Dolayısıyla <strong>ikiden fazla değişkenin</strong> aynı anda
analizi çok değişkenli analiz olarak düşünülebilir.</p></li>
<li><p>Çok değişkenli analiz yöntemlerinin çoğu <strong>tek veya iki
değişkenli</strong> analiz yöntemlerinin uzantısıdır.</p></li>
<li><p>Çoklu regresyon, basit regresyonun tek bir bağımlı değişkenin
<strong>iki veya daha fazla yordayıcısına</strong> izin veren uzantısıdır. Diğer bir
ifadeyle, çoklu regresyon tek bir bağımlı değişken ile <strong>iki veya daha
fazla bağımsız (yordayıcı)</strong> değişken arasındaki ilişkinin analiz
edilmesi için kullanılan istatistiksel bir yöntemdir.</p></li>
<li><p>Çoklu regresyonun amacı değerleri bilinen <strong>bağımsız değişkenleri
kullanarak bağımlı değişkenin değerini</strong> yordamaktır.</p></li>
<li><p>Regresyon yöntemiyle <strong>bağımsız değişkenlerden en fazla yordamayı
sağlamak üzere her bağımsız değişken</strong> ağırlıklandırılır.</p></li>
<li><p>Ağırlıklar bağımsız değişkenin <strong>yordamaya bağıl katkısını</strong> ifade eder
ve her bir değişkenin yordamadaki etkisine ilişkin yorumlamayı kolaylaştırır.</p></li>
<li><p>Çoklu regresyon, hem bağımlı değişken hem de bağımsız
değişkenler <strong>en az eşit aralıklı ölçek düzeyinde</strong> ölçüldüğünde
kullanılmalıdır.</p></li>
<li><p>Ancak bağımsız değişkenler <strong>sınıflama veya sıralama ölçeğinde</strong> ölçüldüğünde ilgili değişkenler <strong>belli koşullar</strong>
altında analize dahil edilebilir.</p></li>
<li><p>Çoklu regresyon her bir bağımsız değişkendeki değişikliklerin
<strong>bağımlı değişkendeki değişikliklerle ne ölçüde</strong> ilişkili olduğunu
kestirir.</p></li>
<li><p>Ancak <strong>bağımsız değişkenler arasındaki korelasyon</strong>
yordama sürecini zorlaştırır.</p></li>
</ul>
<div id="çoklu-regresyon-1" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Çoklu Regresyon</h2>
<p>Örneğin, <span class="math inline">\(X_1\)</span> ve <span class="math inline">\(Y\)</span> arasındaki korelasyon katsayısı <strong>0.40</strong>, <span class="math inline">\(X_2\)</span> ve <span class="math inline">\(Y\)</span>
arasındaki korelasyon katsayısı <strong>0.60</strong>, <span class="math inline">\(X_1\)</span> ve <span class="math inline">\(X_2\)</span> arasındaki korelasyon
katsayısı sıfır ise, <span class="math inline">\(Y\)</span>’nin varyansının iki değişken tarafından
açıklanan toplam oranı iki değişkenin <span class="math inline">\(Y\)</span> ile korelasyonlarının
kareleri toplamından elde edilebilir:</p>
<p><span class="math inline">\(0.40^2 + 0.50^2 = 0.16 + 0.25 = 0.41\)</span></p>
<p><img src="images/CR_1.PNG" width="75%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Ancak, uygulamada çoğunlukla <span class="math inline">\(X_1\)</span> ve <span class="math inline">\(X_2\)</span> birlikte değişim gösterirler
ve iki değişkenin <span class="math inline">\(Y\)</span> ile korelasyonlarının kareleri toplamı
çok yüksek bir oran verir.</p></li>
<li><p>Bunun nedeni, iki bağımsız değişkenin aralarındaki korelasyondan dolayı
her bir bağımsız değişken tarafından açıklanan <span class="math inline">\(Y\)</span> varyansının bir kısmının üst üste gelmesidir.</p></li>
<li><p>Çoklu regresyonun en önemli özelliği modele eklenen bağımsız
değişkenler arasındaki ilişkileri kontrol altına almasıdır.</p></li>
</ul>
<p><img src="images/CR_2.PNG" width="75%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Modeldeki bağımsız değişkenler arasındaki ilişkilerin kontrol altına alınması, modeldeki bir değişkenin bağımlı değişken üzerindeki etkisini incelerken, modeldeki diğer bütün değişkenlerin sabit tutulmasıdır.<strong>ceteris paribus</strong></p>
<ul>
<li>Örneğin, bir çalısmada kahve tuketiminin ölüm oranını nasıl etkilediği calisilmistir. Basta, sonuclar daha yuksek kahve tuketiminin daha yuksek ölüm riskiyle ilişkili oldugunu gostermistir. Ancak kahve icen cogu kisi sigara da icmektedir. Arastirmacilar modellerine sigara icme aliskanliklari icin bir degisken eklediklerinde, sigara icmenin ölüm riskini artırırken, kahve tuketiminin ölüm riskini azalttığını bulmuşlardır.</li>
</ul></li>
<li><p>Bu durumda modele bütün onemli değişkenlerin eklenmesi gerekmektedir. Onemli değişkenlerin modelin dışında bırakılması, katsayılara ilişkin kestirimlerin <strong>yanlı</strong> olmasina neden olabilmektedir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-uygulama" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Çoklu Regresyon Uygulama</h2>
<ul>
<li><strong>Performans:</strong> Öğrencilerin matematik performans düzeyleri olup eşit aralık
ölçeğinde ölçülen sürekli bir değişkendir.</li>
<li><strong>Motivasyon:</strong> Öğrencilerin motivasyon
düzeyleri olup eşit aralık ölçeğinde
ölçülen sürekli bir değişkendir.</li>
<li><strong>Kaygı:</strong> Öğrencilerin kaygı düzeyleri olup
eşit aralık ölçeğinde ölçülen sürekli bir
değişkendir.</li>
<li><strong>Güven:</strong> Öğrencilerin matematiğe karşı
güven düzeyleri olup eşit aralık ölçeğinde
ölçülen sürekli bir değişkendir.</li>
</ul>
<p>Betimsel İstatistikler</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="çoklu-regresyon.html#cb16-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb16-2"><a href="çoklu-regresyon.html#cb16-2" tabindex="-1"></a>performans <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;import/Performans.sav&quot;</span>)</span>
<span id="cb16-3"><a href="çoklu-regresyon.html#cb16-3" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(performans)[,<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">mean</th>
<th align="right">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Performans</td>
<td align="right">18.2</td>
<td align="right">7.83</td>
</tr>
<tr class="even">
<td align="left">Motivasyon</td>
<td align="right">39.9</td>
<td align="right">10.03</td>
</tr>
<tr class="odd">
<td align="left">Kaygi</td>
<td align="right">18.1</td>
<td align="right">4.77</td>
</tr>
<tr class="even">
<td align="left">Guven</td>
<td align="right">21.6</td>
<td align="right">7.38</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="korelasyon-değerleri-ve-anlamlılığı" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Korelasyon değerleri ve anlamlılığı</h2>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="çoklu-regresyon.html#cb17-1" tabindex="-1"></a>cor_1 <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(<span class="sc">~</span> Performans <span class="sc">+</span> Motivasyon , <span class="at">data =</span> performans)</span>
<span id="cb17-2"><a href="çoklu-regresyon.html#cb17-2" tabindex="-1"></a><span class="fu">tidy</span>(cor_1)[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.824</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="çoklu-regresyon.html#cb18-1" tabindex="-1"></a>cor_2 <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(<span class="sc">~</span> Performans <span class="sc">+</span> Kaygi , <span class="at">data =</span> performans)</span>
<span id="cb18-2"><a href="çoklu-regresyon.html#cb18-2" tabindex="-1"></a><span class="fu">tidy</span>(cor_2)[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-0.241</td>
<td align="right">0.388</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="çoklu-regresyon.html#cb19-1" tabindex="-1"></a>cor_3 <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(<span class="sc">~</span> Motivasyon <span class="sc">+</span> Kaygi , <span class="at">data =</span> performans)</span>
<span id="cb19-2"><a href="çoklu-regresyon.html#cb19-2" tabindex="-1"></a><span class="fu">tidy</span>(cor_3)[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.147</td>
<td align="right">0.601</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="çoklu-regresyon-2" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Çoklu Regresyon</h2>
<ul>
<li><p>Öğrencilerin matematikteki <strong>performans düzeylerini, motivasyon ve
kaygı düzeylerinden yordamak</strong> ile ilgilendiğimizi düşünelim.</p></li>
<li><p>Bu araştırma sorusuna cevap vermek için çoklu regresyon uygun bir
istatistiksel analiz yöntemdir.</p></li>
</ul>
<p><span class="math display">\[Y_{performans_i} = b_0 + b_1 X_{motivasyon_i} +  b_2 X_{kaygi_i} + e_i\]</span></p>
<ul>
<li>Burada, <span class="math inline">\(b_1\)</span> ve <span class="math inline">\(b_2\)</span> motivasyon ve kaygı yordayıcıları için ağırlıklardır. Diğer bir ifadeyle regresyon katsayılarıdır veya eğimlerdir. <span class="math inline">\(b_0\)</span> ise kesişimdir.</li>
</ul>
</div>
<div id="çoklu-regresyon-3" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Çoklu Regresyon</h2>
<ul>
<li><p>Amaç hata puanlarının (artiklarin) kareleri toplamının küçüleceği,
diğer bir ifade ile <span class="math inline">\(Y\)</span> ve yordanan <span class="math inline">\(Y&#39;\)</span> arasındaki korelasyonun
büyüyeceği, <span class="math inline">\(b_0\)</span>, <span class="math inline">\(b_1\)</span> ve <span class="math inline">\(b_2\)</span> değerleri için tek bir çözüm kümesi
bulmaktır.</p></li>
<li><p>Grafiğin sadeleştirilmesi için bir bağımsız değişken kullanılmıştır.</p></li>
<li><p>Tek bir çözüm bulmak için kullanılan yöntem Sıradan <strong>En
Küçük Kareler Yöntemi</strong> (Ordinary Least Squares Procedure) olarak adlandırılır.</p></li>
</ul>
<p><img src="images/CR_3.PNG" width="75%" style="display: block; margin: auto;" /></p>
</div>
<div id="çoklu-regresyon-4" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Çoklu Regresyon</h2>
<ul>
<li><p><span class="math inline">\(R^2\)</span> değeri <em>çoklu korelasyon katsayısı</em> (multiple correlation
coefficient) olup bağımlı değişkenin gözlenen değerleri ile bağımsız
değişkenlerin <em>en iyi doğrusal kombinasyonu</em> arasındaki
korelasyondur.</p></li>
<li><p><strong>En iyi doğrusal kombinasyon</strong>, bağımlı değişkenin
bağımsız değişkenlerden yordanmasında, daha iyi bir iş yapacak
regresyon katsayıları kümesi olmadığı anlamına gelir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-5" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Çoklu Regresyon</h2>
<p>Çoklu Korelasyon</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="çoklu-regresyon.html#cb20-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span> Motivasyon <span class="sc">+</span> Kaygi,<span class="at">data=</span>performans)</span>
<span id="cb20-2"><a href="çoklu-regresyon.html#cb20-2" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">glance</span>(model)[,<span class="dv">1</span>])</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.902</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>R değeri bağımlı değişkenin <strong>gözlenen</strong> ve <strong>yordanan</strong> değerleri arasındaki <strong>korelasyondur</strong>.</p></li>
<li><p>Bağımlı değişkenin <strong>yordanan değerinin</strong> bağımlı değişkenin
<strong>gözlenen değerine</strong> mümkün olduğunca yakın olmasını
gerektiren <strong>en küçük kareler kriterinden</strong> dolayı bağımlı
değişkenin <strong>gözlenen ve yordanan değerleri arasındaki korelasyon eksi
değerler</strong> alamaz. Dolayısıyla çoklu korelasyon katsayısı 0 ile 1
arasında değişir</p></li>
</ul>
</div>
<div id="çoklu-regresyon-6" class="section level2" number="4.8">
<h2><span class="header-section-number">4.8</span> Çoklu Regresyon</h2>
<p>** Çoklu Korelasyon**
<span class="math display">\[R_{Y_{12}}= \sqrt{\frac{r^2_{Y_1}+r^2_{Y_2}-2r^2_{Y_1}r^2_{Y_2}r_{12}}{1-r_{12}}}\]</span>
<span class="math display">\[R_{Y_{12}}=\sqrt{\frac{(0.824)^2+(-0.241)^2-2*(0.824)(-0.241)(0.147)}{1-(0.147)^2}}) = 0.902\]</span></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="çoklu-regresyon.html#cb21-1" tabindex="-1"></a>model_s <span class="ot">&lt;-</span> <span class="fu">augment</span>(model,<span class="at">data=</span>performans)</span>
<span id="cb21-2"><a href="çoklu-regresyon.html#cb21-2" tabindex="-1"></a><span class="fu">cor</span>(model_s[,<span class="dv">1</span>], model_s[,<span class="dv">5</span>])</span></code></pre></div>
<pre><code>##            .fitted
## Performans   0.902</code></pre>
<p>öğrencilerin <strong>gözlenen performans puanları</strong> ve <strong>yoradan performans puanları</strong> arasındaki korelasyon katsayısı nokta <strong>0.902</strong> eşittir</p>
</div>
<div id="çoklu-regresyon-7" class="section level2" number="4.9">
<h2><span class="header-section-number">4.9</span> Çoklu Regresyon</h2>
<p>Çoklu Korelasyon</p>
<ul>
<li><p>Çoklu korelasyon katsayısının kestirimi hem örneklem büyüklüğüne
<span class="math inline">\((n)\)</span> hem de bağımsız değişkenlerin sayısına <span class="math inline">\((k)\)</span> bağlıdır.</p></li>
<li><p>Bağımlı değişken ile bağımsız değişkenler arasında hiç ilişki yoksa,
<span class="math inline">\(R\)</span> değerinin sıfıra yakın olması beklenir ancak <span class="math inline">\(R\)</span>’nin beklenen değeri
rastgele bir veri için <span class="math inline">\(k/(n-1)\)</span>’dir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-8" class="section level2" number="4.10">
<h2><span class="header-section-number">4.10</span> Çoklu Regresyon</h2>
<ul>
<li><p>Örneğin, örneklem büyüklüğünün <strong>50</strong>, bağımsız değişken sayısının <strong>2</strong> olduğu bir durumda, bağımlı değişken ile bağımsız değişkenler arasında hiç ilişki yoksa, R değeri <strong>0.04</strong> olacaktır, <strong>0</strong> değil.</p></li>
<li><p>Bu nedenle büyük örnekleme sahip olmak önemlidir. Her bağımsız
değişken için <strong>en az 10</strong> gözlem önerilmektedir. Bir başka öneri de
örneklem büyüklüğünün <strong>bağımsız değişken sayısından en az 50
fazla olması</strong> yönündedir.</p></li>
<li><p>Bir çalışmada, tek bir bağımsız değişken bulunduğunda, <strong>0.80</strong> güce sahip olmak için <strong>0.30</strong> evren korelasyonunun <strong>124</strong> birey gerektireceği belirtilmiştir. <strong>Beş bağımsız</strong> değişken bulunduğundaysa, örneklem büyüklüğünün <strong>187</strong> olması gerekmektedir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-9" class="section level2" number="4.11">
<h2><span class="header-section-number">4.11</span> Çoklu Regresyon</h2>
<p><strong>Çoklu Korelasyon</strong></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="çoklu-regresyon.html#cb23-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span> Motivasyon <span class="sc">+</span> Kaygi,<span class="at">data=</span>performans)</span>
<span id="cb23-2"><a href="çoklu-regresyon.html#cb23-2" tabindex="-1"></a><span class="fu">glance</span>(model)[,<span class="dv">1</span>]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.814</td>
</tr>
</tbody>
</table>
</div>
<p><span class="math inline">\(R^2\)</span> değeri <strong>belirlilik katsayısı</strong> (coefficient of determination) olup
bağımlı değişkenin gözlenen ve yordanan değerleri arasındaki
korelasyonun karesi alınarak hesaplanır. Bu değer bağımlı
değişkendeki varyansın model tarafından açıklanan oranını ifade
eder. Diğer bir ifadeyle <strong>bağımlı değişkenin varyansının bağımsız
değişkenlerin en iyi doğrusal kombinasyonu</strong> ile paylaşılan oranını
ifade eder.
<strong>Performans puanlarındaki varyansın yaklaşık %81’i öğrencilerin motivasyon ve kaygı puanları</strong> tarafından açıklanabilir.</p>
</div>
<div id="çoklu-regresyon-10" class="section level2" number="4.12">
<h2><span class="header-section-number">4.12</span> Çoklu Regresyon</h2>
<ul>
<li><p>Modele yeni bir bağımsız değişken eklendiginde, <span class="math inline">\(R^2\)</span> degeri artar,
sadece <strong>sans eseri olsa bile</strong>. Boylece daha fazla bağımsız değişken
iceren model sadece daha fazla bağımsız değişken icerdigi icin
veriye daha iyi uyum sagliyor gibi gozukebilir.</p></li>
<li><p>Bu etkiyi gidermek icin <span class="math inline">\(adj R^2\)</span> degeri hesaplanabilir.</p></li>
<li><p><span class="math inline">\(adj R^2\)</span> değeri, <span class="math inline">\(R^2\)</span> değerinin modeldeki bağımsız degisken sayısı için modifiye edilmis versiyonudur. <span class="math inline">\(adj R^2\)</span> degeri yeni eklenen bağımsız
degisken modeli sans eseri beklenenden daha fazla gelistirirse artar,
daha az gelistirirse azalir.</p></li>
<li><p><span class="math inline">\(adj R^2\)</span> değeri, eksi değerler alabilir ancak genellikle artı değerler alır. Her zaman <span class="math inline">\(R^2\)</span> değerinden daha düşüktür.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-11" class="section level2" number="4.13">
<h2><span class="header-section-number">4.13</span> Çoklu Regresyon</h2>
<p><span class="math inline">\(R^2\)</span> değeri, <span class="math inline">\(n\)</span> gözlemlerin sayısı, <span class="math inline">\(k\)</span> bağımsız değişkenlerin sayısı olmak üzere, aşağıdaki eşitlikle hesaplanabilir.
<span class="math display">\[R^2_{adj}= R^2 - \frac{k-(1-R^2)}{n-k-1}\]</span>
<span class="math display">\[R^2_{adj}= 0.814 - \frac{2-(1-0.814)}{15-2-1} =0.783\]</span></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="çoklu-regresyon.html#cb24-1" tabindex="-1"></a><span class="fu">glance</span>(model)[,<span class="dv">2</span>]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">adj.r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.783</td>
</tr>
</tbody>
</table>
</div>
<p><span class="math inline">\(adj R^2\)</span> evrende gerçek korelasyonun karesinin daha az yanlı kestirimi olsa da, çoğunlukla <span class="math inline">\(R^2\)</span> değeri rapor edilir.</p>
</div>
<div id="çoklu-regresyon-12" class="section level2" number="4.14">
<h2><span class="header-section-number">4.14</span> Çoklu Regresyon</h2>
<ul>
<li><strong>Kestirimin standart hatası</strong> (standard error of the estimation), modeldeki artıkların karelerinin toplamının, <span class="math inline">\(n-p\)</span> ( <span class="math inline">\(n\)</span> örneklem büyüklüğü ve <span class="math inline">\(p\)</span> modeldeki parametrelerin sayısı) ile bölünmesiyle elde edilen bölümün kareköküdür.</li>
</ul>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="çoklu-regresyon.html#cb25-1" tabindex="-1"></a><span class="fu">glance</span>(model)[,<span class="dv">3</span>]</span>
<span id="cb25-2"><a href="çoklu-regresyon.html#cb25-2" tabindex="-1"></a></span>
<span id="cb25-3"><a href="çoklu-regresyon.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="çoklu-regresyon.html#cb25-4" tabindex="-1"></a>res <span class="ot">&lt;-</span> model<span class="sc">$</span>residuals</span>
<span id="cb25-5"><a href="çoklu-regresyon.html#cb25-5" tabindex="-1"></a><span class="fu">sd</span>(res)</span>
<span id="cb25-6"><a href="çoklu-regresyon.html#cb25-6" tabindex="-1"></a></span>
<span id="cb25-7"><a href="çoklu-regresyon.html#cb25-7" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>((res <span class="sc">-</span> <span class="fu">mean</span>(res)) <span class="sc">^</span> <span class="dv">2</span> <span class="sc">/</span> (<span class="fu">length</span>(res)<span class="sc">-</span><span class="dv">3</span>)))</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">sigma</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">3.65</td>
</tr>
</tbody>
</table>
</div>
<pre><code>## [1] 3.38
## [1] 3.65</code></pre>
<p>]</p>
</div>
<div id="çoklu-regresyon-13" class="section level2" number="4.15">
<h2><span class="header-section-number">4.15</span> Çoklu Regresyon</h2>
<ul>
<li><p>Modelin veriye iyi uyup uymadığının test edilmesinde kullanılacak <strong>F</strong> değeri varyans analizi sonucunda elde edilir.</p></li>
<li><p>Regresyonun anlamlılığının test edildiği varyans analizinde, birlikte ele alınan bir grup bağımsız değişkenin (motivasyon ve kaygı gibi) en iyi doğrusal kombinasyonu ile bağımlı değişken (performans gibi) arasında <strong>korelasyon yoktur sıfır hipotezi</strong> test edilir. İstatistiksel olarak <strong>anlamlı etki</strong>, <strong>evrende çoklu korelasyon katsayısının sıfırdan farklı olduğu anlamına </strong>gelir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-14" class="section level2" number="4.16">
<h2><span class="header-section-number">4.16</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="çoklu-regresyon.html#cb27-1" tabindex="-1"></a><span class="fu">glance</span>(model)[,<span class="dv">4</span><span class="sc">:</span><span class="dv">6</span>]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">26.2</td>
<td align="right">0</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>F istatistiği 26.2 değerine eşittir ve istatistiğe ilişkin p &lt; 0.001. Bu olasılık 0.05’ten küçük olduğundan, sıfır hipotezi reddedilir.</p></li>
<li><p>Bu sonuç <strong>motivasyon ve kaygı değişkenlerinin ikisi birlikte kullanıldığında, çoklu korelasyon katsayısının anlamlı olarak sıfırdan büyük olduğunu</strong> ifade etmektedir. Diğer bir ifadeyle, motivasyon ve kaygı değişkenleri performansı istatistiksel olarak anlamlı bir şekilde yordamaktadır.</p></li>
<li><p><strong>Regresyon modeli veriye iyi uyum sağlamaktadır.</strong></p></li>
</ul>
</div>
<div id="çoklu-regresyon-15" class="section level2" number="4.17">
<h2><span class="header-section-number">4.17</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="çoklu-regresyon.html#cb28-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb28-2"><a href="çoklu-regresyon.html#cb28-2" tabindex="-1"></a><span class="fu">tidy</span>(model) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1.744</td>
<td align="right">5.096</td>
<td align="right">0.342</td>
<td align="right">0.738</td>
</tr>
<tr class="even">
<td align="left">Motivasyon</td>
<td align="right">0.686</td>
<td align="right">0.098</td>
<td align="right">6.975</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">Kaygi</td>
<td align="right">-0.607</td>
<td align="right">0.207</td>
<td align="right">-2.936</td>
<td align="right">0.012</td>
</tr>
</tbody>
</table>
<p>Performans puanlarındaki farklılıkların <strong>bir kısmı motivasyon puanlarındaki farklılıklardan</strong>, <strong>bir kısmı ise kaygı puanlarındaki farklılıklardan</strong> kaynaklanmaktadır</p>
</div>
<div id="çoklu-regresyon-16" class="section level2" number="4.18">
<h2><span class="header-section-number">4.18</span> Çoklu Regresyon</h2>
<ul>
<li><strong>Performansın</strong> sadece <strong>kaygıdan yordandığı basit regresyon analizi</strong> gerçekleştirilirse, yordanan puanlar ve gözlenen puanlar arasındaki fark <strong>(artıkPER1)</strong>, <strong>performansın kaygıdan yordanamayan kısmı</strong> olacaktır.</li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="çoklu-regresyon.html#cb29-1" tabindex="-1"></a>artıkPER1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span>  Kaygi,<span class="at">data=</span>performans)<span class="sc">$</span>residuals</span></code></pre></div>
<ul>
<li><strong>Motivasyonun</strong> sadece <strong>kaygıdan yordandığı basit regresyon analizi</strong> gerçekleştirilirse, yordanan puanlar ve gözlenen puanlar arasındaki fark <strong>(artıkMOT)</strong>, <strong>motivasyonun kaygıdan yordanamayan kısmı</strong> olacaktır.</li>
</ul>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="çoklu-regresyon.html#cb30-1" tabindex="-1"></a>artıkMOT <span class="ot">&lt;-</span> <span class="fu">lm</span>(Motivasyon  <span class="sc">~</span>  Kaygi,<span class="at">data=</span>performans)<span class="sc">$</span>residuals</span></code></pre></div>
<ul>
<li>Böylece <strong>artıkPER1</strong> ve <strong>artıkMOT</strong> olarak adlandırılan artık puanlar kaygıdan bağımsız olacaktır.</li>
</ul>
</div>
<div id="çoklu-regresyon-17" class="section level2" number="4.19">
<h2><span class="header-section-number">4.19</span> Çoklu Regresyon</h2>
<ul>
<li>Diğer bir ifadeyle, <strong>kaygı ilişkilerinde</strong> herhangi bir rol oynamayacaktır. <strong>artıkPER1</strong> puanları <strong>artıkMOT</strong> puanlarından yordanırsa, <strong>artıkMOT</strong> puanlarına ilişkin eğim katsayısı <strong>0.686</strong> olarak kestirilecektir. Bu değer, <strong>öğrencilerin kaygı düzeyleri kontrol altına</strong> alındıktan sonra, <strong>motivasyon düzeylerindeki bir birimlik</strong> artışın matematikteki <strong>performans düzeylerini 0.686</strong> birim artırmaya eğilimli olduğunu önermektedir</li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="çoklu-regresyon.html#cb31-1" tabindex="-1"></a><span class="fu">lm</span>(artıkPER1  <span class="sc">~</span>  artıkMOT,<span class="at">data=</span><span class="fu">data.frame</span>(artıkPER1,artıkMOT))<span class="sc">$</span>coefficients </span></code></pre></div>
<pre><code>## (Intercept)    artıkMOT 
##    4.59e-16    6.86e-01</code></pre>
</div>
<div id="çoklu-regresyon-18" class="section level2" number="4.20">
<h2><span class="header-section-number">4.20</span> Çoklu Regresyon</h2>
<ul>
<li><p><span class="math display">\[B_{Y_{12}} = \frac{r_{Y1}-r_{Y2}r_{12}}{1-r^2_{12}}\frac{sd_Y}{sd_1}\]</span></p></li>
<li><p><span class="math display">\[B_{Y_{12}} = \frac{(0.824)-(-0.241)(0.147)}{1-(0.022)}\frac{7.827}{10.025} = 0.879 * 0.780 =0.686\]</span></p></li>
<li><p>Bu değer, <strong>kaygı puanı kontrol altına alındıktan sonra</strong>, <strong>motivasyon</strong> puanlarındaki
<strong>bir birimlik artışın</strong> öğrencilerin <strong>matematik performansından 0.686</strong> birim artmaya eğilimi olduğunu önermektedir.</p></li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="çoklu-regresyon.html#cb33-1" tabindex="-1"></a>((<span class="fu">cor</span>(performans)[<span class="dv">2</span>,<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">cor</span>(performans)[<span class="dv">3</span>,<span class="dv">1</span>]<span class="sc">*</span><span class="fu">cor</span>(performans)[<span class="dv">2</span>,<span class="dv">3</span>])<span class="sc">/</span></span>
<span id="cb33-2"><a href="çoklu-regresyon.html#cb33-2" tabindex="-1"></a>   (<span class="dv">1</span><span class="sc">-</span><span class="fu">cor</span>(performans)[<span class="dv">2</span>,<span class="dv">3</span>]<span class="sc">^</span><span class="dv">2</span>))<span class="sc">*</span>(<span class="fu">sd</span>(performans<span class="sc">$</span>Performans)<span class="sc">/</span><span class="fu">sd</span>(performans<span class="sc">$</span>Motivasyon))</span></code></pre></div>
<pre><code>## [1] 0.686</code></pre>
</div>
<div id="çoklu-regresyon-19" class="section level2" number="4.21">
<h2><span class="header-section-number">4.21</span> Çoklu Regresyon</h2>
<ul>
<li><strong>Performansın</strong> sadece <strong>motivasyondan</strong> yordandığı basit regresyon analizi
gerçekleştirilirse, yordanan puanlar ve gözlenen puanlar arasındaki fark
<strong>(artıkPER2)</strong>, <strong>performansın motivasyondan</strong> yordanamayan kısmı olacaktır.</li>
</ul>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="çoklu-regresyon.html#cb35-1" tabindex="-1"></a>artıkPER2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span>  Motivasyon ,<span class="at">data=</span>performans)<span class="sc">$</span>residuals</span></code></pre></div>
<ul>
<li><strong>Kaygının</strong> sadece <strong>motivasyondan</strong> yordandığı basit regresyon analizi<br />
gerçekleştirilirse, yordanan puanlar ve gözlenen puanlar arasındaki
fark <strong>(artıkKAY)</strong>, <strong>kaygının motivasyondan</strong> yordanamayan kısmı olacaktır.</li>
</ul>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="çoklu-regresyon.html#cb36-1" tabindex="-1"></a>artıkKAY <span class="ot">&lt;-</span> <span class="fu">lm</span>(Kaygi <span class="sc">~</span>  Motivasyon ,<span class="at">data=</span>performans)<span class="sc">$</span>residuals</span></code></pre></div>
</div>
<div id="çoklu-regresyon-20" class="section level2" number="4.22">
<h2><span class="header-section-number">4.22</span> Çoklu Regresyon</h2>
<ul>
<li><p>Böylece <strong>artıkPER2</strong> ve <strong>artıkKAY</strong> olarak adlandırılan artık puanlar motivasyondan bağımsız olacaktır. Diğer bir ifadeyle, <strong>motivasyon ilişkilerinde herhangi bir rol</strong> oynamayacaktır.</p></li>
<li><p><strong>artıkPER2</strong> puanları <strong>artıkKAY</strong> puanlarından yordanırsa, <strong>artıkKAY</strong>
puanlarına ilişkin eğim katsayısı <strong>-0.607</strong> olarak kestirilecektir. Bu değer,
<strong>öğrencilerin motivasyon düzeyleri kontrol altına alındıktan sonra</strong>, kaygı
düzeylerindeki <strong>bir birimlik</strong> artışın matematikteki performans düzeylerini <strong>0.607</strong> birim azaltmaya eğilimli olduğunu önermektedir</p></li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="çoklu-regresyon.html#cb37-1" tabindex="-1"></a><span class="fu">lm</span>(artıkPER2  <span class="sc">~</span>  artıkKAY,<span class="at">data=</span><span class="fu">data.frame</span>(artıkPER2,artıkKAY))<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)    artıkKAY 
##   -6.18e-16   -6.07e-01</code></pre>
</div>
<div id="çoklu-regresyon-21" class="section level2" number="4.23">
<h2><span class="header-section-number">4.23</span> Çoklu Regresyon</h2>
<p><span class="math display">\[B_{Y_{21}} = \frac{r_{Y2}-r_{Y1}r_{12}}{1-r^2_{12}}\frac{sd_Y}{sd_2}\]</span></p>
<p><span class="math display">\[B_{Y_{12}} = \frac{(-0.241)-(0.824)(0.147)}{1-(0.022)}\frac{7.827}{4.769}=(-0.370)*(1.641) =-0.607\]</span></p>
<p>Bu değer, <strong>motivasyon puanı kontrol altına alındıktan sonra</strong>, kaygı puanlarındaki <strong>bir birimlik</strong> artışın öğrencilerin matematik performansından <strong>0.607</strong> birim azaltmaya eğilimli olduğunu önermektedir.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="çoklu-regresyon.html#cb39-1" tabindex="-1"></a>((<span class="fu">cor</span>(performans)[<span class="dv">3</span>,<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">cor</span>(performans)[<span class="dv">2</span>,<span class="dv">1</span>]<span class="sc">*</span><span class="fu">cor</span>(performans)[<span class="dv">2</span>,<span class="dv">3</span>])<span class="sc">/</span></span>
<span id="cb39-2"><a href="çoklu-regresyon.html#cb39-2" tabindex="-1"></a>   (<span class="dv">1</span><span class="sc">-</span><span class="fu">cor</span>(performans)[<span class="dv">2</span>,<span class="dv">3</span>]<span class="sc">^</span><span class="dv">2</span>))<span class="sc">*</span>(<span class="fu">sd</span>(performans<span class="sc">$</span>Performans)<span class="sc">/</span><span class="fu">sd</span>(performans<span class="sc">$</span>Kaygi))</span></code></pre></div>
<pre><code>## [1] -0.607</code></pre>
</div>
<div id="çoklu-regresyon-22" class="section level2" number="4.24">
<h2><span class="header-section-number">4.24</span> Çoklu Regresyon</h2>
<p><span class="math display">\[B_0 = M_Y - B_{Y12}*M_1 -B_{Y21}*M_2\]</span>
<span class="math display">\[B_0 = 18.176  - (0.686)*(39.933) -(-0.607)*(18.701) = 1.744\]</span></p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="çoklu-regresyon.html#cb41-1" tabindex="-1"></a><span class="fu">mean</span>(performans<span class="sc">$</span>Performans)<span class="sc">-</span></span>
<span id="cb41-2"><a href="çoklu-regresyon.html#cb41-2" tabindex="-1"></a>  model<span class="sc">$</span>coefficients[<span class="dv">2</span>]<span class="sc">*</span><span class="fu">mean</span>(performans<span class="sc">$</span>Motivasyon)<span class="sc">-</span></span>
<span id="cb41-3"><a href="çoklu-regresyon.html#cb41-3" tabindex="-1"></a>  model<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span><span class="fu">mean</span>(performans<span class="sc">$</span>Kaygi)</span></code></pre></div>
<pre><code>## Motivasyon 
##       1.74</code></pre>
<p>Bu değer hem motivasyon puanı hem de kaygı puanı 0'a eşit olduğunda yordanan performans puanıdır.</p>
</div>
<div id="çoklu-regresyon-23" class="section level2" number="4.25">
<h2><span class="header-section-number">4.25</span> Çoklu Regresyon</h2>
<p>Böylece yordanan performans puanı</p>
<p><span class="math display">\[Y_{performans_i} = 1.744 + 0.686 X_{motivasyon_i} -  0.607 X_{kaygi_i}\]</span></p>
</div>
<div id="çoklu-regresyon-24" class="section level2" number="4.26">
<h2><span class="header-section-number">4.26</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="çoklu-regresyon.html#cb43-1" tabindex="-1"></a><span class="fu">library</span>(QuantPsyc)</span>
<span id="cb43-2"><a href="çoklu-regresyon.html#cb43-2" tabindex="-1"></a><span class="fu">lm.beta</span>(model)</span></code></pre></div>
<pre><code>## Motivasyon      Kaygi 
##      0.879     -0.370</code></pre>
<ul>
<li><p>Çoklu regresyon eşitliğini elde etmeden önce değişkenlerin her biri
<strong>standartlaştırılırsa</strong> (değişkenlerin her birinin ortalaması 0, standart sapması 1 olacak şekilde ayarlanırsa), sonuçlar <strong>standart sapma</strong> birimlerince ifade edilir.</p></li>
<li><p>Böylece örnekte standartlaştırılmış değişkenler kullanıldığında, yordanan
standartlaştırılmış performans düzeyleri aşağıdaki eşitlikle hesaplanabilir:</p></li>
</ul>
<p><span class="math display">\[Y_{Zperformans_i} = 0.879 X_{Zmotivasyon_i} + -0.370 X_{Zkaygi_i}\]</span>
- Değişkenler standartlaştırıldığında, <strong>kesişim katsayısı 0</strong> olacaktır ve eşitlikte gösterilmeyecektir.</p>
</div>
<div id="çoklu-regresyon-25" class="section level2" number="4.27">
<h2><span class="header-section-number">4.27</span> Çoklu Regresyon</h2>
<ul>
<li><p>Motivasyon için <strong>standartlaştırılmış eğim katsayısı</strong> <span class="math inline">\(\beta_{motivasyon}\)</span> <strong>0.879</strong> değerine eşittir.</p></li>
<li><p>Bu değer, <strong>kaygı puanı kontrol altına alındıktan</strong> sonra, <strong>motivasyon</strong>
puanındaki <strong>bir standart sapmalık artışın</strong> öğrencilerin matematikteki
performans puanlarını <strong>0.879 standart sapma</strong> artırmaya eğilimli olduğunu
önermektedir.</p></li>
<li><p>Benzer şekilde, <strong>kaygı için standartlaştırılmamış eğim katsayısı</strong> <span class="math inline">\(\beta_{motivasyon}\)</span> -0.370 değerine eşittir. Bu değer, <strong>motivasyon puanı kontrol altına</strong> alındıktan sonra, kaygı puanındaki <strong>bir standart sapmalık artışın</strong> öğrencilerin matematikteki performans puanlarını <strong>0.370 standart sapma</strong> azaltmaya eğilimli olduğunu
önermektedir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-26" class="section level2" number="4.28">
<h2><span class="header-section-number">4.28</span> Çoklu Regresyon</h2>
<ul>
<li>Motivasyonun standartlaştırılmış eğim katsayısının mutlak değeri,
kaygının standartlaştırılmış eğim katsayının mutlak değerinden daha büyük olduğundan,
motivasyonun öğrencilerin matematikteki performanslarını yordamada kaygıya
göre daha önemli bir yordayıcı olduğu söylenebilir.</li>
</ul>
<p><strong>|0.879| &gt; |-0.307|</strong></p>
</div>
<div id="çoklu-regresyon-27" class="section level2" number="4.29">
<h2><span class="header-section-number">4.29</span> Çoklu Regresyon</h2>
<ul>
<li><p>Standartlaştırılmış eğim katsayılarının bağıl büyüklükleri "önemin" en iyi
göstergeleri olmasa da, yorumlanmaları kolaydır ve regresyon analizlerinin
yürütülmesinde yararlanılan bilgisayar programlarının çoğu tarafından yazdırılır.</p></li>
<li><p>Ancak bağımsız değişkenlerin <strong>standartlaştırılmamış eğim katsayılarını karşılaştırmak uygun değildir.</strong></p></li>
<li><p>NOT: Bağımsız değişkenler arasında korelasyon olduğunda, <strong>standartlaştırılmış ğim katsayısı</strong> bağımlı değişken ile bağımsız değişken arasındaki <strong>korelasyon katsayısı değildir.</strong></p></li>
</ul>
</div>
<div id="çoklu-regresyon-28" class="section level2" number="4.30">
<h2><span class="header-section-number">4.30</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="çoklu-regresyon.html#cb45-1" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb45-2"><a href="çoklu-regresyon.html#cb45-2" tabindex="-1"></a><span class="fu">ggpairs</span>(performans[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-36-1.png" width="30%" style="display: block; margin: auto;" /></p>
</div>
<div id="çoklu-regresyon-29" class="section level2" number="4.31">
<h2><span class="header-section-number">4.31</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="çoklu-regresyon.html#cb46-1" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb46-2"><a href="çoklu-regresyon.html#cb46-2" tabindex="-1"></a><span class="fu">scatterplot3d</span>(performans[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-37-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="çoklu-regresyon-30" class="section level2" number="4.32">
<h2><span class="header-section-number">4.32</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="çoklu-regresyon.html#cb47-1" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb47-2"><a href="çoklu-regresyon.html#cb47-2" tabindex="-1"></a><span class="fu">scatterplot3d</span>(performans[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],<span class="at">pch =</span> <span class="dv">16</span>, <span class="at">color=</span><span class="st">&quot;steelblue&quot;</span>, <span class="at">angle=</span><span class="dv">75</span>)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-38-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="çoklu-regresyon-31" class="section level2" number="4.33">
<h2><span class="header-section-number">4.33</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="çoklu-regresyon.html#cb48-1" tabindex="-1"></a><span class="fu">scatterplot3d</span>(performans[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>],<span class="at">pch =</span> <span class="dv">16</span>, <span class="at">color=</span><span class="st">&quot;steelblue&quot;</span>,<span class="at">angle=</span><span class="dv">75</span>,<span class="at">box =</span> <span class="cn">FALSE</span>,<span class="at">type =</span> <span class="st">&quot;h&quot;</span>)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-39-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="çoklu-regresyon-32" class="section level2" number="4.34">
<h2><span class="header-section-number">4.34</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="çoklu-regresyon.html#cb49-1" tabindex="-1"></a><span class="fu">library</span>(rgl)</span>
<span id="cb49-2"><a href="çoklu-regresyon.html#cb49-2" tabindex="-1"></a><span class="fu">plot3d</span>(performans<span class="sc">$</span>Performans, performans<span class="sc">$</span>Motivasyon, performans<span class="sc">$</span>Kaygi,</span>
<span id="cb49-3"><a href="çoklu-regresyon.html#cb49-3" tabindex="-1"></a><span class="at">xlab =</span> <span class="st">&quot;Performans&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Motivasyon&quot;</span>, <span class="at">zlab =</span> <span class="st">&quot;Kaygi&quot;</span>, <span class="at">type =</span> <span class="st">&quot;s&quot;</span>,<span class="at">size =</span> <span class="fl">1.5</span>,<span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb49-4"><a href="çoklu-regresyon.html#cb49-4" tabindex="-1"></a><span class="fu">rglwidget</span>() </span></code></pre></div>
<div class="figure" style="text-align: center">
<div id="rgl69370" style="width:672px;height:480px;" class="rglWebGL html-widget" role="img" aria-labelledby="rgl69370-aria"></div>
<script type="application/json" data-for="rgl69370">{"x":{"material":{"color":"#000000","alpha":1,"lit":true,"ambient":"#000000","specular":"#FFFFFF","emission":"#000000","shininess":50,"smooth":true,"front":"filled","back":"filled","size":3,"lwd":1,"fog":true,"point_antialias":false,"line_antialias":false,"texture":null,"textype":"rgb","texmode":"modulate","texmipmap":false,"texminfilter":"linear","texmagfilter":"linear","texenvmap":false,"depth_mask":true,"depth_test":"less","isTransparent":false,"polygon_offset":[0,0],"margin":"","floating":false,"tag":"","blend":["src_alpha","one_minus_src_alpha"]},"rootSubscene":7,"objects":{"13":{"id":13,"type":"spheres","material":{},"vertices":"0","colors":"1","radii":[[0.7039732933044434]],"centers":"2","ignoreExtent":false,"fastTransparency":true,"flags":32771},"15":{"id":15,"type":"text","material":{"lit":false,"margin":0,"floating":true,"edge":[0,1,1]},"vertices":"3","colors":"4","texts":[["Performans"]],"cex":[[1]],"adj":[[0.5,0.5,0.5]],"centers":"5","family":[["sans"]],"font":[[1]],"ignoreExtent":true,"flags":33808},"16":{"id":16,"type":"text","material":{"lit":false,"margin":1,"floating":true,"edge":[1,1,1]},"vertices":"6","colors":"7","texts":[["Motivasyon"]],"cex":[[1]],"adj":[[0.5,0.5,0.5]],"centers":"8","family":[["sans"]],"font":[[1]],"ignoreExtent":true,"flags":33808},"17":{"id":17,"type":"text","material":{"lit":false,"margin":2,"floating":true,"edge":[1,1,1]},"vertices":"9","colors":"10","texts":[["Kaygi"]],"cex":[[1]],"adj":[[0.5,0.5,0.5]],"centers":"11","family":[["sans"]],"font":[[1]],"ignoreExtent":true,"flags":33808},"11":{"id":11,"type":"light","vertices":[[0,0,1]],"colors":[[1,1,1,1],[1,1,1,1],[1,1,1,1]],"viewpoint":true,"finite":false},"10":{"id":10,"type":"background","material":{},"colors":"12","centers":"13","sphere":false,"fogtype":"none","fogscale":1,"flags":32768},"12":{"id":12,"type":"background","material":{"lit":false,"back":"lines"},"colors":"14","centers":"15","sphere":false,"fogtype":"none","fogscale":1,"flags":32768},"14":{"id":14,"type":"bboxdeco","material":{"front":"lines","back":"lines"},"vertices":"16","colors":"17","axes":{"mode":["pretty","pretty","pretty"],"step":[5,5,5],"nticks":[5,5,5],"marklen":[15,15,15],"expand":[1.029999971389771,1.029999971389771,1.029999971389771]},"draw_front":true,"flags":32769},"7":{"id":7,"type":"subscene","par3d":{"antialias":8,"FOV":30,"ignoreExtent":false,"listeners":7,"mouseMode":{"none":"none","left":"trackball","right":"zoom","middle":"fov","wheel":"pull"},"observer":[0,0,125.3147583007812],"modelMatrix":[[0.8970806002616882,0,0,-17.76793670654297],[0,0.2918461263179779,1.51644504070282,-40.72311401367188],[0,-0.8018406629562378,0.5519408583641052,-105.1763000488281],[0,0,0,1]],"projMatrix":[[3.732050895690918,0,0,0],[0,3.732050895690918,0,0],[0,0,-3.863703727722168,-451.7452392578125],[0,0,-1,0]],"skipRedraw":false,"userMatrix":[[1,0,0,0],[0,0.3420201433256682,0.9396926207859085,0],[0,-0.9396926207859085,0.3420201433256682,0],[0,0,0,1]],"userProjection":[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],"scale":[0.8970806002616882,0.8533009886741638,1.613767147064209],"viewport":{"x":0,"y":0,"width":1,"height":1},"zoom":1,"bbox":[3.32689905166626,36.2859001159668,21.17499923706055,55.82500076293945,10.28402137756348,28.60566902160645],"windowRect":[34,57,290,313],"family":"sans","font":1,"cex":1,"useFreeType":false,"fontname":"TT Arial","maxClipPlanes":8,"glVersion":4.6,"activeSubscene":0},"embeddings":{"viewport":"replace","projection":"replace","model":"replace","mouse":"replace"},"objects":[12,14,13,15,16,17,11],"subscenes":[],"flags":34067}},"crosstalk":{"key":[],"group":[],"id":[],"options":[]},"width":672,"height":480,"buffer":{"accessors":[{"bufferView":0,"componentType":5126,"count":15,"type":"VEC3"},{"bufferView":1,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":2,"componentType":5126,"count":15,"type":"VEC3"},{"bufferView":3,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":4,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":5,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":6,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":7,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":8,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":9,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":10,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":11,"componentType":5126,"count":1,"type":"VEC3"},{"bufferView":12,"componentType":5126,"count":1,"type":"VEC4"},{"bufferView":13,"componentType":5121,"count":1,"type":"VEC3"},{"bufferView":14,"componentType":5121,"count":1,"type":"VEC4"},{"bufferView":15,"componentType":5121,"count":1,"type":"VEC3"},{"bufferView":16,"componentType":5126,"count":17,"type":"VEC3"},{"bufferView":17,"componentType":5121,"count":1,"type":"VEC4"}],"bufferViews":[{"buffer":0,"byteLength":180,"byteOffset":0},{"buffer":0,"byteLength":4,"byteOffset":180},{"buffer":0,"byteLength":180,"byteOffset":184},{"buffer":0,"byteLength":12,"byteOffset":364},{"buffer":0,"byteLength":4,"byteOffset":376},{"buffer":0,"byteLength":12,"byteOffset":380},{"buffer":0,"byteLength":12,"byteOffset":392},{"buffer":0,"byteLength":4,"byteOffset":404},{"buffer":0,"byteLength":12,"byteOffset":408},{"buffer":0,"byteLength":12,"byteOffset":420},{"buffer":0,"byteLength":4,"byteOffset":432},{"buffer":0,"byteLength":12,"byteOffset":436},{"buffer":0,"byteLength":16,"byteOffset":448},{"buffer":0,"byteLength":3,"byteOffset":464},{"buffer":0,"byteLength":4,"byteOffset":467},{"buffer":0,"byteLength":3,"byteOffset":471},{"buffer":0,"byteLength":204,"byteOffset":476},{"buffer":0,"byteLength":4,"byteOffset":680}],"buffers":[{"byteLength":684,"bytes":"Ne5FQQAAsEG5LndBiJKDQAAAyEHygp5BXgOtQQAASEJj+pRB4F7HQQAAPEIUlZFB6rPQQQAA\nOEImhitBAJyNQQAAIEKqojJBgVkkQQAA+EEDT5NByy+XQQAAXEIDW+FBGpmZQQAAFEJdiZhB\nzgGOQQAAIEJTUpNBMQEOQgAAWEJuYpJB/lOQQQAAGEJKLGNBV7s1QQAAFEIVF9lBkAzCQQAA\nPEKHPHpBiq0oQQAA8EENGo5BAQAAATXuRUEAALBBuS53QYiSg0AAAMhB8oKeQV4DrUEAAEhC\nY/qUQeBex0EAADxCFJWRQeqz0EEAADhCJoYrQQCcjUEAACBCqqIyQYFZJEEAAPhBA0+TQcsv\nl0EAAFxCA1vhQRqZmUEAABRCXYmYQc4BjkEAACBCU1KTQTEBDkIAAFhCbmKSQf5TkEEAABhC\nSixjQVe7NUEAABRCFRfZQZAMwkEAADxChzx6QYqtKEEAAPBBDRqOQQAAwH8AAIBAAACAPwAA\nAAEAAMB/AACAQAAAgD8AAMB/AACAQAAAgD8AAAABAADAfwAAgEAAAIA/AADAfwAAgEAAAIA/\nAAAAAQAAwH8AAIBAAACAP5mYmD6ZmJg+mZiYPgAAgD8AAAABAQEBAAAAAAAAAKBAAADAfwAA\nwH8AACBBAADAfwAAwH8AAHBBAADAfwAAwH8AAKBBAADAfwAAwH8AAMhBAADAfwAAwH8AAPBB\nAADAfwAAwH8AAAxCAADAfwAAwH8AAMB/AADIQQAAwH8AAMB/AADwQQAAwH8AAMB/AAAMQgAA\nwH8AAMB/AAAgQgAAwH8AAMB/AAA0QgAAwH8AAMB/AABIQgAAwH8AAMB/AABcQgAAwH8AAMB/\nAADAfwAAcEEAAMB/AADAfwAAoEEAAMB/AADAfwAAyEEAAAAB"}]},"context":{"shiny":false,"rmarkdown":null},"vertexShader":"#line 2 1\n// File 1 is the vertex shader\n#ifdef GL_ES\n#ifdef GL_FRAGMENT_PRECISION_HIGH\nprecision highp float;\n#else\nprecision mediump float;\n#endif\n#endif\n\nattribute vec3 aPos;\nattribute vec4 aCol;\nuniform mat4 mvMatrix;\nuniform mat4 prMatrix;\nvarying vec4 vCol;\nvarying vec4 vPosition;\n\n#ifdef NEEDS_VNORMAL\nattribute vec3 aNorm;\nuniform mat4 normMatrix;\nvarying vec4 vNormal;\n#endif\n\n#if defined(HAS_TEXTURE) || defined (IS_TEXT)\nattribute vec2 aTexcoord;\nvarying vec2 vTexcoord;\n#endif\n\n#ifdef FIXED_SIZE\nuniform vec3 textScale;\n#endif\n\n#ifdef FIXED_QUADS\nattribute vec3 aOfs;\n#endif\n\n#ifdef IS_TWOSIDED\n#ifdef HAS_NORMALS\nvarying float normz;\nuniform mat4 invPrMatrix;\n#else\nattribute vec3 aPos1;\nattribute vec3 aPos2;\nvarying float normz;\n#endif\n#endif // IS_TWOSIDED\n\n#ifdef FAT_LINES\nattribute vec3 aNext;\nattribute vec2 aPoint;\nvarying vec2 vPoint;\nvarying float vLength;\nuniform float uAspect;\nuniform float uLwd;\n#endif\n\n#ifdef USE_ENVMAP\nvarying vec3 vReflection;\n#endif\n\nvoid main(void) {\n  \n#ifndef IS_BRUSH\n#if defined(NCLIPPLANES) || !defined(FIXED_QUADS) || defined(HAS_FOG) || defined(USE_ENVMAP)\n  vPosition = mvMatrix * vec4(aPos, 1.);\n#endif\n  \n#ifndef FIXED_QUADS\n  gl_Position = prMatrix * vPosition;\n#endif\n#endif // !IS_BRUSH\n  \n#ifdef IS_POINTS\n  gl_PointSize = POINTSIZE;\n#endif\n  \n  vCol = aCol;\n  \n// USE_ENVMAP implies NEEDS_VNORMAL\n\n#ifdef NEEDS_VNORMAL\n  vNormal = normMatrix * vec4(-aNorm, dot(aNorm, aPos));\n#endif\n\n#ifdef USE_ENVMAP\n  vReflection = normalize(reflect(vPosition.xyz/vPosition.w, \n                        normalize(vNormal.xyz/vNormal.w)));\n#endif\n  \n#ifdef IS_TWOSIDED\n#ifdef HAS_NORMALS\n  /* normz should be calculated *after* projection */\n  normz = (invPrMatrix*vNormal).z;\n#else\n  vec4 pos1 = prMatrix*(mvMatrix*vec4(aPos1, 1.));\n  pos1 = pos1/pos1.w - gl_Position/gl_Position.w;\n  vec4 pos2 = prMatrix*(mvMatrix*vec4(aPos2, 1.));\n  pos2 = pos2/pos2.w - gl_Position/gl_Position.w;\n  normz = pos1.x*pos2.y - pos1.y*pos2.x;\n#endif\n#endif // IS_TWOSIDED\n  \n#ifdef NEEDS_VNORMAL\n  vNormal = vec4(normalize(vNormal.xyz/vNormal.w), 1);\n#endif\n  \n#if defined(HAS_TEXTURE) || defined(IS_TEXT)\n  vTexcoord = aTexcoord;\n#endif\n  \n#if defined(FIXED_SIZE) && !defined(ROTATING)\n  vec4 pos = prMatrix * mvMatrix * vec4(aPos, 1.);\n  pos = pos/pos.w;\n  gl_Position = pos + vec4(aOfs*textScale, 0.);\n#endif\n  \n#if defined(IS_SPRITES) && !defined(FIXED_SIZE)\n  vec4 pos = mvMatrix * vec4(aPos, 1.);\n  pos = pos/pos.w + vec4(aOfs,  0.);\n  gl_Position = prMatrix*pos;\n#endif\n  \n#ifdef FAT_LINES\n  /* This code was inspired by Matt Deslauriers' code in \n   https://mattdesl.svbtle.com/drawing-lines-is-hard */\n  vec2 aspectVec = vec2(uAspect, 1.0);\n  mat4 projViewModel = prMatrix * mvMatrix;\n  vec4 currentProjected = projViewModel * vec4(aPos, 1.0);\n  currentProjected = currentProjected/currentProjected.w;\n  vec4 nextProjected = projViewModel * vec4(aNext, 1.0);\n  vec2 currentScreen = currentProjected.xy * aspectVec;\n  vec2 nextScreen = (nextProjected.xy / nextProjected.w) * aspectVec;\n  float len = uLwd;\n  vec2 dir = vec2(1.0, 0.0);\n  vPoint = aPoint;\n  vLength = length(nextScreen - currentScreen)/2.0;\n  vLength = vLength/(vLength + len);\n  if (vLength > 0.0) {\n    dir = normalize(nextScreen - currentScreen);\n  }\n  vec2 normal = vec2(-dir.y, dir.x);\n  dir.x /= uAspect;\n  normal.x /= uAspect;\n  vec4 offset = vec4(len*(normal*aPoint.x*aPoint.y - dir), 0.0, 0.0);\n  gl_Position = currentProjected + offset;\n#endif\n  \n#ifdef IS_BRUSH\n  gl_Position = vec4(aPos, 1.);\n#endif\n}","fragmentShader":"#line 2 2\n// File 2 is the fragment shader\n#ifdef GL_ES\n#ifdef GL_FRAGMENT_PRECISION_HIGH\nprecision highp float;\n#else\nprecision mediump float;\n#endif\n#endif\nvarying vec4 vCol; // carries alpha\nvarying vec4 vPosition;\n#if defined(HAS_TEXTURE) || defined (IS_TEXT)\nvarying vec2 vTexcoord;\nuniform sampler2D uSampler;\n#endif\n\n#ifdef HAS_FOG\nuniform int uFogMode;\nuniform vec3 uFogColor;\nuniform vec4 uFogParms;\n#endif\n\n#if defined(IS_LIT) && !defined(FIXED_QUADS)\nvarying vec4 vNormal;\n#endif\n\n#if NCLIPPLANES > 0\nuniform vec4 vClipplane[NCLIPPLANES];\n#endif\n\n#if NLIGHTS > 0\nuniform mat4 mvMatrix;\n#endif\n\n#ifdef IS_LIT\nuniform vec3 emission;\nuniform float shininess;\n#if NLIGHTS > 0\nuniform vec3 ambient[NLIGHTS];\nuniform vec3 specular[NLIGHTS]; // light*material\nuniform vec3 diffuse[NLIGHTS];\nuniform vec3 lightDir[NLIGHTS];\nuniform bool viewpoint[NLIGHTS];\nuniform bool finite[NLIGHTS];\n#endif\n#endif // IS_LIT\n\n#ifdef IS_TWOSIDED\nuniform bool front;\nvarying float normz;\n#endif\n\n#ifdef FAT_LINES\nvarying vec2 vPoint;\nvarying float vLength;\n#endif\n\n#ifdef USE_ENVMAP\nvarying vec3 vReflection;\n#endif\n\nvoid main(void) {\n  vec4 fragColor;\n#ifdef FAT_LINES\n  vec2 point = vPoint;\n  bool neg = point.y < 0.0;\n  point.y = neg ? (point.y + vLength)/(1.0 - vLength) :\n                 -(point.y - vLength)/(1.0 - vLength);\n#if defined(IS_TRANSPARENT) && defined(IS_LINESTRIP)\n  if (neg && length(point) <= 1.0) discard;\n#endif\n  point.y = min(point.y, 0.0);\n  if (length(point) > 1.0) discard;\n#endif // FAT_LINES\n  \n#ifdef ROUND_POINTS\n  vec2 coord = gl_PointCoord - vec2(0.5);\n  if (length(coord) > 0.5) discard;\n#endif\n  \n#if NCLIPPLANES > 0\n  for (int i = 0; i < NCLIPPLANES; i++)\n    if (dot(vPosition, vClipplane[i]) < 0.0) discard;\n#endif\n    \n#ifdef FIXED_QUADS\n    vec3 n = vec3(0., 0., 1.);\n#elif defined(IS_LIT)\n    vec3 n = normalize(vNormal.xyz);\n#endif\n    \n#ifdef IS_TWOSIDED\n    if ((normz <= 0.) != front) discard;\n#endif\n\n#ifdef IS_LIT\n    vec3 eye = normalize(-vPosition.xyz/vPosition.w);\n    vec3 lightdir;\n    vec4 colDiff;\n    vec3 halfVec;\n    vec4 lighteffect = vec4(emission, 0.);\n    vec3 col;\n    float nDotL;\n#ifdef FIXED_QUADS\n    n = -faceforward(n, n, eye);\n#endif\n    \n#if NLIGHTS > 0\n    for (int i=0;i<NLIGHTS;i++) {\n      colDiff = vec4(vCol.rgb * diffuse[i], vCol.a);\n      lightdir = lightDir[i];\n      if (!viewpoint[i])\n        lightdir = (mvMatrix * vec4(lightdir, 1.)).xyz;\n      if (!finite[i]) {\n        halfVec = normalize(lightdir + eye);\n      } else {\n        lightdir = normalize(lightdir - vPosition.xyz/vPosition.w);\n        halfVec = normalize(lightdir + eye);\n      }\n      col = ambient[i];\n      nDotL = dot(n, lightdir);\n      col = col + max(nDotL, 0.) * colDiff.rgb;\n      col = col + pow(max(dot(halfVec, n), 0.), shininess) * specular[i];\n      lighteffect = lighteffect + vec4(col, colDiff.a);\n    }\n#endif\n    \n#else // not IS_LIT\n    vec4 colDiff = vCol;\n    vec4 lighteffect = colDiff;\n#endif\n    \n#ifdef IS_TEXT\n    vec4 textureColor = lighteffect*texture2D(uSampler, vTexcoord);\n#endif\n    \n#ifdef HAS_TEXTURE\n\n// These calculations use the definitions from \n// https://docs.gl/gl3/glTexEnv\n\n#ifdef USE_ENVMAP\n    float m = 2.0 * sqrt(dot(vReflection, vReflection) + 2.0*vReflection.z + 1.0);\n    vec4 textureColor = texture2D(uSampler, vReflection.xy / m + vec2(0.5, 0.5));\n#else\n    vec4 textureColor = texture2D(uSampler, vTexcoord);\n#endif\n\n#ifdef TEXTURE_rgb\n\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\n    textureColor = vec4(textureColor.rgb, lighteffect.a);\n#endif \n\n#ifdef TEXMODE_modulate\n    textureColor = lighteffect*vec4(textureColor.rgb, 1.);\n#endif\n\n#ifdef TEXMODE_blend\n    textureColor = vec4((1. - textureColor.rgb) * lighteffect.rgb, lighteffect.a);\n#endif\n\n#ifdef TEXMODE_add\n    textureColor = vec4(lighteffect.rgb + textureColor.rgb, lighteffect.a);\n#endif\n\n#endif //TEXTURE_rgb\n        \n#ifdef TEXTURE_rgba\n\n#ifdef TEXMODE_replace\n// already done\n#endif \n\n#ifdef TEXMODE_modulate\n    textureColor = lighteffect*textureColor;\n#endif\n\n#ifdef TEXMODE_decal\n    textureColor = vec4((1. - textureColor.a)*lighteffect.rgb) +\n                     textureColor.a*textureColor.rgb, \n                     lighteffect.a);\n#endif\n\n#ifdef TEXMODE_blend\n    textureColor = vec4((1. - textureColor.rgb) * lighteffect.rgb,\n                    lighteffect.a*textureColor.a);\n#endif\n\n#ifdef TEXMODE_add\n    textureColor = vec4(lighteffect.rgb + textureColor.rgb,\n                    lighteffect.a*textureColor.a);\n#endif\n    \n#endif //TEXTURE_rgba\n    \n#ifdef TEXTURE_alpha\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\n    textureColor = vec4(lighteffect.rgb, textureColor.a);\n#endif \n\n#if defined(TEXMODE_modulate) || defined(TEXMODE_blend) || defined(TEXMODE_add)\n    textureColor = vec4(lighteffect.rgb, lighteffect.a*textureColor.a);\n#endif\n \n#endif\n    \n// The TEXTURE_luminance values are not from that reference    \n#ifdef TEXTURE_luminance\n    float luminance = dot(vec3(1.,1.,1.),textureColor.rgb)/3.;\n\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\n    textureColor = vec4(luminance, luminance, luminance, lighteffect.a);\n#endif \n\n#ifdef TEXMODE_modulate\n    textureColor = vec4(luminance*lighteffect.rgb, lighteffect.a);\n#endif\n\n#ifdef TEXMODE_blend\n    textureColor = vec4((1. - luminance)*lighteffect.rgb,\n                        lighteffect.a);\n#endif\n\n#ifdef TEXMODE_add\n    textureColor = vec4(luminance + lighteffect.rgb, lighteffect.a);\n#endif\n\n#endif // TEXTURE_luminance\n \n    \n#ifdef TEXTURE_luminance_alpha\n    float luminance = dot(vec3(1.,1.,1.),textureColor.rgb)/3.;\n\n#if defined(TEXMODE_replace) || defined(TEXMODE_decal)\n    textureColor = vec4(luminance, luminance, luminance, textureColor.a);\n#endif \n\n#ifdef TEXMODE_modulate\n    textureColor = vec4(luminance*lighteffect.rgb, \n                        textureColor.a*lighteffect.a);\n#endif\n\n#ifdef TEXMODE_blend\n    textureColor = vec4((1. - luminance)*lighteffect.rgb,\n                        textureColor.a*lighteffect.a);\n#endif\n\n#ifdef TEXMODE_add\n    textureColor = vec4(luminance + lighteffect.rgb, \n                        textureColor.a*lighteffect.a);\n\n#endif\n\n#endif // TEXTURE_luminance_alpha\n    \n    fragColor = textureColor;\n\n#elif defined(IS_TEXT)\n    if (textureColor.a < 0.1)\n      discard;\n    else\n      fragColor = textureColor;\n#else\n    fragColor = lighteffect;\n#endif // HAS_TEXTURE\n    \n#ifdef HAS_FOG\n    // uFogParms elements: x = near, y = far, z = fogscale, w = (1-sin(FOV/2))/(1+sin(FOV/2))\n    // In Exp and Exp2: use density = density/far\n    // fogF will be the proportion of fog\n    // Initialize it to the linear value\n    float fogF;\n    if (uFogMode > 0) {\n      fogF = (uFogParms.y - vPosition.z/vPosition.w)/(uFogParms.y - uFogParms.x);\n      if (uFogMode > 1)\n        fogF = mix(uFogParms.w, 1.0, fogF);\n      fogF = fogF*uFogParms.z;\n      if (uFogMode == 2)\n        fogF = 1.0 - exp(-fogF);\n      // Docs are wrong: use (density*c)^2, not density*c^2\n      // https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/src/mesa/swrast/s_fog.c#L58\n      else if (uFogMode == 3)\n        fogF = 1.0 - exp(-fogF*fogF);\n      fogF = clamp(fogF, 0.0, 1.0);\n      gl_FragColor = vec4(mix(fragColor.rgb, uFogColor, fogF), fragColor.a);\n    } else gl_FragColor = fragColor;\n#else\n    gl_FragColor = fragColor;\n#endif // HAS_FOG\n    \n}","players":[],"webGLoptions":{"preserveDrawingBuffer":true}},"evals":[],"jsHooks":[]}</script>
<p id="rgl69370-aria" hidden>
</p>
</div>
</div>
<div id="çoklu-regresyon-33" class="section level2" number="4.35">
<h2><span class="header-section-number">4.35</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="çoklu-regresyon.html#cb50-1" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(performans[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="at">angle=</span><span class="dv">55</span>,<span class="at">type=</span><span class="st">&#39;h&#39;</span>,</span>
<span id="cb50-2"><a href="çoklu-regresyon.html#cb50-2" tabindex="-1"></a>                   <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">color =</span> <span class="st">&quot;steelblue&quot;</span>)</span>
<span id="cb50-3"><a href="çoklu-regresyon.html#cb50-3" tabindex="-1"></a></span>
<span id="cb50-4"><a href="çoklu-regresyon.html#cb50-4" tabindex="-1"></a><span class="co"># add a plane representing the fit of the model</span></span>
<span id="cb50-5"><a href="çoklu-regresyon.html#cb50-5" tabindex="-1"></a>p<span class="sc">$</span><span class="fu">plane3d</span>(model, <span class="at">col=</span><span class="st">&#39;orangered&#39;</span>)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-41-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="çoklu-regresyon-34" class="section level2" number="4.36">
<h2><span class="header-section-number">4.36</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="çoklu-regresyon.html#cb51-1" tabindex="-1"></a><span class="co"># augment(model,data=performans)[,5]</span></span>
<span id="cb51-2"><a href="çoklu-regresyon.html#cb51-2" tabindex="-1"></a>model<span class="sc">$</span>fitted.values</span>
<span id="cb51-3"><a href="çoklu-regresyon.html#cb51-3" tabindex="-1"></a>model<span class="sc">$</span>residuals</span></code></pre></div>
<pre><code>##     1     2     3     4     5     6     7     8     9    10    11    12    13 
##  7.46  6.87 24.75 22.95 26.80 22.42 11.84 22.38 15.56 18.01 27.69 19.20 10.66 
##    14    15 
## 24.50 11.55 
## attr(,&quot;format.spss&quot;)
## [1] &quot;F8.2&quot;
## attr(,&quot;display_width&quot;)
## [1] 9
##      1      2      3      4      5      6      7      8      9     10     11 
##  4.910 -2.757 -3.123  1.972 -0.716 -4.715 -1.565 -3.485  3.642 -0.262  7.809 
##     12     13     14     15 
## -1.160  0.701 -0.246 -1.004 
## attr(,&quot;format.spss&quot;)
## [1] &quot;F8.2&quot;
## attr(,&quot;display_width&quot;)
## [1] 9</code></pre>
<ul>
<li>Öğrencilerin <strong>standratlastırılmamış yordanan matematik performans düzeyleri</strong> ve <strong>standartlaştırılmamış artıkları</strong> modelden çekilebilir.</li>
<li>Örneğin, ilk öğrenci için standratlastırılmamış yordanan değer yaklaşık <strong>7.46</strong>, artık ise yaklaşık <strong>4.910</strong>’tir.</li>
</ul>
</div>
<div id="çoklu-regresyon-35" class="section level2" number="4.37">
<h2><span class="header-section-number">4.37</span> Çoklu Regresyon</h2>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="çoklu-regresyon.html#cb53-1" tabindex="-1"></a><span class="fu">library</span>(outliers)</span>
<span id="cb53-2"><a href="çoklu-regresyon.html#cb53-2" tabindex="-1"></a>model<span class="sc">$</span>fitted.values <span class="sc">%&gt;%</span> <span class="fu">scores</span>(<span class="at">type =</span> <span class="st">&quot;z&quot;</span>)</span>
<span id="cb53-3"><a href="çoklu-regresyon.html#cb53-3" tabindex="-1"></a>model<span class="sc">$</span>residuals <span class="sc">%&gt;%</span> <span class="fu">scores</span>(<span class="at">type =</span> <span class="st">&quot;z&quot;</span>)</span></code></pre></div>
<pre><code>##       1       2       3       4       5       6       7       8       9      10 
## -1.5176 -1.6014  0.9311  0.6760  1.2219  0.6005 -0.8978  0.5959 -0.3708 -0.0231 
##      11      12      13      14      15 
##  1.3478  0.1452 -1.0648  0.8960 -0.9390 
## attr(,&quot;format.spss&quot;)
## [1] &quot;F8.2&quot;
## attr(,&quot;display_width&quot;)
## [1] 9
##       1       2       3       4       5       6       7       8       9      10 
##  1.4528 -0.8158 -0.9242  0.5836 -0.2118 -1.3950 -0.4631 -1.0313  1.0775 -0.0775 
##      11      12      13      14      15 
##  2.3106 -0.3432  0.2073 -0.0729 -0.2970 
## attr(,&quot;format.spss&quot;)
## [1] &quot;F8.2&quot;
## attr(,&quot;display_width&quot;)
## [1] 9</code></pre>
<ul>
<li>Öğrencilerin <strong>standratlastırılmış yordanan matematik performans düzeyleri</strong> ve <strong>standartlaştırılmış artıkları</strong> modelden çekilebilir.</li>
</ul>
</div>
<div id="çoklu-regresyon-36" class="section level2" number="4.38">
<h2><span class="header-section-number">4.38</span> Çoklu Regresyon</h2>
<ul>
<li>Regresyon katsayılarından her birinin istatistiksel olarak sıfırdan
farklı olup olmadığı test edilebilir. Bu durumda regresyon
katsayılarına ilişkin test edilecek sıfır hipotezleri aşağıdaki gibidir:</li>
</ul>
<p><span class="math inline">\(H_0: \beta_1 = 0\)</span>
- Kaygı düzeyleri eşit olan öğrenciler için
motivasyon düzeylerindeki farklılıklar
performans düzeylerinde farklılığa yol açar mı?</p>
<p><span class="math inline">\(H_0: \beta_2 = 0\)</span>
- Motivasyon düzeyleri eşit olan öğrenciler için
kaygı düzeylerindeki farklılıklar performans
düzeylerinde farklılığa yol açar mı?</p>
</div>
<div id="çoklu-regresyon-37" class="section level2" number="4.39">
<h2><span class="header-section-number">4.39</span> Çoklu Regresyon</h2>
<p>Hipotez testlerine ilişkin <strong>t istatistiği</strong>, standartlaştırılmamış regresyon
katsayılarının standart hatalarına bölünmesi ile hesaplanır.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="çoklu-regresyon.html#cb55-1" tabindex="-1"></a><span class="fu">tidy</span>(model) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span>
<span id="cb55-2"><a href="çoklu-regresyon.html#cb55-2" tabindex="-1"></a><span class="fl">0.686</span> <span class="sc">/</span><span class="fl">0.0984</span></span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">1.744</td>
<td align="right">5.096</td>
<td align="right">0.342</td>
<td align="right">0.738</td>
</tr>
<tr class="even">
<td align="left">Motivasyon</td>
<td align="right">0.686</td>
<td align="right">0.098</td>
<td align="right">6.975</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">Kaygi</td>
<td align="right">-0.607</td>
<td align="right">0.207</td>
<td align="right">-2.936</td>
<td align="right">0.012</td>
</tr>
</tbody>
</table>
<pre><code>## [1] 6.97</code></pre>
<ul>
<li>Motivasyona ilişkin eğim için testin, olasılık değeri (p ˂ 0.001)
0.05’ten daha küçük olduğundan, anlamlı olarak sıfırdan farklı
olduğu görülmektedir.</li>
</ul>
</div>
<div id="çoklu-regresyon-38" class="section level2" number="4.40">
<h2><span class="header-section-number">4.40</span> Çoklu Regresyon</h2>
<ul>
<li><p>Hipotez testlerine ilişkin t istatistiği standartlaştırılmamış regresyon
katsayılarının standart hatalarına bölünmesi ile hesaplanır.</p></li>
<li><p>Kaygıya ilişkin eğim de anlamlıdır <strong>(t = -2.936, p = 0.012)</strong>, öğrencilerin
motivasyon düzeylerindeki farklılıklar kontrol altına alınsa bile, öğrencilerin
kaygı düzeyleri performans düzeylerinde fark yapmaktadır ve kaygı düzeyi negatif bir etkiye
sahiptir.</p></li>
</ul>
</div>
<div id="çoklu-regresyon-39" class="section level2" number="4.41">
<h2><span class="header-section-number">4.41</span> Çoklu Regresyon</h2>
<ul>
<li><p>Hipotez testlerine ilişkin t istatistiği <strong>standartlaştırılmamış regresyon
katsayılarının standart hatalarına</strong> bölünmesi ile hesaplanır.</p></li>
<li><p>Regresyon katsayısının <strong>standart hatası tekrarlanan örneklemlerde
istatistiğin değişkenliğini</strong> belirtir.</p></li>
<li><p>İki regresyon katsayısı ile ilgili <strong>p</strong> değerleri 0.05 alfa düzeyinden daha
küçüktür, bu nedenle her iki bağımsız değişken de öğrencilerin matematikteki
performanslarını yordamada <strong>istatistiksel olarak anlamlıdır.</strong></p></li>
</ul>
</div>
<div id="çoklu-regresyon-40" class="section level2" number="4.42">
<h2><span class="header-section-number">4.42</span> Çoklu Regresyon</h2>
<ul>
<li>Çoklu regresyon modelini bir <strong>yol şeması</strong> ile sunmak oldukça kullanışlıdır.</li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="çoklu-regresyon.html#cb57-1" tabindex="-1"></a><span class="co"># path model</span></span>
<span id="cb57-2"><a href="çoklu-regresyon.html#cb57-2" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb57-3"><a href="çoklu-regresyon.html#cb57-3" tabindex="-1"></a><span class="fu">library</span>(lavaanPlot)</span>
<span id="cb57-4"><a href="çoklu-regresyon.html#cb57-4" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="st">&#39;Performans ~  Motivasyon + Kaygi&#39;</span></span>
<span id="cb57-5"><a href="çoklu-regresyon.html#cb57-5" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">sem</span>(model_1, <span class="at">data =</span> performans)</span>
<span id="cb57-6"><a href="çoklu-regresyon.html#cb57-6" tabindex="-1"></a><span class="fu">coef</span>(fit1)</span></code></pre></div>
<pre><code>##  Performans~Motivasyon       Performans~Kaygi Performans~~Performans 
##                  0.686                 -0.607                 10.661</code></pre>
</div>
<div id="çoklu-regresyon-41" class="section level2" number="4.43">
<h2><span class="header-section-number">4.43</span> Çoklu Regresyon</h2>
<p>Standart cozum</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="çoklu-regresyon.html#cb59-1" tabindex="-1"></a><span class="fu">lavaanPlot</span>(<span class="at">model =</span> fit1, <span class="at">coefs =</span> <span class="cn">TRUE</span>, <span class="at">stand =</span> <span class="cn">TRUE</span>, <span class="at">sig =</span> <span class="fl">0.05</span>) </span></code></pre></div>
<div class="grViz html-widget html-fill-item" id="htmlwidget-e02a766674befec24745" style="width:30%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-e02a766674befec24745">{"x":{"diagram":" digraph plot { \n graph [ overlap = true, fontsize = 10 ] \n node [ shape = box ] \n node [shape = box] \n Motivasyon; Kaygi; Performans \n node [shape = oval] \n  \n \n edge [ color = black ] \n Motivasyon->Performans [label = \"0.88\"] Kaygi->Performans [label = \"-0.37\"]  \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="çoklu-regresyon-42" class="section level2" number="4.44">
<h2><span class="header-section-number">4.44</span> Çoklu Regresyon</h2>
<p>Standart olmayan cozum:</p>
<p>Not: Araştırmacılar özellikle ortalamaların yapısı ile ilgilenmedikleri sürece yol şemasında <span class="math inline">\(b_0\)</span> gösterilmez.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="çoklu-regresyon.html#cb60-1" tabindex="-1"></a><span class="fu">lavaanPlot</span>(<span class="at">model =</span> fit1, <span class="at">coefs =</span> <span class="cn">TRUE</span>, <span class="at">stand =</span> <span class="cn">FALSE</span>, <span class="at">sig =</span> <span class="fl">0.05</span>) </span></code></pre></div>
<div class="grViz html-widget html-fill-item" id="htmlwidget-f4b3434d01988c6baf85" style="width:30%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-f4b3434d01988c6baf85">{"x":{"diagram":" digraph plot { \n graph [ overlap = true, fontsize = 10 ] \n node [ shape = box ] \n node [shape = box] \n Motivasyon; Kaygi; Performans \n node [shape = oval] \n  \n \n edge [ color = black ] \n Motivasyon->Performans [label = \"0.69\"] Kaygi->Performans [label = \"-0.61\"]  \n}","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="çoklu-regresyon-43" class="section level2" number="4.45">
<h2><span class="header-section-number">4.45</span> Çoklu Regresyon</h2>
<ul>
<li>Öğrencilerin matematik performanslarının düzeyini motivasyon
ve kaygı düzeylerinden yordamak için çoklu regresyon analizi
gerçekleştirilmiştir. Genel regresyon istatistiksel olarak anlamlıdır
<span class="math inline">\(F_{[2, 12]} = 26.188, p &lt; .001\)</span> ve <span class="math inline">\(R^2 = 0.814\)</span> Öğrencilerin hem
motivasyonlarının düzeyi ( <span class="math inline">\(b_1 = 0.686\)</span>) hem kaygılarının düzeyi( <span class="math inline">\(b_2 = -0.607\)</span>) matematik performanslarının düzeyinin istatistiksel olarak anlamlı yordayıcılarıdır,
<span class="math inline">\(t = 6.975; p &lt; .001, t = -2.936; p = .012\)</span></li>
</ul>
</div>
<div id="regresyon-eşitliğinin-oluşturulması" class="section level2" number="4.46">
<h2><span class="header-section-number">4.46</span> Regresyon Eşitliğinin Oluşturulması</h2>
<p><strong>Aşamalı (Stepwise) Regresyon</strong></p>
<ul>
<li><p>Bir regresyon modeline dahil edilebilecek çok sayıda değişken
bulunduğunda, bu değişkenlerden <strong>en uygun</strong> regresyon eşitliğinin
oluşturulması için değişken seçiminde çeşitli yöntemler vardır. Bu
yöntemlerden birisi aşamalı <strong>stepwise</strong> regresyondur.</p></li>
<li><p>Aşamalı regresyon yöntemi <strong>her bağımsız değişkenin regresyon
modeline</strong> katkısının incelenmesini sağlar.</p></li>
<li><p>Bu yönteme göre önce <strong>bağımlı değişkenle en yüksek korelasyona</strong>
sahip bağımsız değişken seçilerek basit regresyon modeli kurulur.</p></li>
</ul>
</div>
<div id="regresyon-eşitliğinin-oluşturulması-1" class="section level2" number="4.47">
<h2><span class="header-section-number">4.47</span> Regresyon Eşitliğinin Oluşturulması</h2>
<p><strong>Aşamalı (Stepwise) Regresyon</strong></p>
<ul>
<li><p>Birinci regresyon eşitliğinden kalan <strong>hata varyansının istatistiksel olarak anlamlı kısmını en çok açıklayan bağımsız değişkeni</strong> bulmak
için <strong>kısmi korelasyon</strong> katsayıları incelenir ve en yüksek <strong>kısmi korelasyon katsayısına</strong> sahip bağımsız değişken modele eklenir.</p></li>
<li><p>İki bağımsız değişken ile regresyon eşitliği yeniden hesaplanır ve
<strong>eklenen değişkenin modele anlamlı katkısı olup olmadığı</strong> test edilir.
Bu işlem modele anlamlı katkı sağlayacak değişken kalmayana
kadar devam eder.</p></li>
</ul>
</div>
<div id="aşamalı-regresyon" class="section level2" number="4.48">
<h2><span class="header-section-number">4.48</span> Aşamalı regresyon</h2>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="çoklu-regresyon.html#cb61-1" tabindex="-1"></a>sadece_kesisim  <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span> Motivasyon, <span class="at">data=</span>performans)</span>
<span id="cb61-2"><a href="çoklu-regresyon.html#cb61-2" tabindex="-1"></a><span class="fu">glance</span>(sadece_kesisim)</span></code></pre></div>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="10%" />
<col width="14%" />
<col width="6%" />
<col width="10%" />
<col width="8%" />
<col width="3%" />
<col width="7%" />
<col width="5%" />
<col width="5%" />
<col width="9%" />
<col width="12%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.68</td>
<td align="right">0.655</td>
<td align="right">4.6</td>
<td align="right">27.6</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">-43.1</td>
<td align="right">92.2</td>
<td align="right">94.3</td>
<td align="right">275</td>
<td align="right">13</td>
<td align="right">15</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="çoklu-regresyon.html#cb62-1" tabindex="-1"></a>tum  <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span>  Motivasyon <span class="sc">+</span> Kaygi, <span class="at">data=</span>performans)</span>
<span id="cb62-2"><a href="çoklu-regresyon.html#cb62-2" tabindex="-1"></a><span class="fu">glance</span>(tum)</span></code></pre></div>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="10%" />
<col width="14%" />
<col width="6%" />
<col width="10%" />
<col width="8%" />
<col width="3%" />
<col width="7%" />
<col width="5%" />
<col width="5%" />
<col width="9%" />
<col width="12%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.814</td>
<td align="right">0.783</td>
<td align="right">3.65</td>
<td align="right">26.2</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">-39</td>
<td align="right">86.1</td>
<td align="right">88.9</td>
<td align="right">160</td>
<td align="right">12</td>
<td align="right">15</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="aşamalı-regresyon-1" class="section level2" number="4.49">
<h2><span class="header-section-number">4.49</span> Aşamalı regresyon</h2>
<ul>
<li><p>Birinci modelde <strong>motivasyon tek yordayıcıdır</strong> ve performans ile korelasyonu <strong>0.824’tür</strong> <span class="math inline">\(R = 0.824\)</span> . Motivasyon tek başına performans puanlarındaki
varyansın yaklaşık <strong>%68’ini</strong> <span class="math inline">\(R^2 = 0.680\)</span> açıklamaktadır.</p></li>
<li><p>Modele <strong>kaygının yordayıcı olarak eklenmesiyle</strong> korelasyon <strong>0.902</strong>’ye <span class="math inline">\(R = 0.902\)</span> yükselmiştir. Motivasyon ve kaygı birlikte performans puanlarındaki
varyansın yaklaşık <strong>%81</strong>’ini <span class="math inline">\(R^2 = 0.814\)</span> açıklamaktadır.</p></li>
</ul>
</div>
<div id="aşamalı-regresyon-2" class="section level2" number="4.50">
<h2><span class="header-section-number">4.50</span> Aşamalı regresyon</h2>
<ul>
<li>Modele kaygının eklenmesiyle <span class="math inline">\(R^2\)</span> değişimi (R Square Change) 0.134’tür. <span class="math inline">\(R^2\)</span> değerindeki bu değişim kaygının eklenmesiyle açıklanan varyans oranında
<strong>%13</strong>’lük bir artış olduğu anlamındadır. <span class="math inline">\(R^2\)</span> değişimi F testi (F Change) ile test edilmiştir ve F değerindeki değişim istatistiksel olarak anlamlıdır <span class="math inline">\(p = 0.012\)</span> Dolayısıyla modele eklenen kaygı değişkeni yordamayı anlamlı olarak
geliştirmiştir.</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="çoklu-regresyon.html#cb63-1" tabindex="-1"></a>asamali <span class="ot">&lt;-</span> <span class="fu">step</span>(sadece_kesisim, <span class="at">direction=</span><span class="st">&#39;forward&#39;</span>, <span class="at">scope=</span><span class="fu">formula</span>(tum), <span class="at">trace=</span><span class="dv">0</span>)</span>
<span id="cb63-2"><a href="çoklu-regresyon.html#cb63-2" tabindex="-1"></a><span class="fu">tidy</span>(<span class="fu">anova</span>(tum,sadece_kesisim))</span></code></pre></div>
<div class="kable-table">
<table>
<colgroup>
<col width="42%" />
<col width="16%" />
<col width="5%" />
<col width="4%" />
<col width="8%" />
<col width="13%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">df.residual</th>
<th align="right">rss</th>
<th align="right">df</th>
<th align="right">sumsq</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Performans ~ Motivasyon + Kaygi</td>
<td align="right">12</td>
<td align="right">160</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="left">Performans ~ Motivasyon</td>
<td align="right">13</td>
<td align="right">275</td>
<td align="right">-1</td>
<td align="right">-115</td>
<td align="right">8.62</td>
<td align="right">0.012</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="aşamalı-regresyon-3" class="section level2" number="4.51">
<h2><span class="header-section-number">4.51</span> Aşamalı regresyon</h2>
<ul>
<li><p>Modelde tek bir yordayıcı (motivasyon) varken, korelasyon <strong>0.824</strong>’tür ve sıfır hipotezi doğruysa bu kadar yüksek bir korelasyon elde etme olasılığı p &lt; 0.001.
Bu olasılık 0.05’ten küçük olduğundan, korelasyonun anlamlı olarak sıfırdan
büyük olduğu söylenebilir.</p></li>
<li><p>Modele motivasyon değişkeninin yanı sıra kaygi değişkeni de yordayıcı olarak
eklendiğinde, çoklu korelasyon <strong>0.902</strong>’dir ve sıfır hipotezi doğruysa bu kadar yüksek bir korelasyon elde etme olasılığı p &lt; 0.001. Bu olasılık 0.05’ten küçük olduğundan, çoklu korelasyonun anlamlı olarak sıfırdan büyük olduğu söylenebilir.</p></li>
</ul>
</div>
<div id="aşamalı-regresyon-4" class="section level2" number="4.52">
<h2><span class="header-section-number">4.52</span> Aşamalı regresyon</h2>
<ul>
<li><p>Birinci modelde motivasyon tek yordayıcıdır. Bu modelde motivasyona ilişkin
standartlaştırılmamış eğim katsayısı <strong>0.644</strong> olarak kestirilmiş olup kestirimin standart hatası <strong>0.123</strong>’tür. Bu katsayı p ˂ .05’te anlamlıdır. Standartlaştırılmış eğim katsayısı 0.824 olarak kestirilmiştir ve bu değer motivasyon ile performansarasındaki korelasyondur.</p></li>
<li><p>İkinci modelde <strong>motivasyon ve kaygı</strong> yordayıcılardır. Bu modelde motivasyona ilişkin standartlaştırılmamış eğim katsayısı <strong>0.686</strong> olarak kestirilmiş olup kestirimin standart hatası <strong>0.098</strong>’dir.</p></li>
</ul>
</div>
<div id="aşamalı-regresyon-5" class="section level2" number="4.53">
<h2><span class="header-section-number">4.53</span> Aşamalı regresyon</h2>
<ul>
<li><p>Öğrencilerin kaygı düzeyi kontrol altına alındığında,
artan motivasyon düzeyi daha yüksek performans puanları ile ilişkilidir. Bu katsayı p ˂ .05’te anlamlıdır. Standartlaştırılmış eğim katsayısı <strong>0.879</strong> olarak kestirilmiştir. Kaygıya ilişkin standartlaştırılmamış eğim katsayısı <strong>-0.607</strong> olarak kestirilmiş olup kestirimin standart hatası <strong>0.207</strong>’dir. Öğrencilerin motivasyon düzeyi kontrol altına alındığında, artan kaygı düzeyi daha düşük performans puanları ile ilişkilidir.</p></li>
<li><p>Kaygının modele eklenmesi korelasyonu çok fazla artırmasa da istatistiksel olarak anlamlı bir yordayıcıdır. Standartlaştırılmış eğim katsayısı -0.370 olarak kestirilmiştir.</p></li>
</ul>
</div>
<div id="etkili-gözlemlerin-belirlenmesi" class="section level2" number="4.54">
<h2><span class="header-section-number">4.54</span> Etkili Gözlemlerin Belirlenmesi</h2>
<ul>
<li><p>Etkili gözlemler (influential observations) regresyon sonuçları
üzerinde <strong>orantısız etkisi</strong> olan bütün gözlemleri içerir.</p></li>
<li><p>Bu <strong>aşırı değerler regresyon doğrusunu kendilerine doğru çekerek</strong> modelin
katsayıları üzerinde anlamlı etkileri olan değerlerdir.</p></li>
<li><p>Bu gözlemlerin belirlenmesinde kullanılan bazı istatistikler şunlardır:</p></li>
<li><p><strong>Distance (Uzaklık)</strong></p></li>
<li><p><strong>Leverage (hi)</strong></p></li>
<li><p><strong>Influence (Etki)</strong></p></li>
<li><p><strong>Cook’s D</strong></p></li>
</ul>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-1" class="section level2" number="4.55">
<h2><span class="header-section-number">4.55</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p><strong>Distance (Uzaklık):</strong></p>
<ul>
<li><p><strong>Bağımlı değişkenlerdeki potansiyel uç değerlerin</strong>
belirlenmesinde kullanışlı bir istatistiktir.</p></li>
<li><p><strong>Uzaklık için en yaygın ölçüm artıktır</strong>.</p></li>
<li><p>Artık herhangi <strong>bir nokta ve regresyon eğrisi arasındaki dikey uzaklığı</strong> ölçer. Bu noktalar <strong>rastgele hatayı temsil edebilir</strong>, Veri yanlış kodlanmış olabilir veya veri setine ait olmayan olağan dışı durumları yansıtabilir.</p></li>
</ul>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-2" class="section level2" number="4.56">
<h2><span class="header-section-number">4.56</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p><strong>Leverage (hi):</strong></p>
<ul>
<li><p><strong>Bağımsız değişkenlerdeki potansiyel uç değerlerin belirlenmesinde </strong>
kullanışlı bir istatistiktir.</p></li>
<li><p>Levarage bir gözlemin bir bağımsız değişkene, <span class="math inline">\(X_j\)</span>, göre <strong>olağan dışı olma derecesini</strong> ölçer.</p></li>
<li><p>Leverage için olası değerler, N gözlemlerin sayısı olmak üzere, <strong>1/N</strong> ile <strong>1.0</strong> arasında değişir.</p></li>
<li><p>Ortalama leverage puanı, <strong>p</strong> bağımsız değişken sayısı ve <strong>N</strong> gözlem sayısı olmak üzere, <strong>(p +1)/N</strong> eşitliği ile hesaplanabilir.</p></li>
<li><p><strong>Yüksek leverage değerine</strong> sahip gözlemler ortalama değerden 2 veya 3 kat daha yüksek leverage puanlarına sahip olacaktır.</p></li>
</ul>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-3" class="section level2" number="4.57">
<h2><span class="header-section-number">4.57</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p><strong>Influence (Etki):</strong></p>
<ul>
<li><p>Etkili bir gözlem <strong>uzaklık ve/veya leverage için yüksek değere</strong>
sahip olan ve <strong>modelin kesişim ve eğim katsayılarını anlamlı</strong> olarak etkileyen bir
gözlemdir.</p></li>
<li><p>Bu gözlemin varlığı veya yokluğu regresyon yüzeyinin yerini önemli
ölçüde değiştirecektir.</p></li>
<li><p>Uzaklık ve/veya leverage için yüksek değere sahip gözlemlerin regresyon
üzerinde önemli bir etkisi olmayabilir. Bir gözlemin etkide yüksek olması için
<strong>hem uzaklık hem de leverage için yüksek değerlere</strong> sahip olması gerekir.</p></li>
</ul>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-4" class="section level2" number="4.58">
<h2><span class="header-section-number">4.58</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p><strong>Cook’s D</strong></p>
<ul>
<li><p>Etkinin en yaygın ölçümü <strong>Cook’s D</strong> olarak bilinir.</p></li>
<li><p>Cook’s D <strong>i</strong> gözlemi veriden çıkarılıp analiz yeniden gerçekleştirilirse, <span class="math inline">\(b_j\)</span> katsayısındaki değişikliğin karesinin toplamının bir fonksiyonudur.</p></li>
<li><p>Her gözlem için hesaplanabilir. Her gözlem için bu değer, <strong>N</strong> gözlemlerin sayısı olmak üzere <strong>4/N</strong> ile karşılaştırılabilir. <strong>4/N</strong> üzerindeki değerler problem olabilecek gözlemlere işaret eder.</p></li>
<li><p><strong>Cook’s D</strong> etkinin genel bir ölçümü olarak düşünülebilir. Gözlemin
eklenmesiyle her katsayının nasıl değiştiğini ölçen daha spesifik bir
ölçüm ele alınabilir. Bu ölçüm <strong>DFBETA</strong> olarak adlandırılır ve her
gözlem için hesaplanabilir. (kritik değer <span class="math inline">\(2/\sqrt{n}\)</span></p></li>
</ul>
<p><strong>Cook’s D</strong></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="çoklu-regresyon.html#cb64-1" tabindex="-1"></a><span class="fu">library</span>(olsrr)</span>
<span id="cb64-2"><a href="çoklu-regresyon.html#cb64-2" tabindex="-1"></a><span class="fu">ols_plot_cooksd_bar</span>(model)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-51-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p><strong>DFBETA</strong></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="çoklu-regresyon.html#cb65-1" tabindex="-1"></a><span class="fu">ols_plot_dfbetas</span>(model)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-52-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="çoklu-regresyon.html#cb66-1" tabindex="-1"></a><span class="fu">ols_plot_dffits</span>(model)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-53-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="çoklu-regresyon.html#cb67-1" tabindex="-1"></a><span class="fu">ols_plot_resid_lev</span>(model)</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-54-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-5" class="section level2" number="4.59">
<h2><span class="header-section-number">4.59</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p><img src="images/CR_4.PNG" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-6" class="section level2" number="4.60">
<h2><span class="header-section-number">4.60</span> Etkili Gözlemlerin Belirlenmesi</h2>
<ul>
<li><p>Regresyon analizinin sonuçları ve sonuçların genellenebilirliği
<strong>birkaç gözlemle değişebilir.</strong> Dolayısıyla bu gözlemlerin etkilerinin
değerlendirilmesi için belirlenmesi gerekir.</p></li>
<li><p>Etkili gözlem, gözlemlerdeki veya veri girişindeki bir hatadan
kaynaklanabilir. Bu durumda birey analizden çıkarılabilir veya veri
düzeltilebilir.</p></li>
<li><p>Sıradışı bir durumla açıklanabilen, ender karşılaşılan geçerli bir
gözlem analizden çıkarılabilir. Halbuki olası bir açıklaması olmayan,
ender karşılaşılan bir gözlemi bir neden olmadan çıkarmak
problemlidir ancak gözlemin analize dahil edilmesi de
savunulamayabilir. <strong>Bu durumda analizlerin gözlem dahil edilerek ve
dahil edilmeyerek tekrarlanması önerilir.</strong></p></li>
</ul>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-7" class="section level2" number="4.61">
<h2><span class="header-section-number">4.61</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p>Cook's D için kesme noktası 4/15= 0.267, 8. ve 11. gözlemler bu sınırı asıyor</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="çoklu-regresyon.html#cb68-1" tabindex="-1"></a><span class="fu">influence.measures</span>(model, <span class="at">infl =</span> <span class="fu">influence</span>(model))</span></code></pre></div>
<pre><code>## Influence measures of
##   lm(formula = Performans ~ Motivasyon + Kaygi, data = performans) :
## 
##      dfb.1_  dfb.Mtvs dfb.Kayg   dffit cov.r   cook.d    hat inf
## 1   0.95795 -0.960377 -0.16108  1.1422 0.896 0.372039 0.3012    
## 2  -0.25252  0.415588 -0.15745 -0.4984 1.422 0.084595 0.2501    
## 3   0.14949 -0.263213  0.00861 -0.3676 1.209 0.045656 0.1388    
## 4  -0.04850  0.110703 -0.01220  0.1872 1.332 0.012398 0.1026    
## 5  -0.05212 -0.059328  0.11625 -0.1413 1.796 0.007232 0.2869   *
## 6  -0.50564 -0.103904  0.68481 -0.8203 0.924 0.201071 0.2200    
## 7  -0.09262  0.115511 -0.02600 -0.1686 1.409 0.010150 0.1264    
## 8   1.12071 -0.626060 -0.99660 -1.3623 1.570 0.574244 0.4905   *
## 9   0.07075 -0.094818  0.07387  0.3019 1.061 0.030173 0.0774    
## 10 -0.00254  0.000079 -0.00142 -0.0191 1.390 0.000132 0.0670    
## 11 -0.76153  1.357765 -0.15466  1.6459 0.228 0.510106 0.2092   *
## 12 -0.07535  0.006834  0.07308 -0.1166 1.424 0.004897 0.1142    
## 13 -0.06170 -0.043739  0.14852  0.1670 1.965 0.010089 0.3487   *
## 14 -0.00051 -0.015642  0.01231 -0.0267 1.490 0.000260 0.1297    
## 15 -0.07231  0.081208 -0.00672 -0.1135 1.472 0.004648 0.1373</code></pre>
</div>
<div id="etkili-gözlemlerin-belirlenmesi-8" class="section level2" number="4.62">
<h2><span class="header-section-number">4.62</span> Etkili Gözlemlerin Belirlenmesi</h2>
<p>DFBETA için kesme noktası ise 2/(15^1/2) = 0.516
hat degerleri ise levarge a karşılık geliyor</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="çoklu-regresyon.html#cb70-1" tabindex="-1"></a><span class="fu">influence.measures</span>(model, <span class="at">infl =</span> <span class="fu">influence</span>(model))</span></code></pre></div>
<pre><code>## Influence measures of
##   lm(formula = Performans ~ Motivasyon + Kaygi, data = performans) :
## 
##      dfb.1_  dfb.Mtvs dfb.Kayg   dffit cov.r   cook.d    hat inf
## 1   0.95795 -0.960377 -0.16108  1.1422 0.896 0.372039 0.3012    
## 2  -0.25252  0.415588 -0.15745 -0.4984 1.422 0.084595 0.2501    
## 3   0.14949 -0.263213  0.00861 -0.3676 1.209 0.045656 0.1388    
## 4  -0.04850  0.110703 -0.01220  0.1872 1.332 0.012398 0.1026    
## 5  -0.05212 -0.059328  0.11625 -0.1413 1.796 0.007232 0.2869   *
## 6  -0.50564 -0.103904  0.68481 -0.8203 0.924 0.201071 0.2200    
## 7  -0.09262  0.115511 -0.02600 -0.1686 1.409 0.010150 0.1264    
## 8   1.12071 -0.626060 -0.99660 -1.3623 1.570 0.574244 0.4905   *
## 9   0.07075 -0.094818  0.07387  0.3019 1.061 0.030173 0.0774    
## 10 -0.00254  0.000079 -0.00142 -0.0191 1.390 0.000132 0.0670    
## 11 -0.76153  1.357765 -0.15466  1.6459 0.228 0.510106 0.2092   *
## 12 -0.07535  0.006834  0.07308 -0.1166 1.424 0.004897 0.1142    
## 13 -0.06170 -0.043739  0.14852  0.1670 1.965 0.010089 0.3487   *
## 14 -0.00051 -0.015642  0.01231 -0.0267 1.490 0.000260 0.1297    
## 15 -0.07231  0.081208 -0.00672 -0.1135 1.472 0.004648 0.1373</code></pre>
</div>
<div id="kategorik-bağımsız-bir-değişken-ile-çoklu-regresyon" class="section level2" number="4.63">
<h2><span class="header-section-number">4.63</span> Kategorik Bağımsız bir Değişken ile Çoklu Regresyon</h2>
<ul>
<li><p>Regresyon modellerinde bagimsiz bir degisken surekli
veya kategorik olabilir.</p></li>
<li><p>Bir regresyon analizine kategorik bir degiskeni dahil
ederken, regresyon modelinin degiskenin duzeylerindeki
farkliliklari dogru olarak kestirmesini saglamak icin,
degiskenin duzeylerinin <strong>yeniden kodlanmasi </strong>
gerekmektedir.</p></li>
<li><p>Kategorik degiskenleri kodlamanın en basit yöntemi <strong>dummy
(yapay)</strong> kodlamadir.</p></li>
<li><p>Dummy kodlama ile kategorik degiskenin
duzeylerine sayısal degerler atanarak dummy degisken(ler)
olusturulur.</p></li>
</ul>
<p>-Dummy degisken kategorik bir degiskenin duzeylerinin sayisal
gosterimidir.</p>
</div>
<div id="kategorik-bağımsız-bir-değişken-ile-çoklu-regresyon-1" class="section level2" number="4.64">
<h2><span class="header-section-number">4.64</span> Kategorik Bağımsız bir Değişken ile Çoklu Regresyon</h2>
<ul>
<li>Bir bireyin <strong>k</strong> tane duzeye sahip kategorik bagimsiz bir degiskenin
belli bir duzeyine iliskin uyeligini temsil eden <strong>k-1</strong> tane dummy
degisken olusturulur.</li>
<li>Eger bir birey kategorik degiskenin birinci duzeyindeyse birinci dummy
degiskene 1 degeri verilir, birey degiskenin baska bir duzeyindeyse
birinci dummy degiskene 0 degeri verilir.</li>
<li>Eger ayni birey kategorik degiskenin ikinci duzeyindeyse ikinci dummy
degiskene 1 degeri verilir, birey degiskenin baska bir duzeyindeyse ikinci
dummy degiskene 0 degeri verilir.</li>
<li>Eger ayni birey kategorik degiskenin (k-1). duzeyindeyse (k-1). dummy
degiskene 1 degeri verilir, birey degiskenin baska bir duzeyindeyse (k-1). dummy degiskene 0 degeri verilir.</li>
<li>Boyle bir kodlama ile olusturulan her bir dummy degisken iki duzeye
sahiptir: 1 ve 0</li>
</ul>
</div>
<div id="kategorik-bağımsız-bir-değişken-ile-çoklu-regresyon-2" class="section level2" number="4.65">
<h2><span class="header-section-number">4.65</span> Kategorik Bağımsız bir Değişken ile Çoklu Regresyon</h2>
<ul>
<li><p>Bir kategorik degisken icin olusturulan dummy degiskenlerle
gerceklestirilen bir regresyon analizinde regresyon katsayilarinin
yorumlanmasi asagidaki gibidir:</p></li>
<li><p><strong>Birinci dummy degiskene iliskin katsayi</strong>, diger butun degiskenler kontrol
altina alindiginda, <strong>kategorik degiskenin birinci duzeyi ve kategorik degiskenin son duzeyi</strong> arasindaki bagimli degiskenin yordanan degerinin
farkidir.</p></li>
<li><p><strong>Ikinci dummy degiskene iliskin katsayi</strong>, diger butun degiskenler kontrol
altina alindiginda, <strong>kategorik degiskenin ikinci duzeyi</strong> ve <strong>kategorik degiskenin son duzeyi</strong> arasindaki bagimli degiskenin yordanan degerinin
farkidir.</p></li>
<li><p><strong>j. dummy degiskene iliskin katsayi</strong>, diger butun degiskenler kontrol altina alindiginda, <strong>kategorik degiskenin j. duzeyi</strong> ve <strong>kategorik degiskenin son duzeyi</strong> arasindaki bagimli degiskenin yordanan degerinin farkidir.</p></li>
</ul>
</div>
<div id="dummy-değişkenlerin-oluşturulması-örnek-performansın-yordanması" class="section level2" number="4.66">
<h2><span class="header-section-number">4.66</span> Dummy Değişkenlerin Oluşturulması Örnek: Performansın Yordanması</h2>
<ul>
<li>Uc duzeyi (evil, bekar ve diger) bulunan medeni durum degiskeni
icin biri “Evli”, digeri “Bekar” olarak adlandirilan iki dummy degisken
(ornegin, D1 ve D2) olusturulabilir.</li>
</ul>
<div class="line-block">Medeni Durum | D1 (Evli) | D2 (Bekar) | D3 (Diger)|</div>
<p>|::|::|::|::|::|::|
|Evli |1 |0 |0|
|Bekar|0 |1 |0|
|Diger|0 |0 |1|
- Referans Grup: Diger
- Kategorik degiskenin <strong>uc duzeyini</strong> gostermek icin uc gosterge degiskenine ihtiyac yoktur. Degiskenin duzeyleri sadece <strong>iki gostergeyle tanimlanmistir.</strong>
- D1 degiskeni icin 0 degerine, D2 degiskeni icin 0 degerine sahip bir birey diger kategorisine aittir.</p>
</div>
<div id="dummy-değişkenlerin-oluşturulması-örnek-performansın-yordanması-1" class="section level2" number="4.67">
<h2><span class="header-section-number">4.67</span> Dummy Değişkenlerin Oluşturulması Örnek: Performansın Yordanması</h2>
<ul>
<li><p>D1 ve D2 bagimsiz degiskenleri ile gerceklestirilen bir regresyon
analizinde kestirilen <span class="math inline">\(b_1\)</span> egim katsayisi evliler ve digerleri arasındaki
yordanan matematik performansi farkini, <span class="math inline">\(b_2\)</span> egim katsayisi ise
bekarlar ve digerleri arasındaki yordanan matematik performansi
farkini belirtir.</p></li>
<li><p>Evliler ve bekarlar arasindaki yordanan matematik performansi farki,
birinci ve ikinci medeni durum katsayilari arasindaki farktir: <span class="math inline">\(b_1 - b_2\)</span></p></li>
</ul>
</div>
<div id="dummy-değişkenlerin-oluşturulması-örnek-performansın-yordanması-2" class="section level2" number="4.68">
<h2><span class="header-section-number">4.68</span> Dummy Değişkenlerin Oluşturulması Örnek: Performansın Yordanması</h2>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="çoklu-regresyon.html#cb72-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb72-2"><a href="çoklu-regresyon.html#cb72-2" tabindex="-1"></a>Performansd1 <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;import/Performansd1.sav&quot;</span>)</span>
<span id="cb72-3"><a href="çoklu-regresyon.html#cb72-3" tabindex="-1"></a><span class="fu">summary</span>(Performansd1)</span></code></pre></div>
<pre><code>##    Performans     Motivasyon       Kaygi          Guven         Medeni         
##  Min.   : 4.1   Min.   :22.0   Min.   :10.7   Min.   : 8.8   Length:15         
##  1st Qu.:11.9   1st Qu.:34.0   1st Qu.:15.5   1st Qu.:17.1   Class :character  
##  Median :18.0   Median :40.0   Median :18.3   Median :22.0   Mode  :character  
##  Mean   :18.2   Mean   :39.9   Mean   :18.1   Mean   :21.6                     
##  3rd Qu.:22.9   3rd Qu.:47.0   3rd Qu.:18.8   3rd Qu.:25.6                     
##  Max.   :35.5   Max.   :55.0   Max.   :28.2   Max.   :38.7</code></pre>
</div>
<div id="dummy-değişkenlerin-oluşturulması-örnek-performansın-yordanması-3" class="section level2" number="4.69">
<h2><span class="header-section-number">4.69</span> Dummy Değişkenlerin Oluşturulması Örnek: Performansın Yordanması</h2>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="çoklu-regresyon.html#cb74-1" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb74-2"><a href="çoklu-regresyon.html#cb74-2" tabindex="-1"></a><span class="co"># Performansd1$D1 &lt;- ifelse(Performansd1$Medeni  == &quot;Evli&quot;, 1, 0)</span></span>
<span id="cb74-3"><a href="çoklu-regresyon.html#cb74-3" tabindex="-1"></a><span class="co"># Performansd1$D2&lt;- ifelse(Performansd1$Medeni  == &quot;Bekar&quot;, 1, 0)</span></span>
<span id="cb74-4"><a href="çoklu-regresyon.html#cb74-4" tabindex="-1"></a>dataf <span class="ot">&lt;-</span> <span class="fu">dummy_cols</span>(Performansd1, <span class="at">select_columns =</span> <span class="st">&#39;Medeni&#39;</span>)</span>
<span id="cb74-5"><a href="çoklu-regresyon.html#cb74-5" tabindex="-1"></a><span class="fu">summary</span>(dataf)</span></code></pre></div>
<pre><code>##    Performans     Motivasyon       Kaygi          Guven         Medeni         
##  Min.   : 4.1   Min.   :22.0   Min.   :10.7   Min.   : 8.8   Length:15         
##  1st Qu.:11.9   1st Qu.:34.0   1st Qu.:15.5   1st Qu.:17.1   Class :character  
##  Median :18.0   Median :40.0   Median :18.3   Median :22.0   Mode  :character  
##  Mean   :18.2   Mean   :39.9   Mean   :18.1   Mean   :21.6                     
##  3rd Qu.:22.9   3rd Qu.:47.0   3rd Qu.:18.8   3rd Qu.:25.6                     
##  Max.   :35.5   Max.   :55.0   Max.   :28.2   Max.   :38.7                     
##     Medeni_1        Medeni_2        Medeni_3    
##  Min.   :0.000   Min.   :0.000   Min.   :0.000  
##  1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000  
##  Median :0.000   Median :0.000   Median :0.000  
##  Mean   :0.267   Mean   :0.467   Mean   :0.267  
##  3rd Qu.:0.500   3rd Qu.:1.000   3rd Qu.:0.500  
##  Max.   :1.000   Max.   :1.000   Max.   :1.000</code></pre>
</div>
<div id="dummy-değişkenlerin-oluşturulması-örnek-performansın-yordanması-4" class="section level2" number="4.70">
<h2><span class="header-section-number">4.70</span> Dummy Değişkenlerin Oluşturulması Örnek: Performansın Yordanması</h2>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="çoklu-regresyon.html#cb76-1" tabindex="-1"></a>model_dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(Performans <span class="sc">~</span> Medeni_1 <span class="sc">+</span> Medeni_2 , </span>
<span id="cb76-2"><a href="çoklu-regresyon.html#cb76-2" tabindex="-1"></a>                  <span class="at">data=</span>dataf)</span>
<span id="cb76-3"><a href="çoklu-regresyon.html#cb76-3" tabindex="-1"></a>model_dummy</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Performans ~ Medeni_1 + Medeni_2, data = dataf)
## 
## Coefficients:
## (Intercept)     Medeni_1     Medeni_2  
##      19.644       -6.623        0.639</code></pre>
<ul>
<li>Kesişim katsayısı <span class="math inline">\(b_0\)</span> 19.644 matematik değerine eşittir. Bu değer, medeni
durumu diger olan ogrencilerin yordanan performans puanıdır.</li>
<li>Evli için standartlaştırılmamış eğim katsayısı <span class="math inline">\(b_1\)</span> -6.623 değerine eşittir. Bu değer, <strong>evliler ve digerleri arasindaki</strong> yordanan matematik performans
puanları farkinin -6.623 birim olduğunu önerir.</li>
<li><span class="math inline">\(19.644 – 6.623 = 13.021\)</span> medeni durumu evli olan ogrencilerin yordanan matematik performans puanidir.</li>
</ul>
</div>
<div id="dummy-değişkenlerin-oluşturulması-örnek-performansın-yordanması-5" class="section level2" number="4.71">
<h2><span class="header-section-number">4.71</span> Dummy Değişkenlerin Oluşturulması Örnek: Performansın Yordanması</h2>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="çoklu-regresyon.html#cb78-1" tabindex="-1"></a>model_dummy</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Performans ~ Medeni_1 + Medeni_2, data = dataf)
## 
## Coefficients:
## (Intercept)     Medeni_1     Medeni_2  
##      19.644       -6.623        0.639</code></pre>
<ul>
<li><p>benzer şekilde, Bekar için standartlaştırılmamış eğim katsayısı <span class="math inline">\(b_21\)</span> 0.639
değerine eşittir. Bu değer, <strong>bekarlar ve digerleri arasindaki</strong> yordanan
matematik performans puanları farkinin 0.639 birim olduğunu önerir.</p></li>
<li><p><span class="math inline">\(19.644 + 0.639 = 20.283\)</span> medeni durumu bekar olan ogrencilerin yordanan matematik
performans puanidir.</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi" class="section level2" number="4.72">
<h2><span class="header-section-number">4.72</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Eger bir coklu regresyon modelinde bir bağımsız degisken ile
bagimli degisken arasindaki iliskinin buyuklugu diger bir bağımsız
degiskenin duzeyine gore degisirse, etkilesim gozlenir.</p></li>
<li><p>Etkilesim etkisi, düzenleyici (moderator) etki olarak da bilinmektedir.</p></li>
</ul>
<!--   - Örneğin, klinik calismalarla test edilen kolesterol dusurucu bir ilacin dozunun -->
<!-- $X_1$ ve ilaci kullanan bireylerin cinsiyetinin $X_2$  kolesterol dusurme miktari $Y$  -->
<!-- uzerindeki etkisini gosteren grafikler asagidaki gibi olabilir -->
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-1" class="section level2" number="4.73">
<h2><span class="header-section-number">4.73</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Etkileşim terimi <span class="math inline">\(X_1\)</span> değişkeninin değerlerinin aracı <span class="math inline">\(X_2\)</span> değişkeninin
değerleriyle çarpılmasıyla oluşan bileşik bir değişkendir.</p></li>
<li><p>Regresyon eşitliği aşağıdaki gibidir:</p></li>
</ul>
<p><span class="math display">\[Y= a + b_1x_{1i} +  b_2x_{2i} + b_3x_{1i}x_{2i}\]</span></p>
<ul>
<li>Burada, <span class="math inline">\(b_3\)</span> katsayısı aracı etki olup <span class="math inline">\(X_2\)</span> değişkenin değeri değişirken <span class="math inline">\(X_1\)</span>
değişkeninin etkisindeki birim değişimi belirtir.</li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-2" class="section level2" number="4.74">
<h2><span class="header-section-number">4.74</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<p><span class="math display">\[Y= a + b_1x_{1i} +  b_2x_{2i} + b_3x_{1i}x_{2i}\]</span></p>
<ul>
<li><p><span class="math inline">\(b_1\)</span> katsayısı <span class="math inline">\(X_2\)</span> değişkenine ilişkin değer sıfırken <span class="math inline">\(X_1\)</span> değişkeninin etkisini,</p></li>
<li><p><span class="math inline">\(b_2\)</span> katsayısı <span class="math inline">\(X_1\)</span> değişkenine ilişkin değer sıfırken <span class="math inline">\(X_2\)</span> değişkeninin etkisini belirtir (Etkileşim etkisinin bulunmadığı modelde, <span class="math inline">\(b_1\)</span> katsayısı <span class="math inline">\(X_2\)</span> değişkeninin bütün düzeylerinde <span class="math inline">\(X_1\)</span> değişkeninin etkisini, <span class="math inline">\(b_2\)</span> katsayısı <span class="math inline">\(X_1\)</span> değişkeninin bütün düzeylerinde <span class="math inline">\(X_2\)</span> değişkeninin etkisini temsil eder).</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-3" class="section level2" number="4.75">
<h2><span class="header-section-number">4.75</span> ## Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Bağımsız değişkenin toplam etkisini belirlemek için değişkenin ayrı ve aracı etkisi bir araya getirilmelidir.</p></li>
<li><p><span class="math inline">\(X_1\)</span> değişkeninin <span class="math inline">\(X_2\)</span> değişkeninin herhangi bir değerindeki toplam etkisi aşağıdaki eşitlikle hesaplanabilir:</p></li>
</ul>
<p><span class="math display">\[ b_{toplam} = b_1+b_3X_2\]</span></p>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-4" class="section level2" number="4.76">
<h2><span class="header-section-number">4.76</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<p>-Sunumdaki ornek Wagner, Compas ve Howell (1988)’in calismasindan
gelmektedir.</p>
<ul>
<li><p>Wagner ve digerleri calismalarinda <strong>daha fazla strese maruz kalan bireylerin psikolojik belirtileri daha yuksek duzeyde gosterecegini</strong>
onermistir.</p></li>
<li><p>Ancak bir birey stresiyle basa cikmasina yardimci olacak yuksek
duzeyde <strong>sosyal destege sahipse</strong>, belirtilerin stres arttikca daha yavas
artmasinin beklenecegini, daha az sosyal destege sahip bireyler icinse,
semptomlarin stres arttikca daha hizli artmasinin beklenecegini belirttiler.</p></li>
<li><p>Wagner, B. M., Compas, B. E., &amp; Howell, D. C. (1988). Daily and major life events: A test of an integrative model of psychosocial stress. American Journal of Community Psychology, 16 (2), 189-205.</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-5" class="section level2" number="4.77">
<h2><span class="header-section-number">4.77</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<p>“Hassles.sav” SPSS veri dosyasi bir ID degiskeni ve ID degiskeni
disinda dort degisken ve 56 universite birinci sinif ogrencisini
icermektedir. Veri setine asagidaki web adresinden ulasilabilir:</p>
<ul>
<li><a href="https://www.uvm.edu/~dhowell/methods8/DataFiles/DataSets.html" class="uri">https://www.uvm.edu/~dhowell/methods8/DataFiles/DataSets.html</a></li>
</ul>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="çoklu-regresyon.html#cb80-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb80-2"><a href="çoklu-regresyon.html#cb80-2" tabindex="-1"></a>zorluklar <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;import/Hassles.sav&quot;</span>)[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>)]</span>
<span id="cb80-3"><a href="çoklu-regresyon.html#cb80-3" tabindex="-1"></a><span class="fu">colnames</span>(zorluklar)  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;id&quot;</span>,<span class="st">&quot;sorun&quot;</span>,<span class="st">&quot;destek&quot;</span>,<span class="st">&quot;belirtiler&quot;</span>)</span></code></pre></div>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-6" class="section level2" number="4.78">
<h2><span class="header-section-number">4.78</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<p>İlk olarak değişkenler arasındaki ilişkilere bakılır.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="çoklu-regresyon.html#cb81-1" tabindex="-1"></a><span class="fu">ggpairs</span>(zorluklar[,<span class="sc">-</span><span class="dv">1</span>])</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-63-1.png" width="40%" style="display: block; margin: auto;" /></p>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-7" class="section level2" number="4.79">
<h2><span class="header-section-number">4.79</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Destek, sorun veya belirtiler ile iliskili olmamasina ragmen, beklendigi
gibi, Zorluklar ve Belirtiler arasinda istatistiksel olarak bir iliski vardir (r = 0,
577).</p></li>
<li><p>Ancak bu bulgular sorun ve belirtiler arasindaki iliskinin destek
duzeyine bagli olup olmadigi sorusuna cevap vermemektedir</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-8" class="section level2" number="4.80">
<h2><span class="header-section-number">4.80</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Sorun ve Destek etkilesimini test etmek icin sorun degerleri ile
destek degerlerinin carpimiyla yeni bir degisken olusturulur.</p></li>
<li><p>Ancak bu iki degiskene iliskin degerlerin carpilmasiyla olusan degiskenin
analize dahil edilmesinde iki problem ortaya cikacaktir.</p>
<ul>
<li>Sorun veya Destek degiskenlerinden biri veya ikisi, carpimlariyla olusan
degisken ile yuksek duzeyde korelasyona sahip olacaktir ki bu da veride <strong>coklu baglanti problemine</strong> neden olacaktir.</li>
</ul></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-9" class="section level2" number="4.81">
<h2><span class="header-section-number">4.81</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Regresyon analizinde Sorun veya Destek degiskeninin herhangi bir etkisi
diger degiskenin degerinin 0 oldugu durumda degerlendirilecektir.</p></li>
<li><p>Diger bir ifadeyle, Sorun uzerindeki test hic sosyal destegi olmayan bir katilimci icin Sorunların belirtilerle iliskili olup olmadigi testi olacaktir.</p></li>
<li><p>Benzer sekilde, destek uzerindeki test hic Sorunları olmayan katilimcilar icin degerlendirilecektir.</p></li>
<li><p>Hem <strong>coklu baglanti problemi</strong>, hem de <strong>ana etkilerden birinin digerana etkinin uc degerinde degerlendirilmesi</strong> problemi istenmeyen
durumlardir.</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-10" class="section level2" number="4.82">
<h2><span class="header-section-number">4.82</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Bahsedilen problemlerle basa cikmak icin <strong>sorun degiskeni ve destek
degiskeni</strong> merkezlenebilir.</p></li>
<li><p>Bunun icin her bir degiskene iliskin bireysel gozlemlerden ilgili
degiskenin ortalamasi cikarilarak sapma puanlari hesaplanacaktir.</p></li>
</ul>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="çoklu-regresyon.html#cb82-1" tabindex="-1"></a>zorluklar<span class="sc">$</span>csorun <span class="ot">&lt;-</span> zorluklar<span class="sc">$</span>sorun <span class="sc">-</span><span class="fu">mean</span>(zorluklar<span class="sc">$</span>sorun)</span>
<span id="cb82-2"><a href="çoklu-regresyon.html#cb82-2" tabindex="-1"></a>zorluklar<span class="sc">$</span>cdestek <span class="ot">&lt;-</span> zorluklar<span class="sc">$</span>destek <span class="sc">-</span><span class="fu">mean</span>(zorluklar<span class="sc">$</span>destek)</span>
<span id="cb82-3"><a href="çoklu-regresyon.html#cb82-3" tabindex="-1"></a>zorluklar<span class="sc">$</span>cross  <span class="ot">&lt;-</span> zorluklar<span class="sc">$</span>sorun<span class="sc">*</span>zorluklar<span class="sc">$</span>destek</span>
<span id="cb82-4"><a href="çoklu-regresyon.html#cb82-4" tabindex="-1"></a>zorluklar<span class="sc">$</span>cross_m  <span class="ot">&lt;-</span> zorluklar<span class="sc">$</span>csorun<span class="sc">*</span>zorluklar<span class="sc">$</span>cdestek</span></code></pre></div>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-11" class="section level2" number="4.83">
<h2><span class="header-section-number">4.83</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Degiskenler merkezlendikten sonra merkezlenen sorun
degiskeni icin 0 degeri sorun degiskeninin ortalama duzeyindeki
katilimcilari temsil ederken, merkezlenen destek degiskeni icin 0 degeri
destek degiskeninin ortalama duzeyindeki katilimcilari
temsil eder.</p></li>
<li><p>Boylece ana etkiler diger degiskenin uygun duzeyinde degerlendirilir.</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-12" class="section level2" number="4.84">
<h2><span class="header-section-number">4.84</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Degiskenlerin merkezlenmesiyle sorun ve destek degiskenleri
arasindaki <strong>coklu baglanti</strong> da onemli olcude dusecektir.</p></li>
<li><p>Merkezlenen sorun, Merkezlenen destek, Merkezlenen sorun
degiskeninin degerleri ile Merkezlenen Destek degiskeninin degerlerinin
carpilmasiyla elde edilen etkilesim terimi ve Belirtiler arasindaki
korelasyon matrisi incelenir.</p></li>
</ul>
<p>.pull-left[</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="çoklu-regresyon.html#cb83-1" tabindex="-1"></a><span class="fu">ggpairs</span>(zorluklar[,<span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>,<span class="dv">7</span>)])</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-65-1.png" width="70%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="çoklu-regresyon.html#cb84-1" tabindex="-1"></a><span class="fu">ggpairs</span>(zorluklar[,<span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">8</span>)])</span></code></pre></div>
<p><img src="03-CR_files/figure-html/unnamed-chunk-66-1.png" width="70%" style="display: block; margin: auto;" /></p>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-13" class="section level2" number="4.85">
<h2><span class="header-section-number">4.85</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li>Belirtilerin bagimli degişken, merkezlenen sorunların ve merkezlenen
Destegin bağımsız degisken olarak modellendigi regresyonda, iki
bağımsız degiskenin etkilesimini incelemek uzere etkilesim terimi de
regresyon modeline eklenir.</li>
</ul>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="çoklu-regresyon.html#cb85-1" tabindex="-1"></a>cross_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(belirtiler  <span class="sc">~</span> csorun  <span class="sc">+</span> cdestek <span class="sc">+</span> cross_m ,<span class="at">data=</span>zorluklar)</span>
<span id="cb85-2"><a href="çoklu-regresyon.html#cb85-2" tabindex="-1"></a><span class="fu">glance</span>(cross_model)</span>
<span id="cb85-3"><a href="çoklu-regresyon.html#cb85-3" tabindex="-1"></a><span class="fu">tidy</span>(cross_model)</span></code></pre></div>
<div class="kable-table">
<table>
<colgroup>
<col width="10%" />
<col width="15%" />
<col width="6%" />
<col width="10%" />
<col width="8%" />
<col width="3%" />
<col width="7%" />
<col width="4%" />
<col width="4%" />
<col width="9%" />
<col width="13%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.388</td>
<td align="right">0.353</td>
<td align="right">16.9</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">-236</td>
<td align="right">481</td>
<td align="right">492</td>
<td align="right">14840</td>
<td align="right">52</td>
<td align="right">56</td>
</tr>
</tbody>
</table>
</div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">89.585</td>
<td align="right">2.292</td>
<td align="right">39.094</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">csorun</td>
<td align="right">0.086</td>
<td align="right">0.019</td>
<td align="right">4.473</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">cdestek</td>
<td align="right">0.146</td>
<td align="right">0.305</td>
<td align="right">0.479</td>
<td align="right">0.634</td>
</tr>
<tr class="even">
<td align="left">cross_m</td>
<td align="right">-0.005</td>
<td align="right">0.002</td>
<td align="right">-2.144</td>
<td align="right">0.037</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><span class="math inline">\(R^2\)</span> degeri yaklasik 0.39 olup belirtilerdeki varyansin yaklasik
%39’unun dogrusal regresyon modeli tarafindan aciklandigi
anlamina gelmektedir.</li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-14" class="section level2" number="4.86">
<h2><span class="header-section-number">4.86</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="çoklu-regresyon.html#cb86-1" tabindex="-1"></a><span class="fu">tidy</span>(cross_model)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">89.585</td>
<td align="right">2.292</td>
<td align="right">39.094</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">csorun</td>
<td align="right">0.086</td>
<td align="right">0.019</td>
<td align="right">4.473</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">cdestek</td>
<td align="right">0.146</td>
<td align="right">0.305</td>
<td align="right">0.479</td>
<td align="right">0.634</td>
</tr>
<tr class="even">
<td align="left">cross_m</td>
<td align="right">-0.005</td>
<td align="right">0.002</td>
<td align="right">-2.144</td>
<td align="right">0.037</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><p>Hem merkezlenen sorun hem de etkileşim terimi istatistiksel olarak
anlamlıdır (sırasıyla p ˂ 0.001 ve p = 0.037). Ancak merkezlenen Destek
istatistiksel olarak anlamlı değildir (p = 0.634). Destek değişkeni
etkileşim teriminin hesaplanmasında yer aldığından, regresyon
modelinde kalabilir.</p></li>
<li><p>Etkilesim etkisinin anlamini yorumlamak icin degiskenler arasindaki
iliskilerin grafik ile gosterimi yardimci olabilir. En basit cozum sosyal
destegin sabit duzeyleri icin zorluklar ve psikolojik belirtiler
arasindaki iliskiye bakmaktir.</p></li>
</ul>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-15" class="section level2" number="4.87">
<h2><span class="header-section-number">4.87</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li>Merkezlenen sosyal destek değişkeninin değerileri -21 ile +19 arasında
değişmektedir. Bu değişken icin dusuk, orta ve yuksek degerleri temsil etmek
üzere sirasiyla -15, 0 ve +15 degerleri secilebilir.</li>
</ul>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="çoklu-regresyon.html#cb87-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb87-2"><a href="çoklu-regresyon.html#cb87-2" tabindex="-1"></a>zorluklar <span class="ot">&lt;-</span> zorluklar <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb87-3"><a href="çoklu-regresyon.html#cb87-3" tabindex="-1"></a>  <span class="at">cdestek_kat =</span> <span class="fu">case_when</span>(</span>
<span id="cb87-4"><a href="çoklu-regresyon.html#cb87-4" tabindex="-1"></a>  cdestek <span class="sc">&lt;=</span> <span class="sc">-</span><span class="dv">15</span> <span class="sc">~</span> <span class="st">&quot;dusuk&quot;</span>,</span>
<span id="cb87-5"><a href="çoklu-regresyon.html#cb87-5" tabindex="-1"></a>  cdestek <span class="sc">&gt;-</span><span class="dv">15</span> <span class="sc">&amp;</span>    cdestek <span class="sc">&lt;</span><span class="dv">15</span><span class="sc">~</span> <span class="st">&quot;orta&quot;</span>,</span>
<span id="cb87-6"><a href="çoklu-regresyon.html#cb87-6" tabindex="-1"></a>  cdestek <span class="sc">&gt;=</span><span class="dv">15</span> <span class="sc">~</span> <span class="st">&quot;yuksek&quot;</span>,</span>
<span id="cb87-7"><a href="çoklu-regresyon.html#cb87-7" tabindex="-1"></a>  )</span>
<span id="cb87-8"><a href="çoklu-regresyon.html#cb87-8" tabindex="-1"></a>)</span>
<span id="cb87-9"><a href="çoklu-regresyon.html#cb87-9" tabindex="-1"></a>zorluklar <span class="ot">&lt;-</span> zorluklar <span class="sc">%&gt;%</span>  <span class="fu">arrange</span>(csorun)</span></code></pre></div>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-16" class="section level2" number="4.88">
<h2><span class="header-section-number">4.88</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="çoklu-regresyon.html#cb88-1" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb88-2"><a href="çoklu-regresyon.html#cb88-2" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>zorluklar, <span class="fu">aes</span>(<span class="at">x=</span>sorun, <span class="at">y=</span>belirtiler))<span class="sc">+</span></span>
<span id="cb88-3"><a href="çoklu-regresyon.html#cb88-3" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color=</span>cdestek_kat))</span>
<span id="cb88-4"><a href="çoklu-regresyon.html#cb88-4" tabindex="-1"></a></span>
<span id="cb88-5"><a href="çoklu-regresyon.html#cb88-5" tabindex="-1"></a></span>
<span id="cb88-6"><a href="çoklu-regresyon.html#cb88-6" tabindex="-1"></a><span class="fu">ggplotly</span>(p)</span></code></pre></div>
<div class="plotly html-widget html-fill-item" id="htmlwidget-23b212d5e0b30a05f65a" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-23b212d5e0b30a05f65a">{"x":{"data":[{"x":[176,185],"y":[73,125],"text":["sorun: 176<br />belirtiler:  73<br />cdestek_kat: dusuk","sorun: 185<br />belirtiler: 125<br />cdestek_kat: dusuk"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(248,118,109,1)","dash":"solid"},"hoveron":"points","name":"dusuk","legendgroup":"dusuk","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[16,27,42,45,49,54,54,62,64,65,67,68,68,75,75,88,89,95,96,112,118,131,139,143,144,153,153,156,158,161,164,171,172,193,193,201,202,202,203,214,217,219,229,229,260,277,290,298,342,380,525,717],"y":[80,64,77,78,62,86,74,58,66,86,63,106,88,109,78,81,90,62,111,87,80,80,82,81,70,73,84,74,74,109,99,74,88,79,100,91,102,102,88,93,97,93,127,99,131,101,96,111,75,107,177,117],"text":["sorun:  16<br />belirtiler:  80<br />cdestek_kat: orta","sorun:  27<br />belirtiler:  64<br />cdestek_kat: orta","sorun:  42<br />belirtiler:  77<br />cdestek_kat: orta","sorun:  45<br />belirtiler:  78<br />cdestek_kat: orta","sorun:  49<br />belirtiler:  62<br />cdestek_kat: orta","sorun:  54<br />belirtiler:  86<br />cdestek_kat: orta","sorun:  54<br />belirtiler:  74<br />cdestek_kat: orta","sorun:  62<br />belirtiler:  58<br />cdestek_kat: orta","sorun:  64<br />belirtiler:  66<br />cdestek_kat: orta","sorun:  65<br />belirtiler:  86<br />cdestek_kat: orta","sorun:  67<br />belirtiler:  63<br />cdestek_kat: orta","sorun:  68<br />belirtiler: 106<br />cdestek_kat: orta","sorun:  68<br />belirtiler:  88<br />cdestek_kat: orta","sorun:  75<br />belirtiler: 109<br />cdestek_kat: orta","sorun:  75<br />belirtiler:  78<br />cdestek_kat: orta","sorun:  88<br />belirtiler:  81<br />cdestek_kat: orta","sorun:  89<br />belirtiler:  90<br />cdestek_kat: orta","sorun:  95<br />belirtiler:  62<br />cdestek_kat: orta","sorun:  96<br />belirtiler: 111<br />cdestek_kat: orta","sorun: 112<br />belirtiler:  87<br />cdestek_kat: orta","sorun: 118<br />belirtiler:  80<br />cdestek_kat: orta","sorun: 131<br />belirtiler:  80<br />cdestek_kat: orta","sorun: 139<br />belirtiler:  82<br />cdestek_kat: orta","sorun: 143<br />belirtiler:  81<br />cdestek_kat: orta","sorun: 144<br />belirtiler:  70<br />cdestek_kat: orta","sorun: 153<br />belirtiler:  73<br />cdestek_kat: orta","sorun: 153<br />belirtiler:  84<br />cdestek_kat: orta","sorun: 156<br />belirtiler:  74<br />cdestek_kat: orta","sorun: 158<br />belirtiler:  74<br />cdestek_kat: orta","sorun: 161<br />belirtiler: 109<br />cdestek_kat: orta","sorun: 164<br />belirtiler:  99<br />cdestek_kat: orta","sorun: 171<br />belirtiler:  74<br />cdestek_kat: orta","sorun: 172<br />belirtiler:  88<br />cdestek_kat: orta","sorun: 193<br />belirtiler:  79<br />cdestek_kat: orta","sorun: 193<br />belirtiler: 100<br />cdestek_kat: orta","sorun: 201<br />belirtiler:  91<br />cdestek_kat: orta","sorun: 202<br />belirtiler: 102<br />cdestek_kat: orta","sorun: 202<br />belirtiler: 102<br />cdestek_kat: orta","sorun: 203<br />belirtiler:  88<br />cdestek_kat: orta","sorun: 214<br />belirtiler:  93<br />cdestek_kat: orta","sorun: 217<br />belirtiler:  97<br />cdestek_kat: orta","sorun: 219<br />belirtiler:  93<br />cdestek_kat: orta","sorun: 229<br />belirtiler: 127<br />cdestek_kat: orta","sorun: 229<br />belirtiler:  99<br />cdestek_kat: orta","sorun: 260<br />belirtiler: 131<br />cdestek_kat: orta","sorun: 277<br />belirtiler: 101<br />cdestek_kat: orta","sorun: 290<br />belirtiler:  96<br />cdestek_kat: orta","sorun: 298<br />belirtiler: 111<br />cdestek_kat: orta","sorun: 342<br />belirtiler:  75<br />cdestek_kat: orta","sorun: 380<br />belirtiler: 107<br />cdestek_kat: orta","sorun: 525<br />belirtiler: 177<br />cdestek_kat: orta","sorun: 717<br />belirtiler: 117<br />cdestek_kat: orta"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(0,186,56,1)","dash":"solid"},"hoveron":"points","name":"orta","legendgroup":"orta","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[126,379],"y":[118,88],"text":["sorun: 126<br />belirtiler: 118<br />cdestek_kat: yuksek","sorun: 379<br />belirtiler:  88<br />cdestek_kat: yuksek"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(97,156,255,1)","dash":"solid"},"hoveron":"points","name":"yuksek","legendgroup":"yuksek","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-19.050000000000004,752.04999999999995],"tickmode":"array","ticktext":["0","200","400","600"],"tickvals":[0,200,400,600],"categoryorder":"array","categoryarray":["0","200","400","600"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"sorun","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[52.049999999999997,182.94999999999999],"tickmode":"array","ticktext":["60","90","120","150","180"],"tickvals":[60,90,120,150,180],"categoryorder":"array","categoryarray":["60","90","120","150","180"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"belirtiler","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"cdestek_kat","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"1ae82cfd1f9f":{"x":{},"y":{},"colour":{},"type":"scatter"}},"cur_data":"1ae82cfd1f9f","visdat":{"1ae82cfd1f9f":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<div class="plotly html-widget html-fill-item" id="htmlwidget-76e72c462b05dfc925d7" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-76e72c462b05dfc925d7">{"x":{"data":[{"x":[-200,-193.22033898305085,-186.4406779661017,-179.66101694915255,-172.88135593220341,-166.10169491525426,-159.32203389830508,-152.54237288135593,-145.76271186440678,-138.98305084745763,-132.20338983050848,-125.42372881355932,-118.64406779661017,-111.86440677966102,-105.08474576271186,-98.305084745762713,-91.525423728813564,-84.745762711864415,-77.966101694915267,-71.186440677966118,-64.406779661016969,-57.627118644067792,-50.847457627118644,-44.067796610169495,-37.288135593220346,-30.508474576271198,-23.728813559322049,-16.9491525423729,-10.169491525423723,-3.3898305084745743,3.3898305084745743,10.169491525423723,16.949152542372872,23.72881355932202,30.508474576271169,37.288135593220318,44.067796610169466,50.847457627118644,57.627118644067764,64.406779661016913,71.186440677966061,77.966101694915267,84.745762711864415,91.525423728813564,98.305084745762713,105.08474576271186,111.86440677966101,118.64406779661016,125.42372881355931,132.20338983050846,138.9830508474576,145.76271186440675,152.5423728813559,159.32203389830505,166.1016949152542,172.88135593220335,179.66101694915255,186.4406779661017,193.22033898305085,200],"y":[55.006551593285131,56.104281267401738,57.202010941518353,58.299740615634946,59.397470289751553,60.49519996386816,61.592929637984774,62.690659312101381,63.788388986217996,64.886118660334589,65.983848334451196,67.081578008567803,68.179307682684424,69.277037356801031,70.374767030917624,71.472496705034231,72.570226379150839,73.667956053267446,74.765685727384053,75.86341540150066,76.961145075617267,78.058874749733874,79.156604423850482,80.254334097967089,81.352063772083682,82.449793446200303,83.54752312031691,84.645252794433517,85.742982468550125,86.840712142666732,87.938441816783339,89.036171490899946,90.133901165016553,91.23163083913316,92.329360513249767,93.42709018736636,94.524819861482968,95.622549535599589,96.720279209716196,97.818008883832789,98.915738557949396,100.01346823206602,101.11119790618262,102.20892758029923,103.30665725441584,104.40438692853245,105.50211660264904,106.59984627676565,107.69757595088227,108.79530562499887,109.89303529911548,110.99076497323207,112.08849464734868,113.18622432146529,114.28395399558191,115.3816836696985,116.47941334381512,117.57714301793172,118.67487269204833,119.77260236616495],"text":["csorun: -200.00<br />belirtiler:  55.0<br />destek: dusuk","csorun: -193.22<br />belirtiler:  56.1<br />destek: dusuk","csorun: -186.44<br />belirtiler:  57.2<br />destek: dusuk","csorun: -179.66<br />belirtiler:  58.3<br />destek: dusuk","csorun: -172.88<br />belirtiler:  59.4<br />destek: dusuk","csorun: -166.10<br />belirtiler:  60.5<br />destek: dusuk","csorun: -159.32<br />belirtiler:  61.6<br />destek: dusuk","csorun: -152.54<br />belirtiler:  62.7<br />destek: dusuk","csorun: -145.76<br />belirtiler:  63.8<br />destek: dusuk","csorun: -138.98<br />belirtiler:  64.9<br />destek: dusuk","csorun: -132.20<br />belirtiler:  66.0<br />destek: dusuk","csorun: -125.42<br />belirtiler:  67.1<br />destek: dusuk","csorun: -118.64<br />belirtiler:  68.2<br />destek: dusuk","csorun: -111.86<br />belirtiler:  69.3<br />destek: dusuk","csorun: -105.08<br />belirtiler:  70.4<br />destek: dusuk","csorun:  -98.31<br />belirtiler:  71.5<br />destek: dusuk","csorun:  -91.53<br />belirtiler:  72.6<br />destek: dusuk","csorun:  -84.75<br />belirtiler:  73.7<br />destek: dusuk","csorun:  -77.97<br />belirtiler:  74.8<br />destek: dusuk","csorun:  -71.19<br />belirtiler:  75.9<br />destek: dusuk","csorun:  -64.41<br />belirtiler:  77.0<br />destek: dusuk","csorun:  -57.63<br />belirtiler:  78.1<br />destek: dusuk","csorun:  -50.85<br />belirtiler:  79.2<br />destek: dusuk","csorun:  -44.07<br />belirtiler:  80.3<br />destek: dusuk","csorun:  -37.29<br />belirtiler:  81.4<br />destek: dusuk","csorun:  -30.51<br />belirtiler:  82.4<br />destek: dusuk","csorun:  -23.73<br />belirtiler:  83.5<br />destek: dusuk","csorun:  -16.95<br />belirtiler:  84.6<br />destek: dusuk","csorun:  -10.17<br />belirtiler:  85.7<br />destek: dusuk","csorun:   -3.39<br />belirtiler:  86.8<br />destek: dusuk","csorun:    3.39<br />belirtiler:  87.9<br />destek: dusuk","csorun:   10.17<br />belirtiler:  89.0<br />destek: dusuk","csorun:   16.95<br />belirtiler:  90.1<br />destek: dusuk","csorun:   23.73<br />belirtiler:  91.2<br />destek: dusuk","csorun:   30.51<br />belirtiler:  92.3<br />destek: dusuk","csorun:   37.29<br />belirtiler:  93.4<br />destek: dusuk","csorun:   44.07<br />belirtiler:  94.5<br />destek: dusuk","csorun:   50.85<br />belirtiler:  95.6<br />destek: dusuk","csorun:   57.63<br />belirtiler:  96.7<br />destek: dusuk","csorun:   64.41<br />belirtiler:  97.8<br />destek: dusuk","csorun:   71.19<br />belirtiler:  98.9<br />destek: dusuk","csorun:   77.97<br />belirtiler: 100.0<br />destek: dusuk","csorun:   84.75<br />belirtiler: 101.1<br />destek: dusuk","csorun:   91.53<br />belirtiler: 102.2<br />destek: dusuk","csorun:   98.31<br />belirtiler: 103.3<br />destek: dusuk","csorun:  105.08<br />belirtiler: 104.4<br />destek: dusuk","csorun:  111.86<br />belirtiler: 105.5<br />destek: dusuk","csorun:  118.64<br />belirtiler: 106.6<br />destek: dusuk","csorun:  125.42<br />belirtiler: 107.7<br />destek: dusuk","csorun:  132.20<br />belirtiler: 108.8<br />destek: dusuk","csorun:  138.98<br />belirtiler: 109.9<br />destek: dusuk","csorun:  145.76<br />belirtiler: 111.0<br />destek: dusuk","csorun:  152.54<br />belirtiler: 112.1<br />destek: dusuk","csorun:  159.32<br />belirtiler: 113.2<br />destek: dusuk","csorun:  166.10<br />belirtiler: 114.3<br />destek: dusuk","csorun:  172.88<br />belirtiler: 115.4<br />destek: dusuk","csorun:  179.66<br />belirtiler: 116.5<br />destek: dusuk","csorun:  186.44<br />belirtiler: 117.6<br />destek: dusuk","csorun:  193.22<br />belirtiler: 118.7<br />destek: dusuk","csorun:  200.00<br />belirtiler: 119.8<br />destek: dusuk"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(248,118,109,1)","dash":"solid"},"hoveron":"points","name":"dusuk","legendgroup":"dusuk","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[-200,-193.22033898305085,-186.4406779661017,-179.66101694915255,-172.88135593220341,-166.10169491525426,-159.32203389830508,-152.54237288135593,-145.76271186440678,-138.98305084745763,-132.20338983050848,-125.42372881355932,-118.64406779661017,-111.86440677966102,-105.08474576271186,-98.305084745762713,-91.525423728813564,-84.745762711864415,-77.966101694915267,-71.186440677966118,-64.406779661016969,-57.627118644067792,-50.847457627118644,-44.067796610169495,-37.288135593220346,-30.508474576271198,-23.728813559322049,-16.9491525423729,-10.169491525423723,-3.3898305084745743,3.3898305084745743,10.169491525423723,16.949152542372872,23.72881355932202,30.508474576271169,37.288135593220318,44.067796610169466,50.847457627118644,57.627118644067764,64.406779661016913,71.186440677966061,77.966101694915267,84.745762711864415,91.525423728813564,98.305084745762713,105.08474576271186,111.86440677966101,118.64406779661016,125.42372881355931,132.20338983050846,138.9830508474576,145.76271186440675,152.5423728813559,159.32203389830505,166.1016949152542,172.88135593220335,179.66101694915255,186.4406779661017,193.22033898305085,200],"y":[72.396610497096916,72.979265718704909,73.561920940312902,74.144576161920881,74.727231383528874,75.309886605136867,75.892541826744861,76.475197048352854,77.057852269960847,77.640507491568826,78.223162713176819,78.805817934784812,79.388473156392806,79.971128378000799,80.553783599608778,81.136438821216771,81.719094042824764,82.301749264432758,82.884404486040751,83.46705970764873,84.049714929256723,84.632370150864716,85.215025372472709,85.797680594080703,86.380335815688682,86.962991037296675,87.545646258904668,88.128301480512661,88.710956702120654,89.293611923728648,89.876267145336627,90.45892236694462,91.041577588552613,91.624232810160606,92.206888031768599,92.789543253376578,93.372198474984572,93.954853696592565,94.537508918200558,95.120164139808537,95.70281936141653,96.285474583024524,96.868129804632517,97.45078502624051,98.033440247848503,98.616095469456496,99.198750691064475,99.781405912672469,100.36406113428046,100.94671635588846,101.52937157749645,102.11202679910443,102.69468202071242,103.27733724232041,103.85999246392841,104.44264768553639,105.02530290714439,105.60795812875237,106.19061335036037,106.77326857196836],"text":["csorun: -200.00<br />belirtiler:  72.4<br />destek: orta","csorun: -193.22<br />belirtiler:  73.0<br />destek: orta","csorun: -186.44<br />belirtiler:  73.6<br />destek: orta","csorun: -179.66<br />belirtiler:  74.1<br />destek: orta","csorun: -172.88<br />belirtiler:  74.7<br />destek: orta","csorun: -166.10<br />belirtiler:  75.3<br />destek: orta","csorun: -159.32<br />belirtiler:  75.9<br />destek: orta","csorun: -152.54<br />belirtiler:  76.5<br />destek: orta","csorun: -145.76<br />belirtiler:  77.1<br />destek: orta","csorun: -138.98<br />belirtiler:  77.6<br />destek: orta","csorun: -132.20<br />belirtiler:  78.2<br />destek: orta","csorun: -125.42<br />belirtiler:  78.8<br />destek: orta","csorun: -118.64<br />belirtiler:  79.4<br />destek: orta","csorun: -111.86<br />belirtiler:  80.0<br />destek: orta","csorun: -105.08<br />belirtiler:  80.6<br />destek: orta","csorun:  -98.31<br />belirtiler:  81.1<br />destek: orta","csorun:  -91.53<br />belirtiler:  81.7<br />destek: orta","csorun:  -84.75<br />belirtiler:  82.3<br />destek: orta","csorun:  -77.97<br />belirtiler:  82.9<br />destek: orta","csorun:  -71.19<br />belirtiler:  83.5<br />destek: orta","csorun:  -64.41<br />belirtiler:  84.0<br />destek: orta","csorun:  -57.63<br />belirtiler:  84.6<br />destek: orta","csorun:  -50.85<br />belirtiler:  85.2<br />destek: orta","csorun:  -44.07<br />belirtiler:  85.8<br />destek: orta","csorun:  -37.29<br />belirtiler:  86.4<br />destek: orta","csorun:  -30.51<br />belirtiler:  87.0<br />destek: orta","csorun:  -23.73<br />belirtiler:  87.5<br />destek: orta","csorun:  -16.95<br />belirtiler:  88.1<br />destek: orta","csorun:  -10.17<br />belirtiler:  88.7<br />destek: orta","csorun:   -3.39<br />belirtiler:  89.3<br />destek: orta","csorun:    3.39<br />belirtiler:  89.9<br />destek: orta","csorun:   10.17<br />belirtiler:  90.5<br />destek: orta","csorun:   16.95<br />belirtiler:  91.0<br />destek: orta","csorun:   23.73<br />belirtiler:  91.6<br />destek: orta","csorun:   30.51<br />belirtiler:  92.2<br />destek: orta","csorun:   37.29<br />belirtiler:  92.8<br />destek: orta","csorun:   44.07<br />belirtiler:  93.4<br />destek: orta","csorun:   50.85<br />belirtiler:  94.0<br />destek: orta","csorun:   57.63<br />belirtiler:  94.5<br />destek: orta","csorun:   64.41<br />belirtiler:  95.1<br />destek: orta","csorun:   71.19<br />belirtiler:  95.7<br />destek: orta","csorun:   77.97<br />belirtiler:  96.3<br />destek: orta","csorun:   84.75<br />belirtiler:  96.9<br />destek: orta","csorun:   91.53<br />belirtiler:  97.5<br />destek: orta","csorun:   98.31<br />belirtiler:  98.0<br />destek: orta","csorun:  105.08<br />belirtiler:  98.6<br />destek: orta","csorun:  111.86<br />belirtiler:  99.2<br />destek: orta","csorun:  118.64<br />belirtiler:  99.8<br />destek: orta","csorun:  125.42<br />belirtiler: 100.4<br />destek: orta","csorun:  132.20<br />belirtiler: 100.9<br />destek: orta","csorun:  138.98<br />belirtiler: 101.5<br />destek: orta","csorun:  145.76<br />belirtiler: 102.1<br />destek: orta","csorun:  152.54<br />belirtiler: 102.7<br />destek: orta","csorun:  159.32<br />belirtiler: 103.3<br />destek: orta","csorun:  166.10<br />belirtiler: 103.9<br />destek: orta","csorun:  172.88<br />belirtiler: 104.4<br />destek: orta","csorun:  179.66<br />belirtiler: 105.0<br />destek: orta","csorun:  186.44<br />belirtiler: 105.6<br />destek: orta","csorun:  193.22<br />belirtiler: 106.2<br />destek: orta","csorun:  200.00<br />belirtiler: 106.8<br />destek: orta"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(0,186,56,1)","dash":"solid"},"hoveron":"points","name":"orta","legendgroup":"orta","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[-200,-193.22033898305085,-186.4406779661017,-179.66101694915255,-172.88135593220341,-166.10169491525426,-159.32203389830508,-152.54237288135593,-145.76271186440678,-138.98305084745763,-132.20338983050848,-125.42372881355932,-118.64406779661017,-111.86440677966102,-105.08474576271186,-98.305084745762713,-91.525423728813564,-84.745762711864415,-77.966101694915267,-71.186440677966118,-64.406779661016969,-57.627118644067792,-50.847457627118644,-44.067796610169495,-37.288135593220346,-30.508474576271198,-23.728813559322049,-16.9491525423729,-10.169491525423723,-3.3898305084745743,3.3898305084745743,10.169491525423723,16.949152542372872,23.72881355932202,30.508474576271169,37.288135593220318,44.067796610169466,50.847457627118644,57.627118644067764,64.406779661016913,71.186440677966061,77.966101694915267,84.745762711864415,91.525423728813564,98.305084745762713,105.08474576271186,111.86440677966101,118.64406779661016,125.42372881355931,132.20338983050846,138.9830508474576,145.76271186440675,152.5423728813559,159.32203389830505,166.1016949152542,172.88135593220335,179.66101694915255,186.4406779661017,193.22033898305085,200],"y":[89.786669400908707,89.854250170008072,89.921830939107451,89.989411708206816,90.056992477306196,90.124573246405575,90.19215401550494,90.259734784604319,90.327315553703698,90.394896322803064,90.462477091902443,90.530057861001822,90.597638630101187,90.665219399200566,90.732800168299931,90.800380937399311,90.86796170649869,90.935542475598069,91.003123244697449,91.070704013796799,91.138284782896179,91.205865551995558,91.273446321094937,91.341027090194316,91.408607859293681,91.476188628393047,91.543769397492426,91.611350166591805,91.678930935691184,91.746511704790564,91.814092473889914,91.881673242989294,91.949254012088673,92.016834781188052,92.084415550287432,92.151996319386797,92.219577088486176,92.287157857585541,92.35473862668492,92.422319395784285,92.489900164883665,92.55748093398303,92.625061703082409,92.692642472181788,92.760223241281167,92.827804010380547,92.895384779479912,92.962965548579291,93.030546317678656,93.098127086778035,93.165707855877415,93.23328862497678,93.300869394076159,93.368450163175538,93.436030932274903,93.503611701374268,93.571192470473662,93.638773239573027,93.706354008672406,93.773934777771771],"text":["csorun: -200.00<br />belirtiler:  89.8<br />destek: yuksek","csorun: -193.22<br />belirtiler:  89.9<br />destek: yuksek","csorun: -186.44<br />belirtiler:  89.9<br />destek: yuksek","csorun: -179.66<br />belirtiler:  90.0<br />destek: yuksek","csorun: -172.88<br />belirtiler:  90.1<br />destek: yuksek","csorun: -166.10<br />belirtiler:  90.1<br />destek: yuksek","csorun: -159.32<br />belirtiler:  90.2<br />destek: yuksek","csorun: -152.54<br />belirtiler:  90.3<br />destek: yuksek","csorun: -145.76<br />belirtiler:  90.3<br />destek: yuksek","csorun: -138.98<br />belirtiler:  90.4<br />destek: yuksek","csorun: -132.20<br />belirtiler:  90.5<br />destek: yuksek","csorun: -125.42<br />belirtiler:  90.5<br />destek: yuksek","csorun: -118.64<br />belirtiler:  90.6<br />destek: yuksek","csorun: -111.86<br />belirtiler:  90.7<br />destek: yuksek","csorun: -105.08<br />belirtiler:  90.7<br />destek: yuksek","csorun:  -98.31<br />belirtiler:  90.8<br />destek: yuksek","csorun:  -91.53<br />belirtiler:  90.9<br />destek: yuksek","csorun:  -84.75<br />belirtiler:  90.9<br />destek: yuksek","csorun:  -77.97<br />belirtiler:  91.0<br />destek: yuksek","csorun:  -71.19<br />belirtiler:  91.1<br />destek: yuksek","csorun:  -64.41<br />belirtiler:  91.1<br />destek: yuksek","csorun:  -57.63<br />belirtiler:  91.2<br />destek: yuksek","csorun:  -50.85<br />belirtiler:  91.3<br />destek: yuksek","csorun:  -44.07<br />belirtiler:  91.3<br />destek: yuksek","csorun:  -37.29<br />belirtiler:  91.4<br />destek: yuksek","csorun:  -30.51<br />belirtiler:  91.5<br />destek: yuksek","csorun:  -23.73<br />belirtiler:  91.5<br />destek: yuksek","csorun:  -16.95<br />belirtiler:  91.6<br />destek: yuksek","csorun:  -10.17<br />belirtiler:  91.7<br />destek: yuksek","csorun:   -3.39<br />belirtiler:  91.7<br />destek: yuksek","csorun:    3.39<br />belirtiler:  91.8<br />destek: yuksek","csorun:   10.17<br />belirtiler:  91.9<br />destek: yuksek","csorun:   16.95<br />belirtiler:  91.9<br />destek: yuksek","csorun:   23.73<br />belirtiler:  92.0<br />destek: yuksek","csorun:   30.51<br />belirtiler:  92.1<br />destek: yuksek","csorun:   37.29<br />belirtiler:  92.2<br />destek: yuksek","csorun:   44.07<br />belirtiler:  92.2<br />destek: yuksek","csorun:   50.85<br />belirtiler:  92.3<br />destek: yuksek","csorun:   57.63<br />belirtiler:  92.4<br />destek: yuksek","csorun:   64.41<br />belirtiler:  92.4<br />destek: yuksek","csorun:   71.19<br />belirtiler:  92.5<br />destek: yuksek","csorun:   77.97<br />belirtiler:  92.6<br />destek: yuksek","csorun:   84.75<br />belirtiler:  92.6<br />destek: yuksek","csorun:   91.53<br />belirtiler:  92.7<br />destek: yuksek","csorun:   98.31<br />belirtiler:  92.8<br />destek: yuksek","csorun:  105.08<br />belirtiler:  92.8<br />destek: yuksek","csorun:  111.86<br />belirtiler:  92.9<br />destek: yuksek","csorun:  118.64<br />belirtiler:  93.0<br />destek: yuksek","csorun:  125.42<br />belirtiler:  93.0<br />destek: yuksek","csorun:  132.20<br />belirtiler:  93.1<br />destek: yuksek","csorun:  138.98<br />belirtiler:  93.2<br />destek: yuksek","csorun:  145.76<br />belirtiler:  93.2<br />destek: yuksek","csorun:  152.54<br />belirtiler:  93.3<br />destek: yuksek","csorun:  159.32<br />belirtiler:  93.4<br />destek: yuksek","csorun:  166.10<br />belirtiler:  93.4<br />destek: yuksek","csorun:  172.88<br />belirtiler:  93.5<br />destek: yuksek","csorun:  179.66<br />belirtiler:  93.6<br />destek: yuksek","csorun:  186.44<br />belirtiler:  93.6<br />destek: yuksek","csorun:  193.22<br />belirtiler:  93.7<br />destek: yuksek","csorun:  200.00<br />belirtiler:  93.8<br />destek: yuksek"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(97,156,255,1)","dash":"solid"},"hoveron":"points","name":"yuksek","legendgroup":"yuksek","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-220,220],"tickmode":"array","ticktext":["-200","-100","0","100","200"],"tickvals":[-200,-100.00000000000001,0,100,200],"categoryorder":"array","categoryarray":["-200","-100","0","100","200"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"csorun","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[51.768249054641139,123.01090490480894],"tickmode":"array","ticktext":["60","80","100","120"],"tickvals":[60,80,100,120],"categoryorder":"array","categoryarray":["60","80","100","120"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"belirtiler","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"destek","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"1ae869d3339f":{"x":{},"y":{},"colour":{},"type":"scatter"}},"cur_data":"1ae869d3339f","visdat":{"1ae869d3339f":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div id="coklu-regresyonda-iki-yonlu-etkilesim-etkisi-17" class="section level2" number="4.89">
<h2><span class="header-section-number">4.89</span> Coklu Regresyonda Iki-Yonlu Etkilesim Etkisi</h2>
<ul>
<li><p>Yuksek duzeyde sosyal destek ile sorunlardaki artislar psikolojik belirtilerde kucuk artislarla iliskilendirilirler.</p></li>
<li><p>Orta duzeyde sosyal destek ile sorunlardaki artislar psikolojik belirtilerde
daha buyuk artislarla iliskilendirilir.</p></li>
<li><p>Dusuk duzeyde sosyal destek ile sorunlardaki artislar psikolojik belirtilerde
dramatik artislarla iliskilendirilir.</p></li>
</ul>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="çoklu-regresyon.html#cb89-1" tabindex="-1"></a><span class="fu">ggplotly</span>(p)</span></code></pre></div>
<div class="plotly html-widget html-fill-item" id="htmlwidget-e1ba04d1f2dd5943be3d" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-e1ba04d1f2dd5943be3d">{"x":{"data":[{"x":[-200,-193.22033898305085,-186.4406779661017,-179.66101694915255,-172.88135593220341,-166.10169491525426,-159.32203389830508,-152.54237288135593,-145.76271186440678,-138.98305084745763,-132.20338983050848,-125.42372881355932,-118.64406779661017,-111.86440677966102,-105.08474576271186,-98.305084745762713,-91.525423728813564,-84.745762711864415,-77.966101694915267,-71.186440677966118,-64.406779661016969,-57.627118644067792,-50.847457627118644,-44.067796610169495,-37.288135593220346,-30.508474576271198,-23.728813559322049,-16.9491525423729,-10.169491525423723,-3.3898305084745743,3.3898305084745743,10.169491525423723,16.949152542372872,23.72881355932202,30.508474576271169,37.288135593220318,44.067796610169466,50.847457627118644,57.627118644067764,64.406779661016913,71.186440677966061,77.966101694915267,84.745762711864415,91.525423728813564,98.305084745762713,105.08474576271186,111.86440677966101,118.64406779661016,125.42372881355931,132.20338983050846,138.9830508474576,145.76271186440675,152.5423728813559,159.32203389830505,166.1016949152542,172.88135593220335,179.66101694915255,186.4406779661017,193.22033898305085,200],"y":[55.006551593285131,56.104281267401738,57.202010941518353,58.299740615634946,59.397470289751553,60.49519996386816,61.592929637984774,62.690659312101381,63.788388986217996,64.886118660334589,65.983848334451196,67.081578008567803,68.179307682684424,69.277037356801031,70.374767030917624,71.472496705034231,72.570226379150839,73.667956053267446,74.765685727384053,75.86341540150066,76.961145075617267,78.058874749733874,79.156604423850482,80.254334097967089,81.352063772083682,82.449793446200303,83.54752312031691,84.645252794433517,85.742982468550125,86.840712142666732,87.938441816783339,89.036171490899946,90.133901165016553,91.23163083913316,92.329360513249767,93.42709018736636,94.524819861482968,95.622549535599589,96.720279209716196,97.818008883832789,98.915738557949396,100.01346823206602,101.11119790618262,102.20892758029923,103.30665725441584,104.40438692853245,105.50211660264904,106.59984627676565,107.69757595088227,108.79530562499887,109.89303529911548,110.99076497323207,112.08849464734868,113.18622432146529,114.28395399558191,115.3816836696985,116.47941334381512,117.57714301793172,118.67487269204833,119.77260236616495],"text":["csorun: -200.00<br />belirtiler:  55.0<br />destek: dusuk","csorun: -193.22<br />belirtiler:  56.1<br />destek: dusuk","csorun: -186.44<br />belirtiler:  57.2<br />destek: dusuk","csorun: -179.66<br />belirtiler:  58.3<br />destek: dusuk","csorun: -172.88<br />belirtiler:  59.4<br />destek: dusuk","csorun: -166.10<br />belirtiler:  60.5<br />destek: dusuk","csorun: -159.32<br />belirtiler:  61.6<br />destek: dusuk","csorun: -152.54<br />belirtiler:  62.7<br />destek: dusuk","csorun: -145.76<br />belirtiler:  63.8<br />destek: dusuk","csorun: -138.98<br />belirtiler:  64.9<br />destek: dusuk","csorun: -132.20<br />belirtiler:  66.0<br />destek: dusuk","csorun: -125.42<br />belirtiler:  67.1<br />destek: dusuk","csorun: -118.64<br />belirtiler:  68.2<br />destek: dusuk","csorun: -111.86<br />belirtiler:  69.3<br />destek: dusuk","csorun: -105.08<br />belirtiler:  70.4<br />destek: dusuk","csorun:  -98.31<br />belirtiler:  71.5<br />destek: dusuk","csorun:  -91.53<br />belirtiler:  72.6<br />destek: dusuk","csorun:  -84.75<br />belirtiler:  73.7<br />destek: dusuk","csorun:  -77.97<br />belirtiler:  74.8<br />destek: dusuk","csorun:  -71.19<br />belirtiler:  75.9<br />destek: dusuk","csorun:  -64.41<br />belirtiler:  77.0<br />destek: dusuk","csorun:  -57.63<br />belirtiler:  78.1<br />destek: dusuk","csorun:  -50.85<br />belirtiler:  79.2<br />destek: dusuk","csorun:  -44.07<br />belirtiler:  80.3<br />destek: dusuk","csorun:  -37.29<br />belirtiler:  81.4<br />destek: dusuk","csorun:  -30.51<br />belirtiler:  82.4<br />destek: dusuk","csorun:  -23.73<br />belirtiler:  83.5<br />destek: dusuk","csorun:  -16.95<br />belirtiler:  84.6<br />destek: dusuk","csorun:  -10.17<br />belirtiler:  85.7<br />destek: dusuk","csorun:   -3.39<br />belirtiler:  86.8<br />destek: dusuk","csorun:    3.39<br />belirtiler:  87.9<br />destek: dusuk","csorun:   10.17<br />belirtiler:  89.0<br />destek: dusuk","csorun:   16.95<br />belirtiler:  90.1<br />destek: dusuk","csorun:   23.73<br />belirtiler:  91.2<br />destek: dusuk","csorun:   30.51<br />belirtiler:  92.3<br />destek: dusuk","csorun:   37.29<br />belirtiler:  93.4<br />destek: dusuk","csorun:   44.07<br />belirtiler:  94.5<br />destek: dusuk","csorun:   50.85<br />belirtiler:  95.6<br />destek: dusuk","csorun:   57.63<br />belirtiler:  96.7<br />destek: dusuk","csorun:   64.41<br />belirtiler:  97.8<br />destek: dusuk","csorun:   71.19<br />belirtiler:  98.9<br />destek: dusuk","csorun:   77.97<br />belirtiler: 100.0<br />destek: dusuk","csorun:   84.75<br />belirtiler: 101.1<br />destek: dusuk","csorun:   91.53<br />belirtiler: 102.2<br />destek: dusuk","csorun:   98.31<br />belirtiler: 103.3<br />destek: dusuk","csorun:  105.08<br />belirtiler: 104.4<br />destek: dusuk","csorun:  111.86<br />belirtiler: 105.5<br />destek: dusuk","csorun:  118.64<br />belirtiler: 106.6<br />destek: dusuk","csorun:  125.42<br />belirtiler: 107.7<br />destek: dusuk","csorun:  132.20<br />belirtiler: 108.8<br />destek: dusuk","csorun:  138.98<br />belirtiler: 109.9<br />destek: dusuk","csorun:  145.76<br />belirtiler: 111.0<br />destek: dusuk","csorun:  152.54<br />belirtiler: 112.1<br />destek: dusuk","csorun:  159.32<br />belirtiler: 113.2<br />destek: dusuk","csorun:  166.10<br />belirtiler: 114.3<br />destek: dusuk","csorun:  172.88<br />belirtiler: 115.4<br />destek: dusuk","csorun:  179.66<br />belirtiler: 116.5<br />destek: dusuk","csorun:  186.44<br />belirtiler: 117.6<br />destek: dusuk","csorun:  193.22<br />belirtiler: 118.7<br />destek: dusuk","csorun:  200.00<br />belirtiler: 119.8<br />destek: dusuk"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(248,118,109,1)","dash":"solid"},"hoveron":"points","name":"dusuk","legendgroup":"dusuk","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[-200,-193.22033898305085,-186.4406779661017,-179.66101694915255,-172.88135593220341,-166.10169491525426,-159.32203389830508,-152.54237288135593,-145.76271186440678,-138.98305084745763,-132.20338983050848,-125.42372881355932,-118.64406779661017,-111.86440677966102,-105.08474576271186,-98.305084745762713,-91.525423728813564,-84.745762711864415,-77.966101694915267,-71.186440677966118,-64.406779661016969,-57.627118644067792,-50.847457627118644,-44.067796610169495,-37.288135593220346,-30.508474576271198,-23.728813559322049,-16.9491525423729,-10.169491525423723,-3.3898305084745743,3.3898305084745743,10.169491525423723,16.949152542372872,23.72881355932202,30.508474576271169,37.288135593220318,44.067796610169466,50.847457627118644,57.627118644067764,64.406779661016913,71.186440677966061,77.966101694915267,84.745762711864415,91.525423728813564,98.305084745762713,105.08474576271186,111.86440677966101,118.64406779661016,125.42372881355931,132.20338983050846,138.9830508474576,145.76271186440675,152.5423728813559,159.32203389830505,166.1016949152542,172.88135593220335,179.66101694915255,186.4406779661017,193.22033898305085,200],"y":[72.396610497096916,72.979265718704909,73.561920940312902,74.144576161920881,74.727231383528874,75.309886605136867,75.892541826744861,76.475197048352854,77.057852269960847,77.640507491568826,78.223162713176819,78.805817934784812,79.388473156392806,79.971128378000799,80.553783599608778,81.136438821216771,81.719094042824764,82.301749264432758,82.884404486040751,83.46705970764873,84.049714929256723,84.632370150864716,85.215025372472709,85.797680594080703,86.380335815688682,86.962991037296675,87.545646258904668,88.128301480512661,88.710956702120654,89.293611923728648,89.876267145336627,90.45892236694462,91.041577588552613,91.624232810160606,92.206888031768599,92.789543253376578,93.372198474984572,93.954853696592565,94.537508918200558,95.120164139808537,95.70281936141653,96.285474583024524,96.868129804632517,97.45078502624051,98.033440247848503,98.616095469456496,99.198750691064475,99.781405912672469,100.36406113428046,100.94671635588846,101.52937157749645,102.11202679910443,102.69468202071242,103.27733724232041,103.85999246392841,104.44264768553639,105.02530290714439,105.60795812875237,106.19061335036037,106.77326857196836],"text":["csorun: -200.00<br />belirtiler:  72.4<br />destek: orta","csorun: -193.22<br />belirtiler:  73.0<br />destek: orta","csorun: -186.44<br />belirtiler:  73.6<br />destek: orta","csorun: -179.66<br />belirtiler:  74.1<br />destek: orta","csorun: -172.88<br />belirtiler:  74.7<br />destek: orta","csorun: -166.10<br />belirtiler:  75.3<br />destek: orta","csorun: -159.32<br />belirtiler:  75.9<br />destek: orta","csorun: -152.54<br />belirtiler:  76.5<br />destek: orta","csorun: -145.76<br />belirtiler:  77.1<br />destek: orta","csorun: -138.98<br />belirtiler:  77.6<br />destek: orta","csorun: -132.20<br />belirtiler:  78.2<br />destek: orta","csorun: -125.42<br />belirtiler:  78.8<br />destek: orta","csorun: -118.64<br />belirtiler:  79.4<br />destek: orta","csorun: -111.86<br />belirtiler:  80.0<br />destek: orta","csorun: -105.08<br />belirtiler:  80.6<br />destek: orta","csorun:  -98.31<br />belirtiler:  81.1<br />destek: orta","csorun:  -91.53<br />belirtiler:  81.7<br />destek: orta","csorun:  -84.75<br />belirtiler:  82.3<br />destek: orta","csorun:  -77.97<br />belirtiler:  82.9<br />destek: orta","csorun:  -71.19<br />belirtiler:  83.5<br />destek: orta","csorun:  -64.41<br />belirtiler:  84.0<br />destek: orta","csorun:  -57.63<br />belirtiler:  84.6<br />destek: orta","csorun:  -50.85<br />belirtiler:  85.2<br />destek: orta","csorun:  -44.07<br />belirtiler:  85.8<br />destek: orta","csorun:  -37.29<br />belirtiler:  86.4<br />destek: orta","csorun:  -30.51<br />belirtiler:  87.0<br />destek: orta","csorun:  -23.73<br />belirtiler:  87.5<br />destek: orta","csorun:  -16.95<br />belirtiler:  88.1<br />destek: orta","csorun:  -10.17<br />belirtiler:  88.7<br />destek: orta","csorun:   -3.39<br />belirtiler:  89.3<br />destek: orta","csorun:    3.39<br />belirtiler:  89.9<br />destek: orta","csorun:   10.17<br />belirtiler:  90.5<br />destek: orta","csorun:   16.95<br />belirtiler:  91.0<br />destek: orta","csorun:   23.73<br />belirtiler:  91.6<br />destek: orta","csorun:   30.51<br />belirtiler:  92.2<br />destek: orta","csorun:   37.29<br />belirtiler:  92.8<br />destek: orta","csorun:   44.07<br />belirtiler:  93.4<br />destek: orta","csorun:   50.85<br />belirtiler:  94.0<br />destek: orta","csorun:   57.63<br />belirtiler:  94.5<br />destek: orta","csorun:   64.41<br />belirtiler:  95.1<br />destek: orta","csorun:   71.19<br />belirtiler:  95.7<br />destek: orta","csorun:   77.97<br />belirtiler:  96.3<br />destek: orta","csorun:   84.75<br />belirtiler:  96.9<br />destek: orta","csorun:   91.53<br />belirtiler:  97.5<br />destek: orta","csorun:   98.31<br />belirtiler:  98.0<br />destek: orta","csorun:  105.08<br />belirtiler:  98.6<br />destek: orta","csorun:  111.86<br />belirtiler:  99.2<br />destek: orta","csorun:  118.64<br />belirtiler:  99.8<br />destek: orta","csorun:  125.42<br />belirtiler: 100.4<br />destek: orta","csorun:  132.20<br />belirtiler: 100.9<br />destek: orta","csorun:  138.98<br />belirtiler: 101.5<br />destek: orta","csorun:  145.76<br />belirtiler: 102.1<br />destek: orta","csorun:  152.54<br />belirtiler: 102.7<br />destek: orta","csorun:  159.32<br />belirtiler: 103.3<br />destek: orta","csorun:  166.10<br />belirtiler: 103.9<br />destek: orta","csorun:  172.88<br />belirtiler: 104.4<br />destek: orta","csorun:  179.66<br />belirtiler: 105.0<br />destek: orta","csorun:  186.44<br />belirtiler: 105.6<br />destek: orta","csorun:  193.22<br />belirtiler: 106.2<br />destek: orta","csorun:  200.00<br />belirtiler: 106.8<br />destek: orta"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(0,186,56,1)","dash":"solid"},"hoveron":"points","name":"orta","legendgroup":"orta","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[-200,-193.22033898305085,-186.4406779661017,-179.66101694915255,-172.88135593220341,-166.10169491525426,-159.32203389830508,-152.54237288135593,-145.76271186440678,-138.98305084745763,-132.20338983050848,-125.42372881355932,-118.64406779661017,-111.86440677966102,-105.08474576271186,-98.305084745762713,-91.525423728813564,-84.745762711864415,-77.966101694915267,-71.186440677966118,-64.406779661016969,-57.627118644067792,-50.847457627118644,-44.067796610169495,-37.288135593220346,-30.508474576271198,-23.728813559322049,-16.9491525423729,-10.169491525423723,-3.3898305084745743,3.3898305084745743,10.169491525423723,16.949152542372872,23.72881355932202,30.508474576271169,37.288135593220318,44.067796610169466,50.847457627118644,57.627118644067764,64.406779661016913,71.186440677966061,77.966101694915267,84.745762711864415,91.525423728813564,98.305084745762713,105.08474576271186,111.86440677966101,118.64406779661016,125.42372881355931,132.20338983050846,138.9830508474576,145.76271186440675,152.5423728813559,159.32203389830505,166.1016949152542,172.88135593220335,179.66101694915255,186.4406779661017,193.22033898305085,200],"y":[89.786669400908707,89.854250170008072,89.921830939107451,89.989411708206816,90.056992477306196,90.124573246405575,90.19215401550494,90.259734784604319,90.327315553703698,90.394896322803064,90.462477091902443,90.530057861001822,90.597638630101187,90.665219399200566,90.732800168299931,90.800380937399311,90.86796170649869,90.935542475598069,91.003123244697449,91.070704013796799,91.138284782896179,91.205865551995558,91.273446321094937,91.341027090194316,91.408607859293681,91.476188628393047,91.543769397492426,91.611350166591805,91.678930935691184,91.746511704790564,91.814092473889914,91.881673242989294,91.949254012088673,92.016834781188052,92.084415550287432,92.151996319386797,92.219577088486176,92.287157857585541,92.35473862668492,92.422319395784285,92.489900164883665,92.55748093398303,92.625061703082409,92.692642472181788,92.760223241281167,92.827804010380547,92.895384779479912,92.962965548579291,93.030546317678656,93.098127086778035,93.165707855877415,93.23328862497678,93.300869394076159,93.368450163175538,93.436030932274903,93.503611701374268,93.571192470473662,93.638773239573027,93.706354008672406,93.773934777771771],"text":["csorun: -200.00<br />belirtiler:  89.8<br />destek: yuksek","csorun: -193.22<br />belirtiler:  89.9<br />destek: yuksek","csorun: -186.44<br />belirtiler:  89.9<br />destek: yuksek","csorun: -179.66<br />belirtiler:  90.0<br />destek: yuksek","csorun: -172.88<br />belirtiler:  90.1<br />destek: yuksek","csorun: -166.10<br />belirtiler:  90.1<br />destek: yuksek","csorun: -159.32<br />belirtiler:  90.2<br />destek: yuksek","csorun: -152.54<br />belirtiler:  90.3<br />destek: yuksek","csorun: -145.76<br />belirtiler:  90.3<br />destek: yuksek","csorun: -138.98<br />belirtiler:  90.4<br />destek: yuksek","csorun: -132.20<br />belirtiler:  90.5<br />destek: yuksek","csorun: -125.42<br />belirtiler:  90.5<br />destek: yuksek","csorun: -118.64<br />belirtiler:  90.6<br />destek: yuksek","csorun: -111.86<br />belirtiler:  90.7<br />destek: yuksek","csorun: -105.08<br />belirtiler:  90.7<br />destek: yuksek","csorun:  -98.31<br />belirtiler:  90.8<br />destek: yuksek","csorun:  -91.53<br />belirtiler:  90.9<br />destek: yuksek","csorun:  -84.75<br />belirtiler:  90.9<br />destek: yuksek","csorun:  -77.97<br />belirtiler:  91.0<br />destek: yuksek","csorun:  -71.19<br />belirtiler:  91.1<br />destek: yuksek","csorun:  -64.41<br />belirtiler:  91.1<br />destek: yuksek","csorun:  -57.63<br />belirtiler:  91.2<br />destek: yuksek","csorun:  -50.85<br />belirtiler:  91.3<br />destek: yuksek","csorun:  -44.07<br />belirtiler:  91.3<br />destek: yuksek","csorun:  -37.29<br />belirtiler:  91.4<br />destek: yuksek","csorun:  -30.51<br />belirtiler:  91.5<br />destek: yuksek","csorun:  -23.73<br />belirtiler:  91.5<br />destek: yuksek","csorun:  -16.95<br />belirtiler:  91.6<br />destek: yuksek","csorun:  -10.17<br />belirtiler:  91.7<br />destek: yuksek","csorun:   -3.39<br />belirtiler:  91.7<br />destek: yuksek","csorun:    3.39<br />belirtiler:  91.8<br />destek: yuksek","csorun:   10.17<br />belirtiler:  91.9<br />destek: yuksek","csorun:   16.95<br />belirtiler:  91.9<br />destek: yuksek","csorun:   23.73<br />belirtiler:  92.0<br />destek: yuksek","csorun:   30.51<br />belirtiler:  92.1<br />destek: yuksek","csorun:   37.29<br />belirtiler:  92.2<br />destek: yuksek","csorun:   44.07<br />belirtiler:  92.2<br />destek: yuksek","csorun:   50.85<br />belirtiler:  92.3<br />destek: yuksek","csorun:   57.63<br />belirtiler:  92.4<br />destek: yuksek","csorun:   64.41<br />belirtiler:  92.4<br />destek: yuksek","csorun:   71.19<br />belirtiler:  92.5<br />destek: yuksek","csorun:   77.97<br />belirtiler:  92.6<br />destek: yuksek","csorun:   84.75<br />belirtiler:  92.6<br />destek: yuksek","csorun:   91.53<br />belirtiler:  92.7<br />destek: yuksek","csorun:   98.31<br />belirtiler:  92.8<br />destek: yuksek","csorun:  105.08<br />belirtiler:  92.8<br />destek: yuksek","csorun:  111.86<br />belirtiler:  92.9<br />destek: yuksek","csorun:  118.64<br />belirtiler:  93.0<br />destek: yuksek","csorun:  125.42<br />belirtiler:  93.0<br />destek: yuksek","csorun:  132.20<br />belirtiler:  93.1<br />destek: yuksek","csorun:  138.98<br />belirtiler:  93.2<br />destek: yuksek","csorun:  145.76<br />belirtiler:  93.2<br />destek: yuksek","csorun:  152.54<br />belirtiler:  93.3<br />destek: yuksek","csorun:  159.32<br />belirtiler:  93.4<br />destek: yuksek","csorun:  166.10<br />belirtiler:  93.4<br />destek: yuksek","csorun:  172.88<br />belirtiler:  93.5<br />destek: yuksek","csorun:  179.66<br />belirtiler:  93.6<br />destek: yuksek","csorun:  186.44<br />belirtiler:  93.6<br />destek: yuksek","csorun:  193.22<br />belirtiler:  93.7<br />destek: yuksek","csorun:  200.00<br />belirtiler:  93.8<br />destek: yuksek"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(97,156,255,1)","dash":"solid"},"hoveron":"points","name":"yuksek","legendgroup":"yuksek","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-220,220],"tickmode":"array","ticktext":["-200","-100","0","100","200"],"tickvals":[-200,-100.00000000000001,0,100,200],"categoryorder":"array","categoryarray":["-200","-100","0","100","200"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"csorun","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[51.768249054641139,123.01090490480894],"tickmode":"array","ticktext":["60","80","100","120"],"tickvals":[60,80,100,120],"categoryorder":"array","categoryarray":["60","80","100","120"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"belirtiler","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"destek","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"1ae83f9b6752":{"x":{},"y":{},"colour":{},"type":"scatter"}},"cur_data":"1ae83f9b6752","visdat":{"1ae83f9b6752":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>require(stats); require(graphics)
pairs(LifeCycleSavings, panel = panel.smooth,
main = "LifeCycleSavings data")
fm1 &lt;- lm(sr ~ pop15 + pop75 + dpi + ddpi, data = LifeCycleSavings)
summary(fm1)</p>
<p>sr_3 &lt;- lm(sr ~ pop75 + dpi + ddpi, data = LifeCycleSavings)
summary(sr_3)<span class="math inline">\(residuals pop15_3 &lt;- lm(pop15 ~ pop75 + dpi + ddpi, data = LifeCycleSavings) summary(pop15_3)\)</span>residuals
model_last &lt;- lm(summary(sr_3)<span class="math inline">\(residuals ~ summary(pop15_3)\)</span>residuals)
round(model_last$coefficients,3)</p>

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;

    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    $(solveme[i]).after(" <span class='webex-icon'></span>");
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    $(selects[i]).after(" <span class='webex-icon'></span>");
  }

  update_total_correct();
}

</script>
<script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );

  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });

  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>OLC733</strong>: R ile Çok Değişkenli İstatistik ve Ölçme Uygulamaları" was written by Kubra Atalay Kabasakal. It was last built on 2024-02-26.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
