<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>OLC733</title>

    <meta name="author" content="Kubra Atalay Kabasakal" />
  
   <meta name="description" content="<p>Bu notlar OLC733 dersi için hazırlanmıştır.</p>" />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="OLC733" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="<a href="https://github.com/atalay-k/OLC733" class="uri">https://github.com/atalay-k/OLC733</a>" />
  <meta property="og:image" content="<a href="https://github.com/atalay-k/OLC733" class="uri">https://github.com/atalay-k/OLC733</a>/images/logos/logo.png" />
  <meta property="og:description" content="<p>Bu notlar OLC733 dersi için hazırlanmıştır.</p>" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="OLC733" />
  
  <meta name="twitter:description" content="<p>Bu notlar OLC733 dersi için hazırlanmıştır.</p>" />
  <meta name="twitter:image" content="<a href="https://github.com/atalay-k/OLC733" class="uri">https://github.com/atalay-k/OLC733</a>/images/logos/logo.png" />
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.6.1/transition.js"></script>
    <script src="libs/bs3compat-0.6.1/tabs.js"></script>
    <script src="libs/bs3compat-0.6.1/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
    <link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
    <script src="libs/datatables-binding-0.32/datatables.js"></script>
    <link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
    <script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
    <link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
    <script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
    <script src="libs/plotly-binding-4.10.4/plotly.js"></script>
    <script src="libs/typedarray-0.1/typedarray.min.js"></script>
    <link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
    <script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
      <link rel="stylesheet" href="include/psyteachr.css" />
    <link rel="stylesheet" href="include/webex.css" />
    <link rel="stylesheet" href="include/style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<!--bookdown:title:start-->
<!--bookdown:title:end-->

<!--bookdown:toc:start-->
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="R ile Çok Değişkenli İstatistik ve Ölçme Uygulamaları">OLC733</a>:
        <small class="text-muted">R ile Çok Değişkenli İstatistik ve Ölçme Uygulamaları</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<!--bookdown:toc:end-->
<!--bookdown:body:start-->
<div class="small_right">
<p><img src="images/logos/logo.png" alt="ADS Hex Logo"/></p>
</div>
<div id="ders-hakkında" class="section level1 unnumbered">
<h1 class="unnumbered">Ders Hakkında</h1>
<p>Bu dersin amacı, R yazılımını kullanarak veri üzerinde istenilen çok değişkenli istatistiksel ve psikometrik işlemlerin yapılabilmesini sağlamaktır.</p>
<p>Tez ve makale çalışmalarında öğrencilerimizin analizlerini R yazılımı ile hiçbir paket programa ihtiyaç duymadan kendi başlarına yapmalarını sağlamaktır.</p>
<p>Ders İçeriği:</p>
<ul>
<li>Çok değişkenli İstatistik Varsayımları<br />
</li>
<li>Çoklu Regresyon<br />
</li>
<li>Yol Analizi</li>
<li>Açımlayıcı Faktör Analizi<br />
</li>
<li>Doğrulayıcı Faktör Analizi<br />
</li>
<li>Progralamaya Giriş<br />
</li>
<li>Klasik Test Kuramı<br />
</li>
<li>Madde Tepki Kuramı<br />
</li>
<li>Veri Üretimi</li>
</ul>
<div id="eğitmen" class="section level2 unnumbered">
<h2 class="unnumbered">Eğitmen</h2>
<p><svg aria-hidden="true" role="img" viewBox="0 0 448 512" style="height:1em;width:0.88em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:black;overflow:visible;position:relative;"><path d="M224 256A128 128 0 1 1 224 0a128 128 0 1 1 0 256zM209.1 359.2l-18.6-31c-6.4-10.7 1.3-24.2 13.7-24.2H224h19.7c12.4 0 20.1 13.6 13.7 24.2l-18.6 31 33.4 123.9 36-146.9c2-8.1 9.8-13.4 17.9-11.3c70.1 17.6 121.9 81 121.9 156.4c0 17-13.8 30.7-30.7 30.7H285.5c-2.1 0-4-.4-5.8-1.1l.3 1.1H168l.3-1.1c-1.8 .7-3.8 1.1-5.8 1.1H30.7C13.8 512 0 498.2 0 481.3c0-75.5 51.9-138.9 121.9-156.4c8.1-2 15.9 3.3 17.9 11.3l36 146.9 33.4-123.9z"/></svg> <a href="https://avesis.hacettepe.edu.tr/katalay">Dr. Kübra Atalay Kabasakal</a></p>
<p><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:black;overflow:visible;position:relative;"><path d="M64 112c-8.8 0-16 7.2-16 16v22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1V128c0-8.8-7.2-16-16-16H64zM48 212.2V384c0 8.8 7.2 16 16 16H448c8.8 0 16-7.2 16-16V212.2L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z"/></svg> <a href="mailto:kkatalay@gmail.com" class="email">kkatalay@gmail.com</a></p>
<p><svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:1em;width:1em;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:black;overflow:visible;position:relative;"><path d="M64 112c-8.8 0-16 7.2-16 16v22.1L220.5 291.7c20.7 17 50.4 17 71.1 0L464 150.1V128c0-8.8-7.2-16-16-16H64zM48 212.2V384c0 8.8 7.2 16 16 16H448c8.8 0 16-7.2 16-16V212.2L322 328.8c-38.4 31.5-93.7 31.5-132 0L48 212.2zM0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z"/></svg> <a href="mailto:katalay@hacettepe.edu.tr" class="email">katalay@hacettepe.edu.tr</a></p>
</div>
<div id="kitaplar" class="section level2 unnumbered">
<h2 class="unnumbered">Kitaplar</h2>
<ul>
<li><p>Atar, B., Atalay Kabasakal, K, Unsal Ozberk, E. B., Ozberk, E. H. &amp; Kibrislioglu Uysal, N. (2020). R ile Veri Analizi ve Psikometri Uygulamaları, Pegem Akademi, Ankara.🔗 <a href="https://pegem.net/urun/R-ile-Veri-Analizi-ve-Psikometri-Uygulamalari/60801">📖</a></p></li>
<li><p>Desjardins, C. D., &amp; Bulut, O. (2018). Handbook of educational measurement and psychometrics using R. Boca Raton, FL: CRC Press. 🔗<a href="https://www.routledge.com/Handbook-of-Educational-Measurement-and-Psychometrics-Using-R/Desjardins-Bulut/p/book/9780367734671">📖</a></p></li>
<li><p>Demir, E. R Diliyle İstatistik Uygulamaları. Pegem Akademi, Ankara.(2021). 🔗<a href="https://pegem.net/urun/R-Diliyle-Istatistik-Uygulamalari/61912">📖</a></p></li>
<li><p>Kline,R. B. (2019). Yapısal Eşitlik Modellemesinin İlkeleri ve Uygulaması(4. Baskı). (S. Şen, Çev.) Ankara: Nobel Yayınevi.</p></li>
<li><p>Şen, S. (2020). Mplus ile Yapısal Eşitlik Modellemesi Uygulamaları (2020).Nobel Yayınevi.</p></li>
<li><p>Tabachnick, B. G., &amp; Fidell, L. S. (2012). Using Multivariate Statistics (4rd ed.). New York: Harper Collins.</p></li>
<li><p>Wolf, E. J., Harrington, K. M., Clark, S. L., &amp; Miller, M. W. (2013). Sample Size Requirements for Structural Equation Models: An Evaluation of Power, Bias, and Solution Propriety. Educational and Psychological Measurement, 73(6), 913–934. <a href="https://doi.org/10.1177/0013164413495237" class="uri">https://doi.org/10.1177/0013164413495237</a></p></li>
</ul>
<!--chapter:end:index.Rmd-->
</div>
</div>
<div id="varsayımlar-i" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Varsayımlar I</h1>
<ul>
<li><p>Veri Dosyasındaki Verinin Doğruluğu</p></li>
<li><p>Kayıp Verinin Miktarı ve Dağılımı</p></li>
<li><p>Tek Değişkenli ve Çok Değişkenli Uç Değerler (Outliers)</p></li>
<li><p>Sayıltılar</p></li>
<li><p>Çoklu Bağlantı (Multicollinearity) ve Tekillik (Singularity)</p></li>
</ul>
<div id="veri-inceleme" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Veri İnceleme</h2>
<ul>
<li><p>Varsayımlar incelenirken ilk olarak yanlış girilmiş bir değer olup
olmadığına bakılmalıdır.</p></li>
<li><p>Bu bölümde 🔗 <a href="import/SCREEN.SAV">SCREEN.SAV</a> adlı
veri seti kullanılmıştır. Bu veri setinde 20-59 yaşları arasında 465
kadının 6 değişkene ilişkin bilgileri bulunmaktadır. Değişkenlerden
timedrs, attdrug, atthouse ve income değişkenleri sürekli, mstatus
ve race değişkenleriyse iki kategorili değişkenlerdir. Bu veri seti
<strong>Tabachnick, B. G., &amp; Fidell, L. S. (2012). Using Multivariate
Statistics (4rd ed.). New York: Harper Collins.</strong> kitabının 4.
bölümünde kullanılmaktadır.</p></li>
<li><p>Veri incelemede birden fazla paket kullanılabilir. En temel
fonksiyon <code>base</code> paketin <code>summary()</code> fonksiyonudur. <code>psych</code>
paketinde <code>describe()</code> fonksiyonu da aynı amaçla kullanılabilir.</p></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>screen <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;import/SCREEN.sav&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">head</span>(screen)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">subno</th>
<th align="right">timedrs</th>
<th align="right">attdrug</th>
<th align="right">atthouse</th>
<th align="right">income</th>
<th align="right">mstatus</th>
<th align="right">race</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">8</td>
<td align="right">27</td>
<td align="right">5</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">3</td>
<td align="right">7</td>
<td align="right">20</td>
<td align="right">6</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">23</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">13</td>
<td align="right">9</td>
<td align="right">28</td>
<td align="right">8</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">15</td>
<td align="right">7</td>
<td align="right">24</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">25</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>Veri setindeki maksimum ve minumum değerleri belirlenmiştir.</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">summary</span>(screen)</span></code></pre></div>
<pre><code>##      subno          timedrs          attdrug          atthouse    
##  Min.   :  1.0   Min.   : 0.000   Min.   : 5.000   Min.   : 2.00  
##  1st Qu.:137.0   1st Qu.: 2.000   1st Qu.: 7.000   1st Qu.:21.00  
##  Median :314.0   Median : 4.000   Median : 8.000   Median :24.00  
##  Mean   :317.4   Mean   : 7.901   Mean   : 7.686   Mean   :23.54  
##  3rd Qu.:483.0   3rd Qu.:10.000   3rd Qu.: 9.000   3rd Qu.:27.00  
##  Max.   :758.0   Max.   :81.000   Max.   :10.000   Max.   :35.00  
##                                                    NA&#39;s   :1      
##      income         mstatus           race      
##  Min.   : 1.00   Min.   :1.000   Min.   :1.000  
##  1st Qu.: 2.50   1st Qu.:2.000   1st Qu.:1.000  
##  Median : 4.00   Median :2.000   Median :1.000  
##  Mean   : 4.21   Mean   :1.778   Mean   :1.088  
##  3rd Qu.: 6.00   3rd Qu.:2.000   3rd Qu.:1.000  
##  Max.   :10.00   Max.   :2.000   Max.   :2.000  
##  NA&#39;s   :26</code></pre>
<ul>
<li>Elde edilen değerlerin makul olduğu söylenebilir. Ancak bunu elde
etmek için başka yollar da bulunmaktadır. <code>psych</code> paketi ile
inceleme daha ayrıntılı yapılabilir.</li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">describe</span>(screen[,<span class="sc">-</span><span class="dv">1</span>]),<span class="dv">2</span>)</span></code></pre></div>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="10%" />
<col width="5%" />
<col width="4%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="9%" />
<col width="5%" />
<col width="4%" />
<col width="4%" />
<col width="7%" />
<col width="7%" />
<col width="10%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">vars</th>
<th align="right">n</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">median</th>
<th align="right">trimmed</th>
<th align="right">mad</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">range</th>
<th align="right">skew</th>
<th align="right">kurtosis</th>
<th align="right">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">timedrs</td>
<td align="right">1</td>
<td align="right">465</td>
<td align="right">7.90</td>
<td align="right">10.95</td>
<td align="right">4</td>
<td align="right">5.61</td>
<td align="right">4.45</td>
<td align="right">0</td>
<td align="right">81</td>
<td align="right">81</td>
<td align="right">3.23</td>
<td align="right">12.88</td>
<td align="right">0.51</td>
</tr>
<tr class="even">
<td align="left">attdrug</td>
<td align="right">2</td>
<td align="right">465</td>
<td align="right">7.69</td>
<td align="right">1.16</td>
<td align="right">8</td>
<td align="right">7.71</td>
<td align="right">1.48</td>
<td align="right">5</td>
<td align="right">10</td>
<td align="right">5</td>
<td align="right">-0.12</td>
<td align="right">-0.47</td>
<td align="right">0.05</td>
</tr>
<tr class="odd">
<td align="left">atthouse</td>
<td align="right">3</td>
<td align="right">464</td>
<td align="right">23.54</td>
<td align="right">4.48</td>
<td align="right">24</td>
<td align="right">23.62</td>
<td align="right">4.45</td>
<td align="right">2</td>
<td align="right">35</td>
<td align="right">33</td>
<td align="right">-0.45</td>
<td align="right">1.51</td>
<td align="right">0.21</td>
</tr>
<tr class="even">
<td align="left">income</td>
<td align="right">4</td>
<td align="right">439</td>
<td align="right">4.21</td>
<td align="right">2.42</td>
<td align="right">4</td>
<td align="right">4.01</td>
<td align="right">2.97</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">9</td>
<td align="right">0.58</td>
<td align="right">-0.38</td>
<td align="right">0.12</td>
</tr>
<tr class="odd">
<td align="left">mstatus</td>
<td align="right">5</td>
<td align="right">465</td>
<td align="right">1.78</td>
<td align="right">0.42</td>
<td align="right">2</td>
<td align="right">1.85</td>
<td align="right">0.00</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">-1.34</td>
<td align="right">-0.21</td>
<td align="right">0.02</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">6</td>
<td align="right">465</td>
<td align="right">1.09</td>
<td align="right">0.28</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="right">0.00</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">2.90</td>
<td align="right">6.40</td>
<td align="right">0.01</td>
</tr>
</tbody>
</table>
</div>
<p>🔗 <a href="https://personality-project.org/r/psych/">personality-project
sayfasını</a> daha fazla örnek
için inceleyebilirsiniz.</p>
<ul>
<li><code>gtsummary</code> paketi ile inceleme</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>screen <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>) <span class="sc">%&gt;%</span><span class="fu">tbl_summary</span>(<span class="at">statistic =</span> <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="fu">c</span>(</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a><span class="st">&quot;{min}, {max}&quot;</span>),<span class="at">missing =</span><span class="st">&quot;always&quot;</span>)</span></code></pre></div>
<div id="uypskvckdh" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#uypskvckdh table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#uypskvckdh thead, #uypskvckdh tbody, #uypskvckdh tfoot, #uypskvckdh tr, #uypskvckdh td, #uypskvckdh th {
  border-style: none;
}

#uypskvckdh p {
  margin: 0;
  padding: 0;
}

#uypskvckdh .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#uypskvckdh .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#uypskvckdh .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#uypskvckdh .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#uypskvckdh .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uypskvckdh .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uypskvckdh .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uypskvckdh .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#uypskvckdh .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#uypskvckdh .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#uypskvckdh .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#uypskvckdh .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#uypskvckdh .gt_spanner_row {
  border-bottom-style: hidden;
}

#uypskvckdh .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#uypskvckdh .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#uypskvckdh .gt_from_md > :first-child {
  margin-top: 0;
}

#uypskvckdh .gt_from_md > :last-child {
  margin-bottom: 0;
}

#uypskvckdh .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#uypskvckdh .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#uypskvckdh .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#uypskvckdh .gt_row_group_first td {
  border-top-width: 2px;
}

#uypskvckdh .gt_row_group_first th {
  border-top-width: 2px;
}

#uypskvckdh .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uypskvckdh .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#uypskvckdh .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#uypskvckdh .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uypskvckdh .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uypskvckdh .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#uypskvckdh .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#uypskvckdh .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#uypskvckdh .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uypskvckdh .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uypskvckdh .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uypskvckdh .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uypskvckdh .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uypskvckdh .gt_left {
  text-align: left;
}

#uypskvckdh .gt_center {
  text-align: center;
}

#uypskvckdh .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#uypskvckdh .gt_font_normal {
  font-weight: normal;
}

#uypskvckdh .gt_font_bold {
  font-weight: bold;
}

#uypskvckdh .gt_font_italic {
  font-style: italic;
}

#uypskvckdh .gt_super {
  font-size: 65%;
}

#uypskvckdh .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#uypskvckdh .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#uypskvckdh .gt_indent_1 {
  text-indent: 5px;
}

#uypskvckdh .gt_indent_2 {
  text-indent: 10px;
}

#uypskvckdh .gt_indent_3 {
  text-indent: 15px;
}

#uypskvckdh .gt_indent_4 {
  text-indent: 20px;
}

#uypskvckdh .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;N = 465&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>N = 465</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Visits to health professionals</td>
<td headers="stat_0" class="gt_row gt_center">0, 81</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">0</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Attitudes toward medication</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    5</td>
<td headers="stat_0" class="gt_row gt_center">13 (2.8%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    6</td>
<td headers="stat_0" class="gt_row gt_center">60 (13%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    7</td>
<td headers="stat_0" class="gt_row gt_center">126 (27%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    8</td>
<td headers="stat_0" class="gt_row gt_center">149 (32%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    9</td>
<td headers="stat_0" class="gt_row gt_center">95 (20%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    10</td>
<td headers="stat_0" class="gt_row gt_center">22 (4.7%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">0</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Attitudes toward housework</td>
<td headers="stat_0" class="gt_row gt_center">2.0, 35.0</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">1</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Income</td>
<td headers="stat_0" class="gt_row gt_center">1.00, 10.00</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">26</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Whether currently married</td>
<td headers="stat_0" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    1</td>
<td headers="stat_0" class="gt_row gt_center">103 (22%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    2</td>
<td headers="stat_0" class="gt_row gt_center">362 (78%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    Unknown</td>
<td headers="stat_0" class="gt_row gt_center">0</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="2"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> Range; n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
<ul>
<li><p>🔗[Presentation-Ready Summary Tables] with
gtsummary(<a href="https://education.rstudio.com/blog/2020/07/gtsummary" class="uri">https://education.rstudio.com/blog/2020/07/gtsummary</a>)</p></li>
<li><p><code>vtable</code> paketi ile inceleme</p></li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">library</span>(vtable)</span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a><span class="fu">sumtable</span>(screen, <span class="at">summ=</span><span class="fu">c</span>(<span class="st">&#39;notNA(x)&#39;</span>,<span class="st">&#39;min(x)&#39;</span>,<span class="st">&#39;max(x)&#39;</span>))</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:unnamed-chunk-5)Summary Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
NotNA
</th>
<th style="text-align:left;">
Min
</th>
<th style="text-align:left;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
subno
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
758
</td>
</tr>
<tr>
<td style="text-align:left;">
timedrs
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
81
</td>
</tr>
<tr>
<td style="text-align:left;">
attdrug
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
atthouse
</td>
<td style="text-align:left;">
464
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
income
</td>
<td style="text-align:left;">
439
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
mstatus
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
race
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
</tbody>
</table>
<ul>
<li><p>🔗 <a href="https://nickch-k.github.io/vtable/index.html">vtable paketi için
örnekler</a></p></li>
<li><p>sütun isimleri aşağıdaki gibi değiştirilebilir.</p></li>
</ul>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">sumtable</span>(screen, <span class="at">summ =</span> <span class="fu">c</span>(<span class="st">&#39;notNA(x)&#39;</span>,<span class="st">&#39;min(x)&#39;</span>,<span class="st">&#39;max(x)&#39;</span>),</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>         <span class="at">summ.names =</span> <span class="fu">c</span>(<span class="st">&#39;Frekans&#39;</span></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>,<span class="st">&#39;Minimum&#39;</span>,<span class="st">&#39;Maksimum&#39;</span>))</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:unnamed-chunk-6)Summary Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Frekans
</th>
<th style="text-align:left;">
Minimum
</th>
<th style="text-align:left;">
Maksimum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
subno
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
758
</td>
</tr>
<tr>
<td style="text-align:left;">
timedrs
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
81
</td>
</tr>
<tr>
<td style="text-align:left;">
attdrug
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
atthouse
</td>
<td style="text-align:left;">
464
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
income
</td>
<td style="text-align:left;">
439
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
mstatus
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
race
</td>
<td style="text-align:left;">
465
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
</tr>
</tbody>
</table>
<ul>
<li><code>kable</code> paketi ile <code>psych</code> paketi çıktılarını düzenleme</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>ozet <span class="ot">&lt;-</span> <span class="fu">describe</span>(screen[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a><span class="fu">kable</span>(ozet,<span class="at">format=</span><span class="st">&#39;markdown&#39;</span>,</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Betimsel İstatistikler&quot;</span>,<span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<table style="width:100%;">
<caption>(#tab:unnamed-chunk-7)Betimsel İstatistikler</caption>
<colgroup>
<col width="10%" />
<col width="5%" />
<col width="4%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="9%" />
<col width="5%" />
<col width="4%" />
<col width="4%" />
<col width="7%" />
<col width="7%" />
<col width="10%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">vars</th>
<th align="right">n</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">median</th>
<th align="right">trimmed</th>
<th align="right">mad</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">range</th>
<th align="right">skew</th>
<th align="right">kurtosis</th>
<th align="right">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">timedrs</td>
<td align="right">1</td>
<td align="right">465</td>
<td align="right">7.90</td>
<td align="right">10.95</td>
<td align="right">4</td>
<td align="right">5.61</td>
<td align="right">4.45</td>
<td align="right">0</td>
<td align="right">81</td>
<td align="right">81</td>
<td align="right">3.23</td>
<td align="right">12.88</td>
<td align="right">0.51</td>
</tr>
<tr class="even">
<td align="left">attdrug</td>
<td align="right">2</td>
<td align="right">465</td>
<td align="right">7.69</td>
<td align="right">1.16</td>
<td align="right">8</td>
<td align="right">7.71</td>
<td align="right">1.48</td>
<td align="right">5</td>
<td align="right">10</td>
<td align="right">5</td>
<td align="right">-0.12</td>
<td align="right">-0.47</td>
<td align="right">0.05</td>
</tr>
<tr class="odd">
<td align="left">atthouse</td>
<td align="right">3</td>
<td align="right">464</td>
<td align="right">23.54</td>
<td align="right">4.48</td>
<td align="right">24</td>
<td align="right">23.62</td>
<td align="right">4.45</td>
<td align="right">2</td>
<td align="right">35</td>
<td align="right">33</td>
<td align="right">-0.45</td>
<td align="right">1.51</td>
<td align="right">0.21</td>
</tr>
<tr class="even">
<td align="left">income</td>
<td align="right">4</td>
<td align="right">439</td>
<td align="right">4.21</td>
<td align="right">2.42</td>
<td align="right">4</td>
<td align="right">4.01</td>
<td align="right">2.97</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">9</td>
<td align="right">0.58</td>
<td align="right">-0.38</td>
<td align="right">0.12</td>
</tr>
<tr class="odd">
<td align="left">mstatus</td>
<td align="right">5</td>
<td align="right">465</td>
<td align="right">1.78</td>
<td align="right">0.42</td>
<td align="right">2</td>
<td align="right">1.85</td>
<td align="right">0.00</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">-1.34</td>
<td align="right">-0.21</td>
<td align="right">0.02</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">6</td>
<td align="right">465</td>
<td align="right">1.09</td>
<td align="right">0.28</td>
<td align="right">1</td>
<td align="right">1.00</td>
<td align="right">0.00</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">2.90</td>
<td align="right">6.40</td>
<td align="right">0.01</td>
</tr>
</tbody>
</table>
<ul>
<li>🔗
<a href="https://bookdown.org/yihui/rmarkdown-cookbook/kable.html">rmarkdown-cookbook</a></li>
</ul>
</div>
<div id="kayıp-değerler" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Kayıp Değerler</h2>
<ul>
<li><p>Kayıp veri, veri analizindeki en yaygın problemlerden biridir.</p></li>
<li><p>Kayıp verinin önemi kayıp verinin miktarına, örüntüsüne ve neden
eksik olduğuna bağlıdır.</p></li>
<li><p>Bir değişkene ait beklenmeyen miktarda kayıp veri varsa, ilk olarak
bunun nedeni araştırılmalıdır. Daha sonra kayıp verinin örüntüsüne
bakılarak, rastlantısal mı yoksa sistematik bir örüntü mü gösterdiği
belirlenmelidir.</p>
<ul>
<li>Örneğin, 30 yaşın üstündeki birçok kadın yaş ile ilgili soruyu
cevaplamak istemezler.</li>
</ul></li>
<li><p>Genellikle kayıp verinin örüntüsü miktarından daha önemlidir.
Rastlantısal dağılmayan kayıp veriler sonuçların
genellenebilirliğini etkileyeceğinden miktarları az da olsa,
rastlantısal dağılan kayıp verilere oranla daha ciddi problemlere
yol açarlar.</p></li>
</ul>
<div id="kayıp-veri-türleri" class="section level3" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> Kayıp Veri Türleri</h3>
<ul>
<li><p>Kayıp veri türleri arasındaki ayrım 1976 yılında Rubin tarafından
yapılmıştır. Rubin (1976) kayıp veriyi aşağıdaki şekilde
sınıflandırmıştır.</p>
<ul>
<li><p>Tamamen Rastgele Olarak Kayıp (TRK) - Missing Completely at
Random MCAR</p></li>
<li><p>Rastgele Kayıp (RK) - Missing at Random (MAR)</p></li>
<li><p>Rastgele Olmayan Kayıp / İhmal Edilemez Kayıp (ROK) - Not
Missing at Random (NMAR)</p></li>
</ul></li>
<li><p>Kayıp veri en azından MAR türünde değilse, kayıp verinin ihmal
edilemeyeceği söylenir. Bu türdeki kayıp veri rastlantısal olamyan
kayıp veya ihmal edilemez kayıp olarak adlandırılır.</p></li>
<li><p>Büyük bir veri setinde, verinin %5’i veya daha azı rastlantısal
olarak kayıpsa çok ciddi problemlerle karşılaşılmaz ve kayıp veri
ile ilgili problemleri çözmek için kullanılan herhangi bir yöntem
benzer sonuçlar verir. Halbuki küçük veya orta büyüklükteki bir veri
setinde çok sayıda veri kaybı varsa ciddi problemler ortaya
çıkabilir.</p></li>
<li><p>Eldeki bilgiden yararlanarak kayıp verideki örüntüler test
edilebilir.</p></li>
</ul>
</div>
<div id="trk" class="section level3" number="1.2.2">
<h3><span class="header-section-number">1.2.2</span> TRK</h3>
<ul>
<li><p>Bir Y değişkeninde kayıp veri bulunma olasılığının, Y değişkeninin
kendi değerleriyle ve veri setindeki diğer değişkenlerin
değerleriyle <strong>ilişkisiz olması durumunda Y değişkenindeki verinin
tamamen rastgele kayıp (TRK) olduğu söylenir (Allison, 2002).</strong></p></li>
<li><p>Örneğin; bir ilkokulda okuma başarısı üzerine yürütülen bir
boylamsal araştırmada çocuklar hastalık ya da ailede ölüm gibi
tesadüfi bir sebepten değerlendirmeye katılmadığında veri TRK olarak
adlandırılır. Ayrıca bu faktörlerin sosyoekonomik düzey gibi ölçülen
diğer değişkenle ilişkisi olmadığı varsayıldığında, araştırmacı
tarafından elde edilen veriler hipotetik bir tam veri setinin
rastgele bir örneklemini temsil eder (Peugh ve Enders, 2004).</p></li>
</ul>
</div>
<div id="rastgele-kayıp-rk" class="section level3" number="1.2.3">
<h3><span class="header-section-number">1.2.3</span> Rastgele kayıp (RK)</h3>
<ul>
<li><p>Bir Y değişkenindeki kayıp veri bulunma olasılığının, analiz
modelindeki diğer değişkenlerin bazılarıyla ilişkili olduğunu ancak
Y değişkeninin kendi değerleriyle ilişkili olmadığını ifade eder.</p></li>
<li><p>Örneğin, kanser hastalarıyla yaşam kalitesi üzerine çalışma yapan
bir psikologun yaşlı ve eğitim düzeyi düşük hastaların yaşam
kalitesi anketini reddetme eğiliminin daha yüksek olduğu sonucuna
ulaştığını düşünelim. Bu durumda kayıp veriye eğilimin, kayıp veri
bulunan değişkenle arasında artık ilişki yoksa verinin RK olduğu
söylenir. Başka bir ifadeyle, RK yaş ve eğitim kontrol edildiğinde
kayıp veri olasılığının yaşam kalitesiyle arasında ilişki olmaması
durumudur (Enders, 2010). Kayıp veri olasılığı yalnızca diğer
gözlenen değişkenlerin değerlerine bağlı olduğunda veri RK’dır
(Robitzsch ve Rupp, 2009).</p></li>
<li><p>RK türünde veri gerçekte rastlantısal olarak kayıp değildir, veri
kaybı veri setindeki değişkenlerden bazılarına bağlıdır.
Rastlantısal olarak kayıp değerler ve gözlenen değerler arasında
sistematik farklılıkların olabileceği ancak bu farklılıkların diğer
gözlenen değişkenlerle tamamen açıklanabileceği anlamındadır.</p></li>
<li><p>Bir değişkenin gözlemleri rastlantısal olarak kayıpsa, şartlı
değişkenler kontrol edilebilirse , rastlantısal küme elde
edilebilir; kayıp ve gözlenen değerler kontrol altına alınan
gruplarda benzer dağılımlara sahip olacaklardır.</p></li>
<li><p>Örneğin, kayıp verinin bulunduğu değişkene göre eksik değerlere
sahip bireyler ve tam değerlere sahip bireylerden iki grup
oluşturulabilir. Sonra analizde bu değişkenle ilgili olabilecek
diğer değişkenlerde t testi ile iki grup arasındaki ortalama
farklara bakılabilir.</p></li>
</ul>
</div>
<div id="rastgele-olmayan-kayıp" class="section level3" number="1.2.4">
<h3><span class="header-section-number">1.2.4</span> Rastgele Olmayan Kayıp</h3>
<ul>
<li>Rastgele olmayan kayıp (ROK), bir Y değişkenindeki kayıp veri
bulunma olasılığının diğer değişkenler kontrol edildiğinde bile Y
değişkeninin değerleriyle ilişkili olması durumunda meydana gelir.
Örneğin, okuma becerileri zayıf olan öğrencilerin okuma testinde
anlama güçlüğü çekerek soruları atlaması kaçınılmaz olacaktır. Bu
durumda okuma değerlendirmesi okuma başarısıyla doğrudan ilişkilidir
(Enders, 2010; Peugh ve Enders, 2004).</li>
</ul>
</div>
</div>
<div id="kayıp-veri-atama-yöntemleri" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Kayıp Veri Atama Yöntemleri</h2>
<ul>
<li><p>Kayıp veriyle baş etme yöntemleri</p>
<ul>
<li><p>veri silmeye dayalı yöntemler (liste baznda - çiftler bazında)</p></li>
<li><p>Veri atamaya dayalı yöntemler</p></li>
<li><p>Model tabanlı yöntemler</p></li>
</ul></li>
<li><p>Veri silmeye dayalı yöntemler TRK veri mekanizmasını
gerektirmektedir ve bu varsayım sağlanmadığında yanlış parametre
kestirimleri verebilir. MCAR varsayımı sağlandığında bile verinin
silinmesi analizin gücünün düşmesine neden olabilmektedir (Enders,
2010).</p></li>
</ul>
<div id="veri-silmeye-dayalı-yöntemler" class="section level3" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Veri Silmeye Dayalı Yöntemler</h3>
<table>
<thead>
<tr class="header">
<th>Gözlem</th>
<th>Y1</th>
<th>Y2</th>
<th>Y3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>13</td>
<td>23</td>
<td>21</td>
</tr>
<tr class="even">
<td>2</td>
<td>14</td>
<td>22</td>
<td>17</td>
</tr>
<tr class="odd">
<td>3</td>
<td>15</td>
<td>-</td>
<td>11</td>
</tr>
<tr class="even">
<td>4</td>
<td>16</td>
<td>18</td>
<td>-</td>
</tr>
<tr class="odd">
<td>5</td>
<td>17</td>
<td>17</td>
<td>12</td>
</tr>
<tr class="even">
<td>6</td>
<td>-</td>
<td>20</td>
<td>8</td>
</tr>
<tr class="odd">
<td>7</td>
<td>-</td>
<td>20</td>
<td>15</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Liste bazında veri silme yöntemi uygulandığında veri kümesinde
sadece birinci,
ikinci ve beşinci gözlemler üzerinden istatistiksel çözümlemeler
yapılacaktır.
Üçüncü, dördüncü, altıncı ve yedinci gözlemler kayıp veri
bulundurduklarından
çözümleme dışında bırakılmıştır.</p></li>
<li><p>çiftler bazında veri silme ile ele alındığında birinci ve ikinci
değişken için birinci, ikinci, dördüncü ve beşinci gözlemler
üzerinden işlem yapılacaktır. Birinci ve üçüncü değişken için yapılacak
kestirimler,
birinci, ikinci, üçüncü ve beşinci gözlemler üzerinden yapılacaktır.
İkinci ve üçüncü değişkenler baz alındığında ise üçüncü ve dördüncü gözlem hariç diğer gözlemler üzerinden çözümlemeler yapılacaktır. Yapılan işlemler dikkate
alındığında ilk altküme için dört gözlem çifti, ikinci altküme için
dört gözlem çifti ve üçüncü altküme için beş gözlem çifti üzerinden
çözümlemeler yapılarak birleştirilecektir.
Görüldüğü gibi altkümelerin gözlem sayıları birbirlerinden farklı
olabilmektedir. Liste bazında veri silme yönteminde gözlenmesine
rağmen çözümleme dışında kalan değerlerden oluşan bilgi kaybı, çiftler
bazında veri silme yöntemi ile azaltılmıştır. Her değişkenin farklı
örneklem sayısı bulundurmasının ANOVA ve regresyon çözümlemesi gibi yöntemlerin kullanılacağı durumlarda problemli olduğunu belirtilmiştir.</p></li>
</ul>
</div>
<div id="veri-atamaya-dayalı-yöntemler" class="section level3" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Veri atamaya dayalı yöntemler</h3>
<ul>
<li>Ortalama veri atama</li>
<li>Regresyon İle veri atama</li>
<li>Deck/Deste ile Veri Yükleme</li>
<li>En Yakın Komşu Yöntemi</li>
<li>Son Gözlemi İleri Taşıma</li>
</ul>
</div>
<div id="model-tabanlı-yöntemler" class="section level3" number="1.3.3">
<h3><span class="header-section-number">1.3.3</span> Model tabanlı yöntemler</h3>
<ul>
<li><p>Gözlenmiş değerler üzerinden kurulan bir modelde olabilirlik ve sonsal dağılımlara
bağlı olarak parametrelerin kestirilmesine dayanan kayıp veri yöntemleridir. Bu
yöntemlerin en önemli getirisi esneklikleridir. Geçici yöntemlerden kaçınarak model
varsayımları altında çözümleme yaparlar. Ayrıca veri matrisinde gözlenememiş
değerleri de hesaba katarak varyans kestirimleri verirler.</p></li>
<li><p>ML Yöntemi</p></li>
<li><p>EM Algoritması</p></li>
<li><p>Çoklu Veri Atama</p></li>
</ul>
</div>
<div id="kayıp-veri-analizinde-kullanılan-paketler" class="section level3" number="1.3.4">
<h3><span class="header-section-number">1.3.4</span> Kayıp Veri Analizinde Kullanılan Paketler</h3>
<ul>
<li>Kayıp veriyi incelemek ve kayıp veri ile baş etmek konusunda birden
fazla paket mevcuttur. Bu paketler arasında
<ul>
<li>VIM</li>
<li>missMethods</li>
<li>Amelia</li>
<li>naniar paketi sayılabilir.</li>
</ul></li>
</ul>
<p>İlk örnekler <strong>naniar</strong> üzerinden gösterilmektedir.</p>
<ul>
<li><strong>herhangi bir eksik veri olup olmadığının kontrolü</strong></li>
</ul>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a><span class="fu">any_na</span>(screen)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<ul>
<li><strong>toplam kaç eksik veri var</strong></li>
</ul>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">n_miss</span>(screen)</span></code></pre></div>
<pre><code>## [1] 27</code></pre>
<ul>
<li><strong>eksik veri oranı ne?</strong></li>
</ul>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">prop_miss</span>(screen)</span></code></pre></div>
<pre><code>## [1] 0.008294931</code></pre>
<ul>
<li><strong>eksik veriler hangi sütunlarda</strong></li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>screen <span class="sc">%&gt;%</span> <span class="fu">is.na</span>() <span class="sc">%&gt;%</span> <span class="fu">colSums</span>()</span></code></pre></div>
<pre><code>##    subno  timedrs  attdrug atthouse   income  mstatus     race 
##        0        0        0        1       26        0        0</code></pre>
<ul>
<li><strong>eksik veri tablosu, frekans ve oran</strong></li>
</ul>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">miss_var_summary</span>(screen)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">n_miss</th>
<th align="right">pct_miss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">income</td>
<td align="right">26</td>
<td align="right">5.5913978</td>
</tr>
<tr class="even">
<td align="left">atthouse</td>
<td align="right">1</td>
<td align="right">0.2150538</td>
</tr>
<tr class="odd">
<td align="left">subno</td>
<td align="right">0</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">timedrs</td>
<td align="right">0</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">attdrug</td>
<td align="right">0</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">mstatus</td>
<td align="right">0</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">race</td>
<td align="right">0</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><strong>değişkenlere göre eksik veri tablosu</strong></li>
</ul>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">miss_var_table</span>(screen)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">n_miss_in_var</th>
<th align="right">n_vars</th>
<th align="right">pct_vars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">5</td>
<td align="right">71.42857</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
<tr class="odd">
<td align="right">26</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><strong>Hangi bireylerde/satırlarda eksik veri var</strong></li>
</ul>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">miss_case_summary</span>(screen))</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">case</th>
<th align="right">n_miss</th>
<th align="right">pct_miss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">52</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
<tr class="even">
<td align="right">64</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
<tr class="odd">
<td align="right">69</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
<tr class="even">
<td align="right">77</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
<tr class="odd">
<td align="right">118</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
<tr class="even">
<td align="right">135</td>
<td align="right">1</td>
<td align="right">14.28571</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><strong>tam ve eksik veri tablosu</strong></li>
</ul>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">miss_case_table</span>(screen)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">n_miss_in_case</th>
<th align="right">n_cases</th>
<th align="right">pct_cases</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">438</td>
<td align="right">94.193548</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">27</td>
<td align="right">5.806452</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><strong>Eksik verinin görselleştirilmesi</strong></li>
</ul>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">gg_miss_var</span>(screen)</span></code></pre></div>
<p><img src="01-Varsayimlar_files/figure-html/unnamed-chunk-16-1.png" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li><strong>Eksik verinin görselleştirilmesi</strong></li>
</ul>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a><span class="fu">vis_miss</span>(screen) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle=</span><span class="dv">80</span>))</span></code></pre></div>
<p><img src="01-Varsayimlar_files/figure-html/unnamed-chunk-17-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">gg_miss_upset</span>(screen)</span></code></pre></div>
<pre><code>## `geom_line()`: Each group consists of only one observation.
## ℹ Do you need to adjust the group aesthetic?</code></pre>
<p><img src="01-Varsayimlar_files/figure-html/unnamed-chunk-17-2.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="kayıp-veri-testi" class="section level3" number="1.3.5">
<h3><span class="header-section-number">1.3.5</span> Kayıp Veri Testi</h3>
<p>Veri kaybının diğer değişkenlerle ilişkili olup olmadığının incelenmesi
<code>finalfit</code> paketi ile gerçekleştirilebilir.</p>
<ul>
<li>income değişleninde eksik veriler diğer değişkenlerle ilişkili mi?</li>
</ul>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="co"># değişkeni kopyala</span></span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a>screen2 <span class="ot">&lt;-</span> screen</span>
<span id="cb28-3"><a href="#cb28-3" tabindex="-1"></a>screen2<span class="sc">$</span>income_m <span class="ot">&lt;-</span> screen2<span class="sc">$</span>income</span>
<span id="cb28-4"><a href="#cb28-4" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" tabindex="-1"></a><span class="fu">library</span>(finalfit)</span>
<span id="cb28-6"><a href="#cb28-6" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" tabindex="-1"></a>explanatory <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;timedrs&quot;</span>, <span class="st">&quot;attdrug&quot;</span>, <span class="st">&quot;atthouse&quot;</span>)</span>
<span id="cb28-8"><a href="#cb28-8" tabindex="-1"></a>dependent <span class="ot">=</span> <span class="st">&quot;income_m&quot;</span></span>
<span id="cb28-9"><a href="#cb28-9" tabindex="-1"></a>screen2 <span class="sc">%&gt;%</span> </span>
<span id="cb28-10"><a href="#cb28-10" tabindex="-1"></a>  <span class="fu">missing_compare</span>(dependent, explanatory) <span class="sc">%&gt;%</span> </span>
<span id="cb28-11"><a href="#cb28-11" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">row.names=</span><span class="cn">FALSE</span>, <span class="at">align =</span> <span class="fu">c</span>(<span class="st">&quot;l&quot;</span>, <span class="st">&quot;l&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;r&quot;</span>, <span class="st">&quot;r&quot;</span>), </span>
<span id="cb28-12"><a href="#cb28-12" tabindex="-1"></a>        <span class="at">caption =</span> <span class="st">&quot;Eksik veriye sahip olan ve olmayan değişkenlerin ortalama karşılaştırması&quot;</span>) </span></code></pre></div>
<table>
<caption>(#tab:unnamed-chunk-18)Eksik veriye sahip olan ve olmayan değişkenlerin ortalama karşılaştırması</caption>
<colgroup>
<col width="44%" />
<col width="14%" />
<col width="17%" />
<col width="15%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Missing data analysis: Income</th>
<th align="left"></th>
<th align="right">Not missing</th>
<th align="right">Missing</th>
<th align="right">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Visits to health professionals</td>
<td align="left">Mean (SD)</td>
<td align="right">7.9 (11.1)</td>
<td align="right">7.6 (7.4)</td>
<td align="right">0.891</td>
</tr>
<tr class="even">
<td align="left">Attitudes toward medication</td>
<td align="left">Mean (SD)</td>
<td align="right">7.7 (1.2)</td>
<td align="right">7.9 (1.0)</td>
<td align="right">0.368</td>
</tr>
<tr class="odd">
<td align="left">Attitudes toward housework</td>
<td align="left">Mean (SD)</td>
<td align="right">23.5 (4.5)</td>
<td align="right">23.7 (4.2)</td>
<td align="right">0.860</td>
</tr>
</tbody>
</table>
<div id="bir-değişkenin-kategorilerinde-inceleme" class="section level4" number="1.3.5.1">
<h4><span class="header-section-number">1.3.5.1</span> Bir değişkenin kategorilerinde inceleme</h4>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>miss_test <span class="ot">&lt;-</span> screen2 <span class="sc">%&gt;%</span><span class="fu">mutate</span>(<span class="at">miss_income =</span> <span class="fu">is.na</span>(income))</span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a>  </span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a><span class="co"># evli olmayanlar için</span></span>
<span id="cb29-5"><a href="#cb29-5" tabindex="-1"></a>notmarried <span class="ot">&lt;-</span> miss_test <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mstatus <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" tabindex="-1"></a>   <span class="fu">pull</span>(miss_income)</span>
<span id="cb29-7"><a href="#cb29-7" tabindex="-1"></a>  </span>
<span id="cb29-8"><a href="#cb29-8" tabindex="-1"></a><span class="co"># Evliler için</span></span>
<span id="cb29-9"><a href="#cb29-9" tabindex="-1"></a>married <span class="ot">&lt;-</span> miss_test <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mstatus <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(miss_income)</span>
<span id="cb29-10"><a href="#cb29-10" tabindex="-1"></a>  </span>
<span id="cb29-11"><a href="#cb29-11" tabindex="-1"></a><span class="co">#c Oran</span></span>
<span id="cb29-12"><a href="#cb29-12" tabindex="-1"></a><span class="fu">t.test</span>(notmarried, married)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  notmarried and married
## t = -0.95833, df = 198.7, p-value = 0.3391
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.06708191  0.02320485
## sample estimates:
##  mean of x  mean of y 
## 0.03883495 0.06077348</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="fu">gg_miss_fct</span>(screen, <span class="at">fct =</span> mstatus)</span></code></pre></div>
<p><img src="01-Varsayimlar_files/figure-html/unnamed-chunk-20-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="mcar-test" class="section level3" number="1.3.6">
<h3><span class="header-section-number">1.3.6</span> MCAR test</h3>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a><span class="fu">mcar_test</span>(<span class="at">data=</span>screen[,<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p.value</th>
<th align="right">missing.patterns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">3.286262</td>
<td align="right">6</td>
<td align="right">0.7721547</td>
<td align="right">3</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>Littleın MCAR testine ilişkin p değerinin . 773 olduğu
görülmektedir. Böylece kayıp verinin MCAR olduğu sonucuna
varılabilir.</li>
</ul>
</div>
<div id="kayıp-veri-ile-başetme" class="section level3" number="1.3.7">
<h3><span class="header-section-number">1.3.7</span> Kayıp veri ile başetme</h3>
<ul>
<li>Liste bazında silme işlemi <strong>na.omit</strong> ve <strong>complete.cases</strong>
fonkisyonları ile sağlanabilir.</li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="fu">na.omit</span>(screen) </span>
<span id="cb33-2"><a href="#cb33-2" tabindex="-1"></a>screen[<span class="sc">!</span><span class="fu">complete.cases</span>(screen),]</span>
<span id="cb33-3"><a href="#cb33-3" tabindex="-1"></a>screen[<span class="fu">complete.cases</span>(screen),]</span></code></pre></div>
<ul>
<li>Ortalama atama işlemi yapılabir. Tek bir değişkene ortalama atama</li>
</ul>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="fu">rep</span>(<span class="cn">NA</span>,<span class="dv">10</span>)))</span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>df<span class="sc">$</span>y[<span class="fu">is.na</span>(df<span class="sc">$</span>y)] <span class="ot">=</span> <span class="fu">mean</span>(df<span class="sc">$</span>y, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>screen2 <span class="ot">&lt;-</span> screen</span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a>screen2<span class="sc">$</span>income[<span class="fu">is.na</span>(screen2<span class="sc">$</span>income)]<span class="ot">&lt;-</span> <span class="fu">mean</span>(screen2<span class="sc">$</span>income, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<ul>
<li><strong>if_else()</strong> ile ortalama atama işlemi yapılabir.</li>
</ul>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a>screen3 <span class="ot">&lt;-</span> screen</span>
<span id="cb36-2"><a href="#cb36-2" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" tabindex="-1"></a>screen3 <span class="ot">=</span> <span class="fu">transform</span>(screen3, <span class="at">income =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(income), </span>
<span id="cb36-4"><a href="#cb36-4" tabindex="-1"></a>                                        <span class="fu">mean</span>(income, <span class="at">na.rm=</span><span class="cn">TRUE</span>), income))</span>
<span id="cb36-5"><a href="#cb36-5" tabindex="-1"></a><span class="fu">summary</span>(screen3<span class="sc">$</span>income)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    3.00    4.00    4.21    6.00   10.00</code></pre>
<ul>
<li><code>mutate()</code> ile ortalama atama işlemi yapılabilir</li>
</ul>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a>screen <span class="sc">%&gt;%</span>  </span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">income =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(income), <span class="fu">mean</span>(income, <span class="at">na.rm =</span><span class="cn">TRUE</span>), income))</span></code></pre></div>
</div>
<div id="veri-setindeki-kayıp-veriler" class="section level3" number="1.3.8">
<h3><span class="header-section-number">1.3.8</span> Veri setindeki kayıp veriler</h3>
<ul>
<li><p><strong>atthouse</strong> değişkeninde bir kayıp değer bulunmaktadır ve liste
bazında silme yöntemi ile veri setinden çıkarılmıştır.</p></li>
<li><p>Veri setinde <strong>income</strong> değişkeni 26 kayıp değere sahiptir ve bu
sayı örneklemin %5’inden fazladır. Eğer bu değişken araştırma
açısından öneme sahip değilse, veri setinden çıkarılabilir, aksi
halde kayıp verinin tahmin edilmesi yöntemlerinden biri
kullanılabilir.</p></li>
<li><p>income değişkenindeki kayıp değerler için kayıp verinin tahmin
edilmesi yöntemlerinden ortalamanın yerleştirilmesi kullanılarak
kayıp değer yerine değişkenin ortalama değeri (4.21 değeri)
yerleştirilmiştir.</p></li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>screen <span class="ot">&lt;-</span> screen <span class="sc">%&gt;%</span> </span>
<span id="cb39-2"><a href="#cb39-2" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">income =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(income), <span class="fu">mean</span>(income, <span class="at">na.rm =</span><span class="cn">TRUE</span>),</span>
<span id="cb39-3"><a href="#cb39-3" tabindex="-1"></a>                       income)) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span>
<span id="cb39-4"><a href="#cb39-4" tabindex="-1"></a><span class="fu">summary</span>(screen)</span></code></pre></div>
<pre><code>##      subno          timedrs          attdrug         atthouse    
##  Min.   :  1.0   Min.   : 0.000   Min.   : 5.00   Min.   : 2.00  
##  1st Qu.:136.8   1st Qu.: 2.000   1st Qu.: 7.00   1st Qu.:21.00  
##  Median :313.5   Median : 4.000   Median : 8.00   Median :24.00  
##  Mean   :317.3   Mean   : 7.914   Mean   : 7.69   Mean   :23.54  
##  3rd Qu.:483.2   3rd Qu.:10.000   3rd Qu.: 9.00   3rd Qu.:27.00  
##  Max.   :758.0   Max.   :81.000   Max.   :10.00   Max.   :35.00  
##      income          mstatus          race      
##  Min.   : 1.000   Min.   :1.00   Min.   :1.000  
##  1st Qu.: 3.000   1st Qu.:2.00   1st Qu.:1.000  
##  Median : 4.000   Median :2.00   Median :1.000  
##  Mean   : 4.208   Mean   :1.78   Mean   :1.086  
##  3rd Qu.: 6.000   3rd Qu.:2.00   3rd Qu.:1.000  
##  Max.   :10.000   Max.   :2.00   Max.   :2.000</code></pre>
<ul>
<li>daha fazla bilgi için
<a href="https://bookdown.org/mwheymans/bookmi/missing-data-evaluation.html" class="uri">https://bookdown.org/mwheymans/bookmi/missing-data-evaluation.html</a></li>
</ul>
</div>
</div>
<div id="daha-fazlası-için" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Daha Fazlası için</h2>
<ul>
<li><p><a href="https://cran.r-project.org/web/packages/naniar/vignettes/getting-started-w-naniar.html">naniar paketi vigneti</a></p></li>
<li><p>Stef van Buuren "Flexible Imputation of Missing Data" kitabına <a href="Shttps://stefvanbuuren.name/fimd/">linkten
erişebilirsiniz.</a></p></li>
</ul>
</div>
<div id="kaynaklar" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Kaynaklar</h2>
<ul>
<li><p>Allison, P. D. (2003). Missing Data Techniques for Structural Equation Modeling.
Journal of Abnormal Psychology. 112(4), 545-557.</p></li>
<li><p>Peugh, J.L. &amp; Enders, J.K. (2004). Missing Data in Educational Research: A Review of
Reporting Practices and Suggestions for İmprovement. Review of
EducationalResearch, 74(4), 525-556, DOI: 10.3102/00346543074004525
Peugh ve Enders, 2004</p></li>
<li><p>Rubin, D. B. (1976). Inference with missing data. Biometrika , 63, 581</p></li>
</ul>
<ol start="592" style="list-style-type: decimal">
<li></li>
</ol>
<ul>
<li>Robitzsch ve Rupp, 2009</li>
</ul>
<!--chapter:end:01-Varsayimlar.Rmd-->
</div>
</div>
<div id="varsayımlar-ii" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Varsayımlar II</h1>
<div id="uç-değerler" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Uç değerler</h2>
<ul>
<li><p>Uç değerler hem I. tip hem de II. tip hatalara neden olurlar ve
sonuçların genellenebilirliğini düşürürler.</p></li>
<li><p>Veri setinde uç değer bulunmasının 4 nedeni olabilir:</p>
<ul>
<li>Verinin veri dosyasına yanlış girilmesi</li>
<li>Kayıp veri kodlamasında hata yapılması</li>
<li>Uç değerin örneklemin alındığı evrenin üyesi olmaması</li>
<li>Uç değerin örneklemin alındığı evrenin üyesi olması ancak
değişkenin evrendeki dağılımının normal dağılıma göre aşırı
değerlere sahip olması</li>
</ul></li>
<li><p>Hatalı veri girişi ve kayıp değer kodlaması kolaylıkla
bulunup düzeltilebilir ancak 3. ve 4. durumlar arasında
ayrım yapıp uç değerin veri setinden silinip
silinmemesine karar vermek oldukça güçtür.</p></li>
<li><p>Tek değişkenli uç değerlerin belirlenmesi çok değişkenli
uç değerlerin belirlenmesine göre daha kolaydır.</p></li>
<li><p>İki kategorili değişkenler için, eşit büyüklükte olmayan
kategorilerde yanlış kategoride gözlenen bir değer olasılıkla uç
değerdir. Rummel (1970) iki kategorili bir değişken için kategorilerden biri
örneklemdeki bireylerin %90’ını diğeri ise %10’unu içeriyorsa,
değişkenin analiz dışı bırakılmasını önermektedir.</p></li>
</ul>
<div id="iki-kategorili-değişkenlerde-uç-değerlerin-belirlenmesi" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> İki kategorili değişkenlerde uç değerlerin Belirlenmesi</h3>
<ul>
<li><p>summarytools paketinde <code>freq()</code> fonksiyonu ile frekans tabloları oluşturulabilir.</p></li>
<li><p>Veri setinde yer alan mstatus ve race değişkenlerinin frekans tabloları incelenmiştir.</p></li>
<li><p>İlk olarak eksik veri düzenlenmesi</p></li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb41-2"><a href="#cb41-2" tabindex="-1"></a>screen <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">&quot;import/SCREEN.sav&quot;</span>)</span>
<span id="cb41-3"><a href="#cb41-3" tabindex="-1"></a>screen <span class="ot">&lt;-</span> screen <span class="sc">%&gt;%</span> </span>
<span id="cb41-4"><a href="#cb41-4" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">income =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(income), <span class="fu">mean</span>(income, <span class="at">na.rm =</span><span class="cn">TRUE</span>),</span>
<span id="cb41-5"><a href="#cb41-5" tabindex="-1"></a>                       income)) <span class="sc">%&gt;%</span> <span class="fu">na.omit</span>()</span></code></pre></div>
<ul>
<li>race değişkenin frkans tablosu</li>
</ul>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;summarytools&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:tibble&#39;:
## 
##     view</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a><span class="fu">freq</span>(screen<span class="sc">$</span>race, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>, </span>
<span id="cb45-2"><a href="#cb45-2" tabindex="-1"></a>     <span class="at">round.digits=</span><span class="dv">2</span>,<span class="at">report.nas =</span> <span class="cn">FALSE</span>,</span>
<span id="cb45-3"><a href="#cb45-3" tabindex="-1"></a> <span class="at">style =</span> <span class="st">&quot;rmarkdown&quot;</span>) </span></code></pre></div>
<pre><code>## ### Frequencies  
## #### screen$race  
## **Label:** Ethnic group membership  
## **Type:** Numeric  
## 
## |    &amp;nbsp; | Freq |      % | % Cum. |
## |----------:|-----:|-------:|-------:|
## |     **1** |  424 |  91.38 |  91.38 |
## |     **2** |   40 |   8.62 | 100.00 |
## | **Total** |  464 | 100.00 | 100.00 |</code></pre>
<ul>
<li><p>İki kategorili değişkenlerden <strong>race</strong> değişkeninin kategorilere dağılımları
incelendiğinde kategoriler arasında yaklaşık 10.1:1 (91/9) oranı olduğu
görülmektedir. Bu oran oldukça yüksektir. Değişken araştırma için
önemli değilse çıkarılabilir, aksi halde değişkenle ilgili sonuçlar
yorumlanırken bu durum göz önüne alınmalıdır.</p></li>
<li><p>mstatus değişkenin frkans tablosu oluşturulurken kable fonksiyonu ile tablolaştırılmıştır.</p></li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a><span class="fu">freq</span>(screen<span class="sc">$</span>mstatus, <span class="at">plain.ascii =</span> <span class="cn">FALSE</span>,<span class="at">report.nas =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">format=</span><span class="st">&#39;markdown&#39;</span>, </span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Frekans Tablosu&quot;</span>,<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div>
<table>
<caption>(#tab:unnamed-chunk-3)Frekans Tablosu</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Freq</th>
<th align="right">% Valid</th>
<th align="right">% Valid Cum.</th>
<th align="right">% Total</th>
<th align="right">% Total Cum.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">102</td>
<td align="right">21.98</td>
<td align="right">21.98</td>
<td align="right">21.98</td>
<td align="right">21.98</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">362</td>
<td align="right">78.02</td>
<td align="right">100.00</td>
<td align="right">78.02</td>
<td align="right">100.00</td>
</tr>
<tr class="odd">
<td align="left"><NA></td>
<td align="right">0</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.00</td>
<td align="right">100.00</td>
</tr>
<tr class="even">
<td align="left">Total</td>
<td align="right">464</td>
<td align="right">100.00</td>
<td align="right">100.00</td>
<td align="right">100.00</td>
<td align="right">100.00</td>
</tr>
</tbody>
</table>
<ul>
<li><p>İki kategorili değişkenlerden <strong>mstatus</strong> değişkeninin kategorilere
dağılımları incelendiğinde kategoriler arasında yaklaşık 3.5:1 (78/22)
oranı olduğu görülmektedir. Bu oran kabul edilebilir bir orandır.</p></li>
<li><p>🔗 [summarytools için] (<a href="https://cran.r-project.org/web/packages/summarytools/vignettes/introduction.html" class="uri">https://cran.r-project.org/web/packages/summarytools/vignettes/introduction.html</a>)</p></li>
</ul>
</div>
<div id="sürekli-değişkenlerde-uç-değerlerin-belirlenmesi" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Sürekli değişkenlerde uç değerlerin Belirlenmesi</h3>
<ul>
<li><p>Sürekli değişkenler için tek değişkenli uç değerleri belirlemenin bir
yolu, değişkene ait bütün değerlerin ortalama 0, standart sapma 1
olacak şekilde standart değerlere (z puanlarına) dönüştürülmesidir.
Tek değişkenli uç değerler çok büyük z puanlarına sahiptirler.</p></li>
<li><p>Örneklem büyüklüğü 100 veya daha az olduğunda, eğer herhangi
bir gözlemin <strong>z puanı ±3.0</strong> veya daha fazlaysa, gözlem uç değerdir.</p></li>
<li><p>Örneklem büyüklüğü 100’den fazla olduğunda, eğer herhangi bir
gözlemin <strong>z puanı ±4.0</strong> veya daha fazlaysa, gözlem uç değerdir.</p></li>
<li><p>Bu yöntem eşit aralık veya eşit oran düzeyinde ölçülen değişkenler
için veya sürekli değişken olarak ele alınan sıralama ölçeğinde
ölçülen değişkenler için geçerli olup sınıflama düzeyinde ölçülen
değişkenler için geçerli değildir.</p></li>
<li><p>outliers paketinde <code>select()</code> fonksiyonu ile z değerleri hesaplanabilir.</p></li>
</ul>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a><span class="fu">library</span>(outliers)</span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a>z.scores <span class="ot">&lt;-</span> screen <span class="sc">%&gt;%</span>  </span>
<span id="cb48-3"><a href="#cb48-3" tabindex="-1"></a> <span class="fu">select</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-4"><a href="#cb48-4" tabindex="-1"></a> <span class="fu">scores</span>(<span class="at">type =</span> <span class="st">&quot;z&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb48-5"><a href="#cb48-5" tabindex="-1"></a> <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb48-6"><a href="#cb48-6" tabindex="-1"></a><span class="fu">head</span>(z.scores)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">timedrs</th>
<th align="right">attdrug</th>
<th align="right">atthouse</th>
<th align="right">income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-0.63</td>
<td align="right">0.27</td>
<td align="right">0.77</td>
<td align="right">0.34</td>
</tr>
<tr class="even">
<td align="right">-0.45</td>
<td align="right">-0.60</td>
<td align="right">-0.79</td>
<td align="right">0.76</td>
</tr>
<tr class="odd">
<td align="right">-0.72</td>
<td align="right">0.27</td>
<td align="right">-0.12</td>
<td align="right">-0.51</td>
</tr>
<tr class="even">
<td align="right">0.46</td>
<td align="right">1.13</td>
<td align="right">0.99</td>
<td align="right">1.61</td>
</tr>
<tr class="odd">
<td align="right">0.65</td>
<td align="right">-0.60</td>
<td align="right">0.10</td>
<td align="right">-1.36</td>
</tr>
<tr class="even">
<td align="right">-0.45</td>
<td align="right">0.27</td>
<td align="right">0.33</td>
<td align="right">-0.09</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>outliers paketinde <code>descr()</code> fonksiyonu ile z değerlerinin minumum ve maksimum değerleri incelenebilir.</li>
</ul>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a>summarytools<span class="sc">::</span><span class="fu">descr</span>(z.scores,</span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a> <span class="at">stats     =</span> <span class="fu">c</span>(<span class="st">&quot;min&quot;</span>, <span class="st">&quot;max&quot;</span>),</span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a> <span class="at">transpose =</span> <span class="cn">TRUE</span>,</span>
<span id="cb49-4"><a href="#cb49-4" tabindex="-1"></a> <span class="at">headings  =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span>   </span>
<span id="cb49-5"><a href="#cb49-5" tabindex="-1"></a> <span class="fu">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Min</th>
<th align="right">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">attdrug</td>
<td align="right">-2.33</td>
<td align="right">2.00</td>
</tr>
<tr class="even">
<td align="left">atthouse</td>
<td align="right">-4.80</td>
<td align="right">2.56</td>
</tr>
<tr class="odd">
<td align="left">income</td>
<td align="right">-1.36</td>
<td align="right">2.46</td>
</tr>
<tr class="even">
<td align="left">timedrs</td>
<td align="right">-0.72</td>
<td align="right">6.67</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>timedrs</strong> değişkeni için z puanlarının maksimum değerin 4.0’ten büyük olduğu,<strong>atthouse</strong> değişkeni z puanlarının içinse minimum değerin 4.0’ten küçük olduğu görülmektedir. Diğer değişkenler için değerler beklenen sınırlar içerisindedir.</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" tabindex="-1"></a>DT<span class="sc">::</span><span class="fu">datatable</span>(z.scores)</span></code></pre></div>
<div class="datatables html-widget html-fill-item" id="htmlwidget-8b17cb3ee100e34eb90a" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-8b17cb3ee100e34eb90a">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320","321","322","323","324","325","326","327","328","329","330","331","332","333","334","335","336","337","338","339","340","341","342","343","344","345","346","347","348","349","350","351","352","353","354","355","356","357","358","359","360","361","362","363","364","365","366","367","368","369","370","371","372","373","374","375","376","377","378","379","380","381","382","383","384","385","386","387","388","389","390","391","392","393","394","395","396","397","398","399","400","401","402","403","404","405","406","407","408","409","410","411","412","413","414","415","416","417","418","419","420","421","422","423","424","425","426","427","428","429","430","431","432","433","434","435","436","437","438","439","440","441","442","443","444","445","446","447","448","449","450","451","452","453","454","455","456","457","458","459","460","461","462","463","464"],[-0.63,-0.45,-0.72,0.46,0.65,-0.45,-0.54,-0.72,-0.08,-0.36,0.65,-0.72,-0.54,0.46,-0.54,-0.54,-0.63,-0.54,-0.27,-0.27,-0.45,-0.36,-0.54,-0.72,0.46,-0.08,-0.54,0.37,-0.54,-0.27,-0.36,-0.17,-0.54,-0.45,0.5600000000000001,-0.08,-0.72,-0.63,-0.45,4.75,-0.27,-0.45,-0.72,-0.45,-0.54,-0.63,-0.63,0.46,-0.54,-0.27,0.37,0.37,-0.63,1.1,-0.72,-0.27,-0.72,0.01,0.1,0.19,-0.63,-0.27,-0.27,1.38,-0.08,-0.63,2.84,-0.54,-0.08,0.1,-0.72,-0.36,0.74,-0.72,0.74,2.29,-0.36,-0.54,2.75,0.01,-0.54,-0.54,-0.72,0.65,-0.72,-0.63,-0.27,-0.08,0.19,1.29,0.19,-0.72,0.28,0.1,-0.72,2.38,-0.45,-0.63,-0.72,0.19,-0.36,1.74,-0.08,-0.63,-0.08,-0.45,-0.54,0.28,0.1,0.28,0.28,0.01,-0.54,-0.36,-0.36,-0.17,2.02,-0.08,0.65,-0.17,-0.08,-0.54,-0.63,-0.27,-0.63,0.28,0.74,-0.54,0.5600000000000001,0.01,0.83,-0.63,-0.72,-0.63,-0.63,0.19,-0.08,-0.54,-0.27,-0.17,-0.63,0.74,-0.72,0.83,-0.72,0.19,-0.17,1.1,-0.63,1.56,-0.45,-0.17,-0.72,0.01,0.1,1.01,-0.54,-0.54,-0.45,-0.08,-0.54,0.01,3.75,-0.54,-0.63,-0.27,-0.27,4.75,0.19,1.74,-0.08,0.01,0.37,-0.54,-0.54,-0.36,-0.17,1.74,-0.72,0.1,-0.45,-0.72,-0.54,-0.45,-0.27,-0.27,-0.63,-0.08,-0.36,-0.45,-0.08,-0.63,4.02,-0.17,0.92,0.5600000000000001,-0.72,0.01,0.74,-0.54,0.37,-0.45,1.47,-0.72,-0.72,4.48,0.28,-0.63,0.92,-0.63,0.28,-0.72,4.02,0.37,-0.17,-0.72,-0.54,-0.54,0.46,-0.54,-0.45,-0.54,-0.54,-0.63,-0.54,-0.45,-0.63,-0.27,-0.17,-0.63,-0.54,-0.45,-0.08,-0.08,-0.72,-0.08,0.01,0.1,0.01,-0.63,0.5600000000000001,-0.54,-0.36,0.01,-0.45,0.19,1.19,-0.17,4.57,0.37,-0.27,-0.54,-0.36,-0.54,-0.27,-0.72,-0.45,-0.08,-0.63,-0.54,-0.63,-0.36,-0.36,-0.36,-0.54,-0.72,0.46,-0.45,-0.63,-0.36,-0.63,-0.45,-0.63,4.48,-0.63,0.83,0.28,3.2,-0.17,-0.17,-0.63,-0.72,0.19,-0.45,2.65,-0.17,0.28,-0.36,6.12,-0.08,-0.45,-0.45,-0.45,-0.36,-0.27,-0.54,-0.36,-0.54,0.28,-0.72,-0.54,-0.36,-0.17,-0.72,-0.54,-0.27,-0.54,0.19,1.92,-0.45,-0.72,1.19,-0.72,-0.45,-0.63,0.1,-0.45,-0.45,-0.27,-0.17,-0.36,0.74,-0.45,0.46,-0.45,-0.54,-0.54,-0.45,-0.08,-0.54,-0.54,-0.54,-0.54,-0.27,-0.45,-0.54,-0.36,-0.63,-0.45,-0.17,-0.36,2.02,-0.72,1.56,-0.72,-0.27,-0.45,-0.54,-0.54,0.1,-0.54,0.46,-0.63,-0.36,-0.36,-0.45,-0.08,-0.08,0.5600000000000001,-0.36,0.65,2.65,-0.54,-0.36,-0.17,0.19,4.39,-0.45,-0.72,0.92,-0.45,0.92,-0.08,1.92,-0.72,-0.27,-0.36,-0.45,-0.17,1.19,-0.63,-0.45,-0.45,-0.72,0.46,-0.27,-0.27,2.65,-0.54,0.28,0.46,-0.54,-0.36,1.19,-0.54,-0.36,-0.45,-0.45,0.37,-0.63,-0.36,0.46,-0.54,6.67,0.37,-0.54,0.74,1.74,-0.54,-0.54,0.01,-0.54,-0.36,-0.45,1.01,-0.36,-0.63,-0.45,0.65,-0.36,-0.36,0.46,-0.17,-0.63,-0.45,-0.45,-0.72,1.29,-0.36,0.5600000000000001,-0.17,0.74,-0.17,-0.72,0.01,-0.72,-0.36,-0.27,-0.54,-0.17,0.28,-0.63,1.38,-0.36,-0.36,0.74,-0.17,-0.63,-0.54,-0.17,-0.17,-0.45,-0.63,0.65,-0.45,-0.08,0.1,0.92,0.5600000000000001,-0.45,-0.36,0.65,-0.36,-0.45],[0.27,-0.6,0.27,1.13,-0.6,0.27,-0.6,-0.6,-0.6,0.27,1.13,-1.46,-1.46,0.27,-2.33,0.27,0.27,-1.46,0.27,2,-1.46,-2.33,0.27,0.27,1.13,1.13,0.27,1.13,-1.46,1.13,-0.6,-1.46,1.13,-0.6,1.13,-0.6,0.27,0.27,0.27,-0.6,0.27,1.13,-0.6,0.27,-1.46,0.27,1.13,0.27,-0.6,1.13,-1.46,1.13,1.13,1.13,-1.46,-0.6,-0.6,2,0.27,0.27,2,0.27,0.27,-1.46,-1.46,-0.6,-0.6,0.27,0.27,-0.6,-2.33,0.27,2,-0.6,0.27,1.13,-0.6,0.27,0.27,0.27,0.27,1.13,1.13,-0.6,-0.6,0.27,-0.6,1.13,-1.46,1.13,-0.6,-0.6,0.27,-0.6,0.27,-0.6,1.13,-1.46,2,-1.46,0.27,0.27,1.13,-2.33,2,0.27,-1.46,-1.46,-1.46,0.27,0.27,-0.6,1.13,1.13,0.27,-0.6,-2.33,0.27,-0.6,-0.6,-0.6,1.13,-0.6,-0.6,1.13,-1.46,2,-0.6,-2.33,-0.6,0.27,0.27,-1.46,1.13,-1.46,0.27,-0.6,0.27,-1.46,-0.6,0.27,2,-2.33,-0.6,0.27,0.27,-0.6,0.27,0.27,0.27,1.13,1.13,-0.6,0.27,1.13,2,0.27,-0.6,-0.6,0.27,0.27,-1.46,0.27,0.27,0.27,-1.46,0.27,2,-0.6,0.27,1.13,-0.6,0.27,-0.6,-0.6,-0.6,-2.33,1.13,0.27,2,1.13,0.27,-1.46,0.27,0.27,1.13,1.13,1.13,0.27,-0.6,0.27,-0.6,1.13,-0.6,-0.6,-0.6,-0.6,1.13,0.27,1.13,0.27,-0.6,2,1.13,-0.6,1.13,1.13,0.27,-1.46,-2.33,1.13,0.27,0.27,-0.6,-1.46,-0.6,0.27,0.27,2,-0.6,-1.46,1.13,-0.6,-0.6,-0.6,0.27,1.13,-2.33,-0.6,-0.6,0.27,-1.46,2,-1.46,0.27,0.27,-0.6,-0.6,-1.46,1.13,1.13,1.13,-0.6,0.27,0.27,0.27,2,-0.6,-0.6,0.27,-0.6,1.13,-0.6,-0.6,1.13,1.13,0.27,1.13,1.13,0.27,-1.46,-1.46,-0.6,0.27,0.27,0.27,-1.46,0.27,0.27,-0.6,0.27,-0.6,-1.46,0.27,0.27,1.13,-0.6,-1.46,1.13,0.27,1.13,-0.6,-1.46,1.13,1.13,0.27,-0.6,-0.6,1.13,1.13,-1.46,-0.6,-0.6,0.27,1.13,2,-0.6,0.27,1.13,-1.46,-0.6,0.27,1.13,0.27,-1.46,-1.46,-1.46,1.13,1.13,0.27,0.27,0.27,-0.6,0.27,0.27,1.13,0.27,-0.6,0.27,0.27,1.13,-2.33,1.13,1.13,1.13,-1.46,0.27,-0.6,-0.6,0.27,-0.6,-0.6,-0.6,2,-0.6,-1.46,1.13,-0.6,0.27,1.13,0.27,0.27,-0.6,-0.6,-0.6,0.27,0.27,1.13,-0.6,0.27,0.27,-1.46,0.27,1.13,-0.6,1.13,1.13,0.27,-1.46,-0.6,-1.46,1.13,-0.6,-0.6,1.13,-1.46,0.27,2,1.13,-0.6,1.13,-0.6,0.27,0.27,-2.33,-1.46,0.27,-0.6,-0.6,1.13,0.27,-0.6,0.27,-0.6,2,-1.46,0.27,-0.6,0.27,0.27,-0.6,1.13,1.13,1.13,2,0.27,0.27,0.27,0.27,-0.6,-0.6,-0.6,-0.6,0.27,-0.6,0.27,-0.6,0.27,-2.33,-0.6,0.27,0.27,0.27,0.27,-0.6,1.13,-0.6,-0.6,-1.46,0.27,0.27,0.27,1.13,2,1.13,1.13,1.13,-0.6,0.27,-0.6,1.13,-0.6,-1.46,0.27,-1.46,-0.6,-0.6,-1.46,0.27,0.27,0.27,-0.6,-0.6,0.27,1.13,1.13,-0.6,1.13,-1.46,1.13,-1.46,-0.6,-0.6,1.13,-1.46,0.27,-1.46,-1.46,1.13,-1.46,0.27,2,0.27,0.27],[0.77,-0.79,-0.12,0.99,0.1,0.33,1.44,0.1,-0.79,1.44,-1.9,-0.34,-1.01,0.33,-1.46,-1.01,-0.34,-0.57,0.99,0.33,-1.01,1.66,0.33,0.55,0.55,2.11,-0.79,0.55,0.77,1.44,1.66,0.33,0.77,-0.12,-1.9,1.89,-0.57,0.99,-1.68,0.1,-1.01,-0.12,0.1,1.66,1.22,-0.12,0.1,0.33,-0.34,0.55,0.77,0.1,0.77,0.1,-0.12,0.33,-0.34,0.33,-1.9,0.99,0.33,-0.34,-0.57,1.22,0.55,-0.12,0.55,-0.57,-0.34,1.66,2.56,0.99,0.99,-0.79,0.1,0.33,0.33,-1.68,-1.24,-0.12,0.1,1.22,-1.68,-0.34,0.77,-0.12,0.55,1.44,-0.12,0.55,1.44,0.33,-0.34,-0.57,-1.68,-0.12,0.33,-0.79,-1.24,-0.12,-1.46,-0.12,-0.12,-0.34,-0.34,0.99,-1.46,0.77,-1.24,0.55,-0.57,-0.57,0.1,0.55,-0.57,-1.24,0.1,0.99,0.55,0.33,-0.12,-0.34,-1.01,0.55,1.22,-0.79,-0.79,-1.01,0.1,-0.57,1.89,-1.24,-0.34,0.77,-0.57,-1.01,0.33,-1.46,0.33,1.66,-1.68,-1.46,-2.13,1.44,0.33,0.99,-0.34,0.1,-0.57,0.33,0.77,-0.79,0.55,0.33,0.77,-0.12,0.77,-0.57,-0.34,-1.01,0.55,0.33,2.33,0.77,-0.34,-2.13,1.22,1.22,0.55,-1.46,-0.34,-0.79,1.44,-1.46,-0.57,-0.34,1.22,-0.34,-0.79,1.44,0.33,-1.24,-1.01,0.1,-0.34,-0.57,1.22,-0.34,0.55,-1.01,-0.12,-1.01,1.66,0.55,-0.12,1.22,-0.34,1.22,-0.12,-1.46,0.55,0.33,0.33,-1.01,-1.68,0.1,1.22,-0.79,0.33,-1.68,2.56,0.1,-1.01,0.33,1.22,0.33,1.22,-0.79,0.33,1.66,2.11,0.1,0.55,-0.79,-1.46,0.33,0.1,0.77,0.33,0.99,1.22,0.77,0.1,-0.12,-1.01,-0.12,0.1,-0.57,-0.34,-0.57,1.44,1.89,-0.57,-1.01,0.1,0.99,0.99,1.22,1.22,-0.12,0.55,-0.34,0.33,-1.01,-0.34,-1.24,0.33,-0.12,-1.01,-4.8,0.55,0.1,1.44,1.44,-0.34,0.55,1.44,0.33,0.1,-0.12,-1.24,-0.12,2.33,-0.12,-2.35,0.77,-0.57,0.99,0.99,-0.79,-0.57,0.33,0.77,-0.12,0.33,-0.34,0.1,-1.9,2.11,0.1,1.22,-0.57,0.55,1.22,-0.57,-0.57,-1.24,-4.8,0.99,-0.79,0.77,-0.12,0.77,0.77,0.33,-0.34,1.22,-0.12,-2.13,0.99,1.22,0.77,-0.12,-0.12,-0.79,0.1,0.55,-0.12,0.33,0.99,-1.68,1.22,0.33,-0.34,1.22,-0.12,0.55,-1.01,0.77,-0.57,-1.24,-1.01,-0.12,-1.01,-0.57,-0.12,0.99,0.1,0.77,0.77,0.33,1.22,-1.01,0.77,1.66,-1.24,-0.12,1.89,-0.79,-0.57,0.33,-0.57,-0.34,1.22,-0.12,-0.79,-0.57,0.55,-0.57,0.1,0.55,1.44,-1.24,-0.34,0.33,-0.57,-1.01,-0.12,-0.34,-0.57,-0.34,0.1,-1.24,-1.24,0.1,0.33,-1.01,0.77,1.22,-0.34,0.33,0.77,0.55,0.99,-1.01,-0.12,2.11,0.1,0.99,0.99,0.1,-0.57,1.66,-0.12,0.55,0.55,0.55,0.1,-1.24,-0.57,-1.01,-1.46,0.1,0.1,1.66,-1.01,0.99,-0.12,0.55,0.55,-1.24,-1.68,1.22,-2.13,-0.12,1.22,-1.01,-0.34,-0.79,-0.34,-0.57,-0.12,0.55,-1.24,-1.24,0.99,1.66,-0.34,0.99,-0.79,-0.79,0.55,0.77,-2.8,0.55,0.77,-1.68,-2.57,-0.79,-1.01,0.55,-0.79,-0.34,1.44,0.33,-0.12,-0.34,0.1,-0.12,0.77,0.99,0.1,-1.46,-0.34,-0.12,-1.68,-1.24,-0.57,-1.01,-1.46,-1.46,-1.01,-0.12,-1.24],[0.34,0.76,-0.51,1.61,-1.36,-0.09,0.76,0.76,-0.9399999999999999,1.61,1.19,-0.51,0.34,0.76,-1.36,-0.51,-1.36,1.19,-0.9399999999999999,2.04,-0.09,0.34,-0.9399999999999999,-1.36,-0.9399999999999999,-1.36,0.34,-1.36,-0.51,-1.36,-0.09,0.34,0.34,-0.09,-0.09,-0.51,2.04,0.76,-1.36,-1.36,-1.36,0.76,1.61,-0.51,-1.36,-0.09,-0.09,-1.36,-0.9399999999999999,0.34,0.34,0,0.76,0.76,-0.09,-0.09,0.76,2.04,-0.51,0.76,-0.51,1.19,-0.51,0,-1.36,-0.9399999999999999,-0.9399999999999999,-0.51,0,0.34,0.34,0.34,0.34,0.34,-0.51,-1.36,0,-0.51,-0.9399999999999999,-0.9399999999999999,2.04,2.46,-1.36,0.34,2.46,1.61,-1.36,-0.51,-0.51,0.76,-0.51,-0.9399999999999999,-1.36,-0.09,-0.09,0.34,-0.09,0.34,-1.36,-0.09,-0.09,1.61,0.34,-0.9399999999999999,0.76,-0.09,-0.9399999999999999,1.19,-0.09,1.19,1.19,-0.09,2.46,-0.51,-0.51,1.61,2.46,0,-1.36,1.61,0.34,-0.51,0.34,-0.51,-0.51,-0.09,-1.36,0.34,-0.09,-0.51,-1.36,-0.51,-1.36,1.61,0,-1.36,-1.36,1.19,-0.51,-0.09,1.19,1.61,1.61,-0.09,0.76,-1.36,-1.36,0.34,-0.9399999999999999,1.19,1.19,1.19,-1.36,-1.36,-0.51,0.34,-0.51,-0.51,0.34,1.19,0,-0.09,-0.09,-1.36,-0.51,-0.51,-1.36,-0.09,0.76,1.19,-0.51,0,0,0,-1.36,-0.51,-0.51,-1.36,2.04,-0.51,0,0.34,-0.09,-0.51,-0.09,1.61,-1.36,-1.36,1.19,0.76,1.61,2.04,-0.09,-0.9399999999999999,-0.09,0,-0.09,-1.36,1.19,-0.51,-1.36,-0.09,0,-0.09,-0.51,-0.9399999999999999,-0.51,0.76,-0.9399999999999999,0.76,-0.09,1.19,-1.36,-0.09,-0.51,-0.51,-0.9399999999999999,0.76,-1.36,-0.09,0.34,-0.9399999999999999,-0.09,1.19,-0.09,1.19,-0.51,2.46,2.46,1.19,-1.36,-0.09,-0.09,1.19,-0.51,0,-0.51,1.19,-0.51,0,-0.9399999999999999,-1.36,-0.51,2.46,-0.09,-1.36,2.46,1.19,-0.09,-0.09,-1.36,-1.36,0.76,0.34,-0.51,0.34,0,0.34,1.61,-1.36,0.34,-0.51,-0.09,0.34,-0.51,1.19,-0.09,0.34,0.34,-0.51,-0.09,-0.09,-0.09,-0.09,-1.36,1.19,-0.51,1.19,1.19,0.76,-1.36,2.04,2.04,2.46,0.76,-0.9399999999999999,2.04,-0.51,2.04,0.34,1.19,-0.51,-0.9399999999999999,-0.09,-1.36,-1.36,0.34,-0.09,-0.9399999999999999,0.76,-0.09,0.76,0,0.34,-0.09,-0.09,-1.36,1.19,-0.51,1.61,-0.51,1.19,0.76,0.34,-1.36,2.46,-0.51,-1.36,-0.09,0,-0.09,-1.36,2.04,0,-1.36,-0.51,-0.51,0.34,0.34,-0.09,0.76,-0.09,-0.51,1.19,0.76,0.34,-0.51,0.76,-0.9399999999999999,2.46,-0.09,-0.09,0.34,-0.51,-0.51,-0.9399999999999999,1.61,-0.09,1.19,-0.51,0,-0.09,-0.51,-0.09,-1.36,-1.36,-1.36,-1.36,-0.9399999999999999,-1.36,0.76,-0.9399999999999999,-0.9399999999999999,-0.9399999999999999,-0.09,-0.09,-0.51,0.34,-1.36,-1.36,-0.51,-0.09,-0.09,0.34,-0.09,1.61,0,0,-0.9399999999999999,-0.9399999999999999,-1.36,-0.51,0.76,-1.36,-0.9399999999999999,2.04,-0.09,2.46,-0.09,-0.09,2.04,-0.09,-0.51,-0.9399999999999999,-0.09,-0.51,-0.51,-0.09,-0.51,0.34,-0.9399999999999999,1.61,-1.36,2.04,2.46,0.76,-0.09,0,0.34,-0.9399999999999999,0.76,-0.09,-1.36,-0.09,-0.09,-1.36,-0.51,0,-1.36,0,-1.36,0.76,-1.36,2.46,-1.36,-0.09,-0.9399999999999999,-0.9399999999999999,-0.51,-0.9399999999999999,1.19,1.19,-1.36,0,1.19,0.76,-0.09,-0.09,-0.51,0.76,1.19,-0.51,1.19,0.76,-1.36,0.76,1.61,0.34,-0.09,-0.51,-0.51,-0.51,-0.09,2.46,-0.09,-0.51,-0.9399999999999999,-0.09,-0.51,-0.51,-0.51,1.61,-0.9399999999999999,-0.09]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>timedrs<\/th>\n      <th>attdrug<\/th>\n      <th>atthouse<\/th>\n      <th>income<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,2,3,4]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"timedrs","targets":1},{"name":"attdrug","targets":2},{"name":"atthouse","targets":3},{"name":"income","targets":4}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<ul>
<li><p>Tek değişkenli uç değerleri saptamak için grafiksel yöntemlerden de
yararlanılabilir (Örneğin, histogramlar, kutu grafikleri, normal olasılık
grafikleri gibi).</p></li>
<li><p>Histogramlar kolay anlaşılan ve yorumlanan grafiklerdir ve uç
değerlerin belirlenmesine yardımcı olabilirler. Genellikle ortalamanın
yakınındaki çoğu gözlemle birlikte ortalamanın iki yönüne doğru
uzanan gözlemler vardır. Uç değer dağılımın geri kalanıyla
bağlantısı bulunmayan gözlemdir.</p></li>
<li><p>Kutu grafikleri de basittir. Medyan etrafındaki gözlemler kutu içine
alınır. Kutudan çok uzağa düşen gözlemler uç değerdir.</p></li>
<li><p>Normal olasılık grafikleri değişkenlerin dağılımlarının normalliğinin
değerlendirilmesinde oldukça kullanışlıdır. Uç değerler de bu
grafiklerde gözlenebilir; diğerlerinden önemli derecede uzakta
bulunan nokta uçdeğerdir.</p></li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb51-2"><a href="#cb51-2" tabindex="-1"></a><span class="fu">ggplot</span>(screen, <span class="fu">aes</span>(<span class="at">x =</span> timedrs)) <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> 30L, <span class="at">fill =</span> <span class="st">&quot;#0c4c8a&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-4"><a href="#cb51-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-7-1.png" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li>yoğunluk grafiği ile uç değerlerin incelenmesi</li>
</ul>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="fu">ggplot</span>(screen, <span class="fu">aes</span>(<span class="at">x =</span> timedrs)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..))<span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" tabindex="-1"></a> <span class="fu">geom_density</span>(<span class="at">alpha=</span>.<span class="dv">5</span>, <span class="at">fill=</span><span class="st">&quot;#0c4c8a&quot;</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
## ℹ Please use `after_stat(density)` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-8-1.png" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li>interaktif grafik eklenmesi</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a><span class="fu">library</span>(plotly)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;plotly&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a><span class="fu">plot_ly</span>(<span class="at">x =</span> screen<span class="sc">$</span>timedrs,  <span class="at">type =</span> <span class="st">&quot;histogram&quot;</span>, </span>
<span id="cb60-2"><a href="#cb60-2" tabindex="-1"></a><span class="at">histnorm =</span> <span class="st">&quot;probability&quot;</span>)</span></code></pre></div>
<div class="plotly html-widget html-fill-item" id="htmlwidget-673089ae51fcee0a308d" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-673089ae51fcee0a308d">{"x":{"visdat":{"116079ad2398":["function () ","plotlyVisDat"]},"cur_data":"116079ad2398","attrs":{"116079ad2398":{"x":[1,3,0,13,15,3,2,0,7,4,15,0,2,13,2,2,1,2,5,5,3,4,2,0,13,7,2,12,2,5,4,6,2,3,14,7,0,1,3,60,5,3,0,3,2,1,1,13,2,5,12,12,1,20,0,5,0,8,9,10,1,5,5,23,7,1,39,2,7,9,0,4,16,0,16,33,4,2,38,8,2,2,0,15,0,1,5,7,10,22,10,0,11,9,0,34,3,1,0,10,4,27,7,1,7,3,2,11,9,11,11,8,2,4,4,6,30,7,15,6,7,2,1,5,1,11,16,2,14,8,17,1,0,1,1,10,7,2,5,6,1,16,0,17,0,10,6,20,1,25,3,6,0,8,9,19,2,2,3,7,2,8,49,2,1,5,5,60,10,27,7,8,12,2,2,4,6,27,0,9,3,0,2,3,5,5,1,7,4,3,7,1,52,6,18,14,0,8,16,2,12,3,24,0,0,57,11,1,18,1,11,0,52,12,6,0,2,2,13,2,3,2,2,1,2,3,1,5,6,1,2,3,7,7,0,7,8,9,8,1,14,2,4,8,3,10,21,6,58,12,5,2,4,2,5,0,3,7,1,2,1,4,4,4,2,0,13,3,1,4,1,3,1,57,1,17,11,43,6,6,1,0,10,3,37,6,11,4,75,7,3,3,3,4,5,2,4,2,11,0,2,4,6,0,2,5,2,10,29,3,0,21,0,3,1,9,3,3,5,6,4,16,3,13,3,2,2,3,7,2,2,2,2,5,3,2,4,1,3,6,4,30,0,25,0,5,3,2,2,9,2,13,1,4,4,3,7,7,14,4,15,37,2,4,6,10,56,3,0,18,3,18,7,29,0,5,4,3,6,21,1,3,3,0,13,5,5,37,2,11,13,2,4,21,2,4,3,3,12,1,4,13,2,81,12,2,16,27,2,2,8,2,4,3,19,4,1,3,15,4,4,13,6,1,3,3,0,22,4,14,6,16,6,0,8,0,4,5,2,6,11,1,23,4,4,16,6,1,2,6,6,3,1,15,3,7,9,18,14,3,4,15,4,3],"histnorm":"probability","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"histogram"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":[]},"yaxis":{"domain":[0,1],"automargin":true},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[1,3,0,13,15,3,2,0,7,4,15,0,2,13,2,2,1,2,5,5,3,4,2,0,13,7,2,12,2,5,4,6,2,3,14,7,0,1,3,60,5,3,0,3,2,1,1,13,2,5,12,12,1,20,0,5,0,8,9,10,1,5,5,23,7,1,39,2,7,9,0,4,16,0,16,33,4,2,38,8,2,2,0,15,0,1,5,7,10,22,10,0,11,9,0,34,3,1,0,10,4,27,7,1,7,3,2,11,9,11,11,8,2,4,4,6,30,7,15,6,7,2,1,5,1,11,16,2,14,8,17,1,0,1,1,10,7,2,5,6,1,16,0,17,0,10,6,20,1,25,3,6,0,8,9,19,2,2,3,7,2,8,49,2,1,5,5,60,10,27,7,8,12,2,2,4,6,27,0,9,3,0,2,3,5,5,1,7,4,3,7,1,52,6,18,14,0,8,16,2,12,3,24,0,0,57,11,1,18,1,11,0,52,12,6,0,2,2,13,2,3,2,2,1,2,3,1,5,6,1,2,3,7,7,0,7,8,9,8,1,14,2,4,8,3,10,21,6,58,12,5,2,4,2,5,0,3,7,1,2,1,4,4,4,2,0,13,3,1,4,1,3,1,57,1,17,11,43,6,6,1,0,10,3,37,6,11,4,75,7,3,3,3,4,5,2,4,2,11,0,2,4,6,0,2,5,2,10,29,3,0,21,0,3,1,9,3,3,5,6,4,16,3,13,3,2,2,3,7,2,2,2,2,5,3,2,4,1,3,6,4,30,0,25,0,5,3,2,2,9,2,13,1,4,4,3,7,7,14,4,15,37,2,4,6,10,56,3,0,18,3,18,7,29,0,5,4,3,6,21,1,3,3,0,13,5,5,37,2,11,13,2,4,21,2,4,3,3,12,1,4,13,2,81,12,2,16,27,2,2,8,2,4,3,19,4,1,3,15,4,4,13,6,1,3,3,0,22,4,14,6,16,6,0,8,0,4,5,2,6,11,1,23,4,4,16,6,1,2,6,6,3,1,15,3,7,9,18,14,3,4,15,4,3],"histnorm":"probability","type":"histogram","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<ul>
<li>grafk üzerinde ortalamanın gösterilmesi</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a><span class="fu">library</span>(ggpmisc)</span></code></pre></div>
<pre><code>## Loading required package: ggpp</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggpp&#39;:
##   method                  from   
##   heightDetails.titleGrob ggplot2
##   widthDetails.titleGrob  ggplot2</code></pre>
<pre><code>## 
## Attaching package: &#39;ggpp&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     annotate</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;ggpmisc&#39;:
##   method                  from   
##   as.character.polynomial polynom</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a><span class="fu">ggplot</span>(screen, <span class="fu">aes</span>(<span class="at">x =</span> timedrs)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a><span class="fu">geom_vline</span>(<span class="at">xintercept =</span><span class="fl">7.914</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, </span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a><span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span> </span>
<span id="cb67-4"><a href="#cb67-4" tabindex="-1"></a><span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">label =</span> <span class="st">&quot;Mean = 7.913&quot;</span>, <span class="at">x =</span> <span class="dv">10</span>, <span class="at">y =</span> <span class="dv">100</span>,  <span class="at">color =</span><span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-10-1.png" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li>kutu grafiği</li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a><span class="fu">ggplot</span>(screen, <span class="fu">aes</span>(<span class="at">y =</span> timedrs)) <span class="sc">+</span> </span>
<span id="cb69-2"><a href="#cb69-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()  </span></code></pre></div>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-11-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" tabindex="-1"></a><span class="fu">boxplot.stats</span>(screen<span class="sc">$</span>timedrs)<span class="sc">$</span>out</span>
<span id="cb70-2"><a href="#cb70-2" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">boxplot.stats</span>(screen<span class="sc">$</span>timedrs)<span class="sc">$</span>out</span>
<span id="cb70-3"><a href="#cb70-3" tabindex="-1"></a>out</span>
<span id="cb70-4"><a href="#cb70-4" tabindex="-1"></a>out_ind <span class="ot">&lt;-</span> <span class="fu">which</span>(screen<span class="sc">$</span>timedrs <span class="sc">%in%</span> <span class="fu">c</span>(out))</span>
<span id="cb70-5"><a href="#cb70-5" tabindex="-1"></a>out_ind</span></code></pre></div>
<pre><code>##  [1] 60 23 39 33 38 34 27 30 25 49 60 27 27 52 24 57 52 58 57 43 37 75 29 30 25
## [26] 37 56 29 37 81 27 23
##  [1] 60 23 39 33 38 34 27 30 25 49 60 27 27 52 24 57 52 58 57 43 37 75 29 30 25
## [26] 37 56 29 37 81 27 23
##  [1]  40  64  67  76  79  96 102 117 150 163 168 170 178 193 203 206 213 249 274
## [20] 278 285 289 309 342 344 362 367 374 388 404 408 443</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" tabindex="-1"></a><span class="fu">plot_ly</span>(<span class="at">y =</span> screen<span class="sc">$</span>timedrs, <span class="at">type =</span> <span class="st">&#39;box&#39;</span>) </span></code></pre></div>
<div class="plotly html-widget html-fill-item" id="htmlwidget-6847b701f58ae5bae6f8" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-6847b701f58ae5bae6f8">{"x":{"visdat":{"11603d5225b0":["function () ","plotlyVisDat"]},"cur_data":"11603d5225b0","attrs":{"11603d5225b0":{"y":[1,3,0,13,15,3,2,0,7,4,15,0,2,13,2,2,1,2,5,5,3,4,2,0,13,7,2,12,2,5,4,6,2,3,14,7,0,1,3,60,5,3,0,3,2,1,1,13,2,5,12,12,1,20,0,5,0,8,9,10,1,5,5,23,7,1,39,2,7,9,0,4,16,0,16,33,4,2,38,8,2,2,0,15,0,1,5,7,10,22,10,0,11,9,0,34,3,1,0,10,4,27,7,1,7,3,2,11,9,11,11,8,2,4,4,6,30,7,15,6,7,2,1,5,1,11,16,2,14,8,17,1,0,1,1,10,7,2,5,6,1,16,0,17,0,10,6,20,1,25,3,6,0,8,9,19,2,2,3,7,2,8,49,2,1,5,5,60,10,27,7,8,12,2,2,4,6,27,0,9,3,0,2,3,5,5,1,7,4,3,7,1,52,6,18,14,0,8,16,2,12,3,24,0,0,57,11,1,18,1,11,0,52,12,6,0,2,2,13,2,3,2,2,1,2,3,1,5,6,1,2,3,7,7,0,7,8,9,8,1,14,2,4,8,3,10,21,6,58,12,5,2,4,2,5,0,3,7,1,2,1,4,4,4,2,0,13,3,1,4,1,3,1,57,1,17,11,43,6,6,1,0,10,3,37,6,11,4,75,7,3,3,3,4,5,2,4,2,11,0,2,4,6,0,2,5,2,10,29,3,0,21,0,3,1,9,3,3,5,6,4,16,3,13,3,2,2,3,7,2,2,2,2,5,3,2,4,1,3,6,4,30,0,25,0,5,3,2,2,9,2,13,1,4,4,3,7,7,14,4,15,37,2,4,6,10,56,3,0,18,3,18,7,29,0,5,4,3,6,21,1,3,3,0,13,5,5,37,2,11,13,2,4,21,2,4,3,3,12,1,4,13,2,81,12,2,16,27,2,2,8,2,4,3,19,4,1,3,15,4,4,13,6,1,3,3,0,22,4,14,6,16,6,0,8,0,4,5,2,6,11,1,23,4,4,16,6,1,2,6,6,3,1,15,3,7,9,18,14,3,4,15,4,3],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"box"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"yaxis":{"domain":[0,1],"automargin":true,"title":[]},"xaxis":{"domain":[0,1],"automargin":true},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"fillcolor":"rgba(31,119,180,0.5)","y":[1,3,0,13,15,3,2,0,7,4,15,0,2,13,2,2,1,2,5,5,3,4,2,0,13,7,2,12,2,5,4,6,2,3,14,7,0,1,3,60,5,3,0,3,2,1,1,13,2,5,12,12,1,20,0,5,0,8,9,10,1,5,5,23,7,1,39,2,7,9,0,4,16,0,16,33,4,2,38,8,2,2,0,15,0,1,5,7,10,22,10,0,11,9,0,34,3,1,0,10,4,27,7,1,7,3,2,11,9,11,11,8,2,4,4,6,30,7,15,6,7,2,1,5,1,11,16,2,14,8,17,1,0,1,1,10,7,2,5,6,1,16,0,17,0,10,6,20,1,25,3,6,0,8,9,19,2,2,3,7,2,8,49,2,1,5,5,60,10,27,7,8,12,2,2,4,6,27,0,9,3,0,2,3,5,5,1,7,4,3,7,1,52,6,18,14,0,8,16,2,12,3,24,0,0,57,11,1,18,1,11,0,52,12,6,0,2,2,13,2,3,2,2,1,2,3,1,5,6,1,2,3,7,7,0,7,8,9,8,1,14,2,4,8,3,10,21,6,58,12,5,2,4,2,5,0,3,7,1,2,1,4,4,4,2,0,13,3,1,4,1,3,1,57,1,17,11,43,6,6,1,0,10,3,37,6,11,4,75,7,3,3,3,4,5,2,4,2,11,0,2,4,6,0,2,5,2,10,29,3,0,21,0,3,1,9,3,3,5,6,4,16,3,13,3,2,2,3,7,2,2,2,2,5,3,2,4,1,3,6,4,30,0,25,0,5,3,2,2,9,2,13,1,4,4,3,7,7,14,4,15,37,2,4,6,10,56,3,0,18,3,18,7,29,0,5,4,3,6,21,1,3,3,0,13,5,5,37,2,11,13,2,4,21,2,4,3,3,12,1,4,13,2,81,12,2,16,27,2,2,8,2,4,3,19,4,1,3,15,4,4,13,6,1,3,3,0,22,4,14,6,16,6,0,8,0,4,5,2,6,11,1,23,4,4,16,6,1,2,6,6,3,1,15,3,7,9,18,14,3,4,15,4,3],"type":"box","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a><span class="fu">plot_ly</span>(<span class="at">y =</span> screen<span class="sc">$</span>timedrs, <span class="at">type =</span> <span class="st">&#39;box&#39;</span>)  <span class="sc">%&gt;%</span> <span class="fu">layout</span>(<span class="at">title =</span> <span class="st">&#39;Box Plot&#39;</span>,</span>
<span id="cb73-2"><a href="#cb73-2" tabindex="-1"></a><span class="at">annotations =</span> <span class="fu">list</span>( <span class="at">x =</span> <span class="sc">-</span><span class="fl">0.01</span>,  <span class="at">y =</span> <span class="fu">boxplot.stats</span>(screen<span class="sc">$</span>timedrs)<span class="sc">$</span>out, </span>
<span id="cb73-3"><a href="#cb73-3" tabindex="-1"></a><span class="at">text =</span> <span class="fu">paste</span>(out_ind), <span class="at">showarrow =</span> <span class="cn">FALSE</span>,</span>
<span id="cb73-4"><a href="#cb73-4" tabindex="-1"></a><span class="at">xanchor =</span> <span class="st">&quot;right&quot;</span>))</span></code></pre></div>
<div class="plotly html-widget html-fill-item" id="htmlwidget-ed1099273d2c1bd288c2" style="width:100%;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-ed1099273d2c1bd288c2">{"x":{"visdat":{"1160222626d5":["function () ","plotlyVisDat"]},"cur_data":"1160222626d5","attrs":{"1160222626d5":{"y":[1,3,0,13,15,3,2,0,7,4,15,0,2,13,2,2,1,2,5,5,3,4,2,0,13,7,2,12,2,5,4,6,2,3,14,7,0,1,3,60,5,3,0,3,2,1,1,13,2,5,12,12,1,20,0,5,0,8,9,10,1,5,5,23,7,1,39,2,7,9,0,4,16,0,16,33,4,2,38,8,2,2,0,15,0,1,5,7,10,22,10,0,11,9,0,34,3,1,0,10,4,27,7,1,7,3,2,11,9,11,11,8,2,4,4,6,30,7,15,6,7,2,1,5,1,11,16,2,14,8,17,1,0,1,1,10,7,2,5,6,1,16,0,17,0,10,6,20,1,25,3,6,0,8,9,19,2,2,3,7,2,8,49,2,1,5,5,60,10,27,7,8,12,2,2,4,6,27,0,9,3,0,2,3,5,5,1,7,4,3,7,1,52,6,18,14,0,8,16,2,12,3,24,0,0,57,11,1,18,1,11,0,52,12,6,0,2,2,13,2,3,2,2,1,2,3,1,5,6,1,2,3,7,7,0,7,8,9,8,1,14,2,4,8,3,10,21,6,58,12,5,2,4,2,5,0,3,7,1,2,1,4,4,4,2,0,13,3,1,4,1,3,1,57,1,17,11,43,6,6,1,0,10,3,37,6,11,4,75,7,3,3,3,4,5,2,4,2,11,0,2,4,6,0,2,5,2,10,29,3,0,21,0,3,1,9,3,3,5,6,4,16,3,13,3,2,2,3,7,2,2,2,2,5,3,2,4,1,3,6,4,30,0,25,0,5,3,2,2,9,2,13,1,4,4,3,7,7,14,4,15,37,2,4,6,10,56,3,0,18,3,18,7,29,0,5,4,3,6,21,1,3,3,0,13,5,5,37,2,11,13,2,4,21,2,4,3,3,12,1,4,13,2,81,12,2,16,27,2,2,8,2,4,3,19,4,1,3,15,4,4,13,6,1,3,3,0,22,4,14,6,16,6,0,8,0,4,5,2,6,11,1,23,4,4,16,6,1,2,6,6,3,1,15,3,7,9,18,14,3,4,15,4,3],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"box"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Box Plot","annotations":[{"x":-0.01,"y":60,"text":"40","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":23,"text":"64","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":39,"text":"67","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":33,"text":"76","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":38,"text":"79","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":34,"text":"96","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":27,"text":"102","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":30,"text":"117","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":25,"text":"150","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":49,"text":"163","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":60,"text":"168","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":27,"text":"170","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":27,"text":"178","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":52,"text":"193","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":24,"text":"203","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":57,"text":"206","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":52,"text":"213","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":58,"text":"249","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":57,"text":"274","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":43,"text":"278","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":37,"text":"285","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":75,"text":"289","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":29,"text":"309","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":30,"text":"342","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":25,"text":"344","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":37,"text":"362","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":56,"text":"367","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":29,"text":"374","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":37,"text":"388","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":81,"text":"404","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":27,"text":"408","showarrow":false,"xanchor":"right"},{"x":-0.01,"y":23,"text":"443","showarrow":false,"xanchor":"right"}],"yaxis":{"domain":[0,1],"automargin":true,"title":[]},"xaxis":{"domain":[0,1],"automargin":true},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"fillcolor":"rgba(31,119,180,0.5)","y":[1,3,0,13,15,3,2,0,7,4,15,0,2,13,2,2,1,2,5,5,3,4,2,0,13,7,2,12,2,5,4,6,2,3,14,7,0,1,3,60,5,3,0,3,2,1,1,13,2,5,12,12,1,20,0,5,0,8,9,10,1,5,5,23,7,1,39,2,7,9,0,4,16,0,16,33,4,2,38,8,2,2,0,15,0,1,5,7,10,22,10,0,11,9,0,34,3,1,0,10,4,27,7,1,7,3,2,11,9,11,11,8,2,4,4,6,30,7,15,6,7,2,1,5,1,11,16,2,14,8,17,1,0,1,1,10,7,2,5,6,1,16,0,17,0,10,6,20,1,25,3,6,0,8,9,19,2,2,3,7,2,8,49,2,1,5,5,60,10,27,7,8,12,2,2,4,6,27,0,9,3,0,2,3,5,5,1,7,4,3,7,1,52,6,18,14,0,8,16,2,12,3,24,0,0,57,11,1,18,1,11,0,52,12,6,0,2,2,13,2,3,2,2,1,2,3,1,5,6,1,2,3,7,7,0,7,8,9,8,1,14,2,4,8,3,10,21,6,58,12,5,2,4,2,5,0,3,7,1,2,1,4,4,4,2,0,13,3,1,4,1,3,1,57,1,17,11,43,6,6,1,0,10,3,37,6,11,4,75,7,3,3,3,4,5,2,4,2,11,0,2,4,6,0,2,5,2,10,29,3,0,21,0,3,1,9,3,3,5,6,4,16,3,13,3,2,2,3,7,2,2,2,2,5,3,2,4,1,3,6,4,30,0,25,0,5,3,2,2,9,2,13,1,4,4,3,7,7,14,4,15,37,2,4,6,10,56,3,0,18,3,18,7,29,0,5,4,3,6,21,1,3,3,0,13,5,5,37,2,11,13,2,4,21,2,4,3,3,12,1,4,13,2,81,12,2,16,27,2,2,8,2,4,3,19,4,1,3,15,4,4,13,6,1,3,3,0,22,4,14,6,16,6,0,8,0,4,5,2,6,11,1,23,4,4,16,6,1,2,6,6,3,1,15,3,7,9,18,14,3,4,15,4,3],"type":"box","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" tabindex="-1"></a><span class="fu">ggplot</span>(screen, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(mstatus), </span>
<span id="cb74-2"><a href="#cb74-2" tabindex="-1"></a><span class="at">y =</span> timedrs, <span class="at">fill =</span> <span class="fu">factor</span>(mstatus))) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-15-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a><span class="fu">ggplot</span>(screen) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span>  attdrug) <span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>( <span class="at">bins =</span> <span class="dv">6</span>, <span class="at">fill =</span> <span class="st">&quot;#0c4c8a&quot;</span>)<span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-16-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a><span class="fu">ggplot</span>(screen) <span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" tabindex="-1"></a><span class="fu">aes</span>(<span class="at">x =</span>  atthouse) <span class="sc">+</span></span>
<span id="cb76-3"><a href="#cb76-3" tabindex="-1"></a><span class="fu">geom_histogram</span>( <span class="at">bins =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">&quot;darkgreen&quot;</span>) <span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-17-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="uç-değerlerin-belirlenmesi" class="section level3" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Uç değerlerin Belirlenmesi</h3>
<p>🔗<a href="https://htmlcolorcodes.com/">Color codes</a>
.pull-left[</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a>atthouse_plt <span class="ot">&lt;-</span> </span>
<span id="cb77-2"><a href="#cb77-2" tabindex="-1"></a><span class="fu">ggplot</span>(screen) <span class="sc">+</span></span>
<span id="cb77-3"><a href="#cb77-3" tabindex="-1"></a><span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> atthouse) <span class="sc">+</span></span>
<span id="cb77-4"><a href="#cb77-4" tabindex="-1"></a><span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#3357FF&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-5"><a href="#cb77-5" tabindex="-1"></a><span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" tabindex="-1"></a>atthouse_plt</span></code></pre></div>
<p><img src="02-Varsayimlar2_files/figure-html/unnamed-chunk-19-1.png" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Veri setinde potansiyel tek değişkenli uç değerler tespit
edildiğinde, önce uç değerin nedeni araştırılmalıdır. Eğer
veri girişinde hata varsa veya kayıp veri kodlanırken hata
yapıldıysa düzeltilmelidir.</p></li>
<li><p>Bunun dışındaki nedenlerde değişkenin
dönüştürülmesinin uygun olup olmayacağına karar
verilmelidir.</p></li>
<li><p>Dönüşümler hem dağılımların normalliğini geliştirir hem de tek
değişkenli uç değerleri dağılımın merkezine çekerler ve etkisini
azaltırlar.</p></li>
<li><p>Dönüşüme karar verilirse çok değişkenli uç değerler
incelenmeden dönüşüm yapılmalıdır. Çünkü çok değişkenli uç
değerlerin belirlenmesinde kullanılan istatistikler normal dağılımı
gerektirir.</p></li>
</ul>
</div>
<div id="uç-değerlerin-belirlenmesi-1" class="section level3" number="2.1.4">
<h3><span class="header-section-number">2.1.4</span> Uç değerlerin Belirlenmesi</h3>
<ul>
<li><p>Veri setinde iki değişken – timedrs ve atthouse uç
değerlere sahiptir.</p></li>
<li><p><strong>timedrs</strong> değişkeni için uç değer olarak belirlenen değerlerin
beklenen değerlerin üstünde olduğu ancak veri girişinde hata
bulunmadığı rapor edilmiş, bu değerlere sahip bireylerin veri
setinde kalmasına karar verilmiştir.</p></li>
<li><p><strong>atthouse</strong> değişkeni için uç değerler olarak belirlenen değerler
diğer değerlerden kopuktur. Bu değerlerin evren için beklenen
değerler mi olduğuna veya veri girişinde hata yapılıp
yapılmadığına karar verilmelidir.</p></li>
<li><p>Her iki durumda da veri setinde</p></li>
</ul>
<ol start="260" style="list-style-type: decimal">
<li>ve 296. satırda yer alan 2 birey (346 ve 407 subno.lu
bireyler) veri setinden çıkarılabilir. 2 bireyin veri setinden
çıkarılması sonucu örneklem büyüklüğü 462’ye eşit olacaktır.</li>
</ol>
</div>
<div id="uç-değerlerin-belirlenmesi-2" class="section level3" number="2.1.5">
<h3><span class="header-section-number">2.1.5</span> Uç değerlerin Belirlenmesi</h3>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a>screen[<span class="fu">c</span>(<span class="dv">260</span>,<span class="dv">298</span>),]</span>
<span id="cb79-2"><a href="#cb79-2" tabindex="-1"></a>screen <span class="ot">&lt;-</span> screen[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">260</span>,<span class="dv">298</span>),]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">subno</th>
<th align="right">timedrs</th>
<th align="right">attdrug</th>
<th align="right">atthouse</th>
<th align="right">income</th>
<th align="right">mstatus</th>
<th align="right">race</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">346</td>
<td align="right">2</td>
<td align="right">8</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">407</td>
<td align="right">2</td>
<td align="right">8</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="mahalanobis-uzaklığı" class="section level3" number="2.1.6">
<h3><span class="header-section-number">2.1.6</span> Mahalanobis Uzaklığı</h3>
<ul>
<li><p>Çok değişkenli uç değerleri belirlemenin bir yolu
<strong>Mahalanobis uzaklığını</strong> hesaplamaktır. Mahalanobis uzaklığı z puanının çok
boyutlu versiyonudur. Bir gözlemin, dağılımın kovaryansı (çok
boyutlu varyansı) verildiğinde, dağılımın ağırlık merkezinden (çok
boyutlu ortalamasından) uzaklığını ölçer.</p></li>
<li><p><strong>Mahalonobis uzaklığı</strong> ki-kare dağılımı gösterir (serbestlik derecesi
hesaplamada kullanılan değişken sayısına eşittir) ve ki-kare dağılımı
kullanılarak değerlendirilebilir. Eğer hesaplanan Mahalonobis
uzaklığının gözlenme olasılığı 0.001 veya daha küçükse gözlem
uçdeğerdir.</p></li>
<li><p>Bu yöntem eşit aralık veya eşit oran düzeyinde ölçülen değişkenler
için veya sürekli değişken olarak ele alınan sıralama ölçeğinde
ölçülen değişkenler için geçerli olup sınıflama düzeyinde ölçülen
değişkenler için geçerli değildir.</p></li>
</ul>
</div>
<div id="mahalanobis-uzaklığı-1" class="section level3" number="2.1.7">
<h3><span class="header-section-number">2.1.7</span> Mahalanobis Uzaklığı</h3>
<p>Mahalanobis Uzaklığı hesaplama</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:outliers&#39;:
## 
##     outlier</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" tabindex="-1"></a>veri <span class="ot">&lt;-</span> screen[,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb84-2"><a href="#cb84-2" tabindex="-1"></a>md <span class="ot">&lt;-</span> <span class="fu">mahalanobis</span>(veri, <span class="at">center =</span> <span class="fu">colMeans</span>(veri), <span class="at">cov =</span> <span class="fu">cov</span>(veri))</span>
<span id="cb84-3"><a href="#cb84-3" tabindex="-1"></a>md</span></code></pre></div>
<pre><code>##   [1]  3.7855174  4.5414927  3.5010769  7.2813646  5.4572396  2.8965495
##   [7]  5.8078984  3.8794776  4.7511661  7.4154047 10.6020996  5.2491208
##  [13]  6.0737317  3.2718847 12.3164634  4.4407488  4.8361596  6.3628056
##  [19]  4.1265239 10.7975454  5.7484910 10.5727271  3.4984523  4.8334420
##  [25]  4.7006156  9.5885717  3.5312950  5.5896224  5.1433235  7.2593681
##  [31]  5.2943018  4.3283138  4.4507527  2.5727236  8.7821612  6.1025712
##  [37]  7.2382743  4.0468912  7.7316581 28.8987230  5.4170887  4.1667572
##  [43]  5.3116126  5.1569082  7.3460683  2.3625482  3.6737604  4.0534574
##  [49]  3.3853834  3.4657620  4.5780857  3.0608354  4.6916196  4.4893953
##  [55]  4.0245315  2.0344652  3.1050893  9.8614394  6.7505963  3.0433786
##  [61]  6.5567014  3.3054220  2.4455501  7.0248226  5.6672530  2.9891672
##  [67] 11.5828872  2.5441926  1.7667950  4.5960680 14.5333387  2.6837064
##  [73]  6.4811658  3.0011028  2.3057045  9.7329514  1.7895523  5.3934136
##  [79] 13.3716971  2.3110731  5.8720105 10.7725170  8.5039953  2.4574823
##  [85]  8.8868422  4.3797949  3.6144474  4.7011680  3.7145569  4.4318054
##  [91]  3.7427603  2.7907114  3.4843374  1.9955713  5.0384718  7.8181717
##  [97]  2.7505160  4.1944071  9.6736148  3.3155116  3.8999808  6.5893242
## [103]  2.5183178  7.4588332  5.9209105  2.2524852  6.5791408  5.1150492
## [109]  5.1137615  2.6491767  2.9594896  1.7584158  8.8338151  2.8971124
## [115]  1.8123657  5.6574698 16.9238841  1.8501769  3.8235228  3.8774260
## [121]  1.3105799  2.9678079  2.7608382  1.6879187  4.4086001  3.9957294
## [127]  8.2801802  2.6293344  6.7605763  1.8484338  6.5895489  3.2801621
## [133]  5.0517770  5.9195634  3.3591122  4.2221562  2.9409773  4.9531359
## [139]  3.1103986  3.8799964  5.7546236 10.2881928 13.4939493  3.4715583
## [145]  1.8424062  3.2771145  2.8268849  1.6960980  2.0711391  4.0297613
## [151]  4.0657988  3.9282954  3.2096484  2.3121331  2.3604403  5.1809019
## [157]  1.5568562  1.4011462  0.9637404  2.9491943  0.9433546  2.4474680
## [163] 18.1320184  3.0142555  1.0665386  7.7718259  3.6985422 25.5487735
## [169]  1.4221965  7.7048582  1.9624407  1.3074974  2.3822673  3.0783644
## [175]  2.9058360  0.9743921  7.4607015  6.7088908  5.6527432  6.4309122
## [181]  1.8479600  2.5272576  3.4714976  0.6689684  0.4318409  4.5649890
## [187]  5.3568106  3.5000669  2.1231252  2.2844022  2.7988776  6.0061393
## [193] 18.2897225  1.6169351  1.5016959  2.2269690  0.9566407  4.6727831
## [199]  2.0252908  4.4660476  2.3883902  0.6961441  5.6787359  3.1635208
## [205]  4.1110345 22.1964098  3.0522026  1.8021500  4.3506047  9.0541907
## [211]  8.2579306  2.1905416 21.4120430  0.6469666  4.0952020  1.2022856
## [217]  2.9537324  1.6548145  6.0283023  3.9044602  7.6757521  2.5713563
## [223]  0.9938295  2.7277740  2.8550430  1.9264826  2.1040599 12.3495730
## [229]  6.6318164  3.4876501  3.8974509  2.9975335  4.0897193  3.5446727
## [235]  1.9266324  0.1065869  0.6358564  2.1270073  2.5669054  2.1739533
## [241]  4.3804304  7.5386975  1.0302888  7.2362347  0.3305543  2.9615148
## [247] 11.5963772  3.5910218 22.5799967  0.2479659  2.5900657  3.6499610
## [253]  1.2289218  1.7406463  1.8382841  3.7155733  0.4742904  1.4801897
## [259]  5.5730679  3.0041966  2.4852546  2.9817811  2.8800450  0.7831246
## [265]  2.6737370  4.8183265  0.6497375  0.7426755  0.7621307  2.1250657
## [271]  0.5885866  9.1709978 20.6494166  8.4070691  3.7105583  1.2537201
## [277] 15.0711110  4.1107305  1.4540580  4.0546367  5.4775515  7.2414441
## [283]  7.9329624  8.2407241  1.2397701  4.7282567  4.7457248 42.9669017
## [289]  1.6282845  5.9049729  1.2298590  1.9772822  2.2607001  3.8090199
## [295]  6.8631087  2.3061547  3.4541770  3.8338169  1.7260334  1.1083669
## [301]  2.3657616  1.9693117  2.8383000  2.5583017  6.4249597  3.0469777
## [307] 11.5373669  4.7703365  3.2494754  3.6034242  1.8575554  0.8462491
## [313]  3.2868112  7.7835250  1.4153680  2.7682354  0.7780229  1.8078764
## [319]  4.9485890 10.4252132  6.5768527  2.0248181  5.7009743  3.0642524
## [325]  1.6173193  2.0914309  1.8092447  1.1908685  3.1485676  2.0727397
## [331]  1.4037933  7.2297240  1.9343764  3.0312300  3.5897903  2.0050680
## [337]  2.5739437  8.9999992  1.0669762  5.8561713  2.4714036  4.4696050
## [343]  5.4399950  3.2952550  3.7145865  6.9112917  3.2840759  1.4103383
## [349]  1.3851939  3.6322003  1.5878897  4.1914955  3.0752336  4.7892312
## [355]  4.2929589  3.1333097  4.7796665  3.1591478  4.5198379 11.1486580
## [361]  3.7392451  2.2628183  2.4125581  3.4614431 23.0166024  5.4491236
## [367]  4.7397024  4.6842292  2.8538419  2.2781786  2.5956733  6.8531350
## [373]  6.7960135  6.0795978  2.1682126  2.4737663  4.1856046  4.6415479
## [379]  3.5599207  2.7388233  2.5293824  5.1321875  7.2457378  7.4892917
## [385]  6.8010203 14.2353302  2.9820427  2.4682846  5.8733295  3.1122244
## [391]  6.3897252  4.6099423  6.2102703  2.1867739  2.2937065  1.6298391
## [397]  3.3963050  2.3261666  3.5425562  6.6550424  3.8696344 48.8826963
## [403] 11.4814871  3.3018523  3.5740804  4.4757069  7.8057872  3.4772952
## [409]  3.6146914  4.6065698  5.5150259  6.3583130  3.0693829  6.7718509
## [415]  3.4226350  2.2465182  7.1038405  1.9719393  3.9830239  2.5033974
## [421]  5.3274832 13.9456659  6.5996478  4.7996942  8.2874973  5.1300800
## [427]  3.7050704  4.1545249  5.1345741  4.5554130  6.7890309 10.3172984
## [433]  6.0518106  4.4990962  5.0631094 10.7775009  3.0657255  3.5561233
## [439]  3.9424773  3.3850723  5.7943970  7.4352341  7.0970970  5.7053781
## [445]  6.6783334  5.7305661  6.0516997  6.1890557  7.7220897  4.9028508
## [451]  6.4598651 11.5182830  6.3900666  7.0644921  8.5738996  7.7959938
## [457]  7.0491686  9.2822350  7.3239791 12.5969390  6.1863226  6.6177320</code></pre>
</div>
<div id="mahalanobis-uzaklığı-2" class="section level3" number="2.1.8">
<h3><span class="header-section-number">2.1.8</span> Mahalanobis Uzaklığı</h3>
<p>Kritik değer belirleme</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb86-2"><a href="#cb86-2" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> .<span class="dv">001</span></span>
<span id="cb86-3"><a href="#cb86-3" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> (<span class="fu">qchisq</span>(<span class="at">p =</span> <span class="dv">1</span> <span class="sc">-</span> alpha, <span class="at">df =</span> <span class="fu">ncol</span>(veri)))</span>
<span id="cb86-4"><a href="#cb86-4" tabindex="-1"></a>cutoff</span></code></pre></div>
<pre><code>## [1] 20.51501</code></pre>
</div>
<div id="mahalanobis-uzaklığı-3" class="section level3" number="2.1.9">
<h3><span class="header-section-number">2.1.9</span> Mahalanobis Uzaklığı</h3>
<p>Kritik değer belirleme</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" tabindex="-1"></a>ucdegerler <span class="ot">&lt;-</span> <span class="fu">which</span>(md <span class="sc">&gt;</span> cutoff)</span>
<span id="cb88-2"><a href="#cb88-2" tabindex="-1"></a>veri[ucdegerler, ]</span>
<span id="cb88-3"><a href="#cb88-3" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" tabindex="-1"></a>data_temiz <span class="ot">&lt;-</span> veri[<span class="sc">-</span>ucdegerler, ]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">subno</th>
<th align="right">timedrs</th>
<th align="right">attdrug</th>
<th align="right">atthouse</th>
<th align="right">income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">48</td>
<td align="right">60</td>
<td align="right">7</td>
<td align="right">24</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">235</td>
<td align="right">60</td>
<td align="right">10</td>
<td align="right">29</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">276</td>
<td align="right">57</td>
<td align="right">9</td>
<td align="right">24</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">291</td>
<td align="right">52</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">330</td>
<td align="right">58</td>
<td align="right">7</td>
<td align="right">29</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">370</td>
<td align="right">57</td>
<td align="right">8</td>
<td align="right">23</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">398</td>
<td align="right">75</td>
<td align="right">9</td>
<td align="right">33</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="right">502</td>
<td align="right">56</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">548</td>
<td align="right">81</td>
<td align="right">8</td>
<td align="right">24</td>
<td align="right">9</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="mahalanobis-uzaklığı-4" class="section level3" number="2.1.10">
<h3><span class="header-section-number">2.1.10</span> Mahalanobis Uzaklığı</h3>
<ul>
<li>Mahalonobis uzaklığı değerleri ki-kare ile değerlendirilir (serbestlik
derecesi bağımsız değişken sayısına eşittir). Buna göre 18.4668 kritik
değerinden büyük olan değerler 0.001 alfa düzeyinde istatistiksel olarak
anlamlı olarak değerlendirilir.</li>
<li>548, 398, 48, 235, 330, 502, 276, 291 ve 370 subno.lu bireyler için
Mahalonobis uzaklık değerleri kritik değerden büyüktür. Bu gözlemler
çok değişkenli uç değerler olarak değerlendirilir.</li>
</ul>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" tabindex="-1"></a>veri[ucdegerler, ]</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">subno</th>
<th align="right">timedrs</th>
<th align="right">attdrug</th>
<th align="right">atthouse</th>
<th align="right">income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">48</td>
<td align="right">60</td>
<td align="right">7</td>
<td align="right">24</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">235</td>
<td align="right">60</td>
<td align="right">10</td>
<td align="right">29</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">276</td>
<td align="right">57</td>
<td align="right">9</td>
<td align="right">24</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="right">291</td>
<td align="right">52</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td align="right">330</td>
<td align="right">58</td>
<td align="right">7</td>
<td align="right">29</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="right">370</td>
<td align="right">57</td>
<td align="right">8</td>
<td align="right">23</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="right">398</td>
<td align="right">75</td>
<td align="right">9</td>
<td align="right">33</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="right">502</td>
<td align="right">56</td>
<td align="right">8</td>
<td align="right">19</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td align="right">548</td>
<td align="right">81</td>
<td align="right">8</td>
<td align="right">24</td>
<td align="right">9</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="çok-değişkenli-normallik-sayıltısı" class="section level3" number="2.1.11">
<h3><span class="header-section-number">2.1.11</span> Çok Değişkenli Normallik Sayıltısı</h3>
<ul>
<li><p>Çok değişkenli normallik her bir değişkenin ve değişkenlerin bütün
doğrusal kombinasyonlarının normal dağıldığı
sayıltısıdır.</p></li>
<li><p>Sayıltının karşılanması durumunda analizin artıkları
(hataları) da normal dağılır.</p></li>
<li><p>Bir değişken çok değişkenli normal dağılıma sahipse, tek
değişkenli normal dağılıma da sahiptir ancak bunun tersi
sağlanmayabilir; iki veya daha fazla tek dağılımlı
normallik gösteren değişkenler çok değişkenli normallik
göstermeyebilir.</p></li>
</ul>
</div>
<div id="çok-değişkenli-normallik-sayıltısı-1" class="section level3" number="2.1.12">
<h3><span class="header-section-number">2.1.12</span> Çok Değişkenli Normallik Sayıltısı</h3>
<ul>
<li><p>Çok değişkenli normallik sayıltısını test etmek için
doğrudan bir test bulunmadığından, genellikle her bir
değişken ayrı ayrı test edilir ve eğer her bir değişken
normal dağılım gösteriyorsa, çok değişkenli normal
oldukları varsayılır.</p>
<ul>
<li>Not: Her bir değişkenin normal olarak dağılımı çok değişkenli
normallik için gereklidir ancak yeterli değildir.</li>
</ul></li>
<li><p>Normalliğin değerlendirilmesi için hem istatistiksel hem
de grafiksel yöntemler vardır.</p>
<ul>
<li>İstatistiksel yöntemler normallik için hipotez testlerini içerir.</li>
<li>Grafiksel yöntemler histogram ve normallik grafiklerinin
incelenmelerini içerir.</li>
</ul></li>
</ul>
</div>
<div id="normallik-sayıltısı" class="section level3" number="2.1.13">
<h3><span class="header-section-number">2.1.13</span> Normallik Sayıltısı</h3>
<p>Normalliğin iki bileşeni vardır: Çarpıklık ve basıklık</p>
<ul>
<li><p>Bir değişkene ait dağılım normal olduğunda, değişkenin çarpıklık ve basıklık
değerleri sıfıra eşittir.</p></li>
<li><p>Kural olarak eğer değişkenin çarpıklık ve basıklık değerleri -1.0 ile +1.0
arasındaysa, değişkenin normale oldukça yakın olduğu söylenebilir.</p></li>
<li><p>Hem çarpıklık hem de basıklık için istatistiksel anlamlılık testleri vardır. Bu testlerde z dağılımı kullanılarak elde edilen çarpıklık veya basıklık değeri sıfır ile karşılaştırılır:</p></li>
</ul>
</div>
<div id="normallik-sayıltısı-1" class="section level3" number="2.1.14">
<h3><span class="header-section-number">2.1.14</span> Normallik Sayıltısı</h3>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" tabindex="-1"></a><span class="fu">library</span>(sur)</span>
<span id="cb90-2"><a href="#cb90-2" tabindex="-1"></a><span class="fu">attach</span>(screen)</span>
<span id="cb90-3"><a href="#cb90-3" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" tabindex="-1"></a><span class="fu">skew</span>(timedrs)</span>
<span id="cb90-5"><a href="#cb90-5" tabindex="-1"></a><span class="fu">se.skew</span>(timedrs)</span>
<span id="cb90-6"><a href="#cb90-6" tabindex="-1"></a><span class="fu">skew.ratio</span>(timedrs)</span></code></pre></div>
<pre><code>## [1] 3.226868
## [1] 0.1135929
## [1] 28.4073</code></pre>
</div>
<div id="normallik-sayıltısı-2" class="section level3" number="2.1.15">
<h3><span class="header-section-number">2.1.15</span> Normallik Sayıltısı</h3>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb92-2"><a href="#cb92-2" tabindex="-1"></a><span class="fu">library</span>(labelled)</span>
<span id="cb92-3"><a href="#cb92-3" tabindex="-1"></a><span class="fu">jarque.test</span>(<span class="fu">remove_labels</span>(timedrs))</span>
<span id="cb92-4"><a href="#cb92-4" tabindex="-1"></a><span class="fu">jarque.test</span>(<span class="fu">remove_labels</span>(attdrug))</span>
<span id="cb92-5"><a href="#cb92-5" tabindex="-1"></a><span class="fu">jarque.test</span>(<span class="fu">remove_labels</span>(atthouse))</span></code></pre></div>
<pre><code>## 
##  Jarque-Bera Normality Test
## 
## data:  remove_labels(timedrs)
## JB = 3984.7, p-value &lt; 2.2e-16
## alternative hypothesis: greater
## 
## 
##  Jarque-Bera Normality Test
## 
## data:  remove_labels(attdrug)
## JB = 5.1381, p-value = 0.07661
## alternative hypothesis: greater
## 
## 
##  Jarque-Bera Normality Test
## 
## data:  remove_labels(atthouse)
## JB = 1.5155, p-value = 0.4687
## alternative hypothesis: greater</code></pre>
<p>🔗 <a href="https://www.statology.org/skewness-kurtosis-in-r/">summarytools için</a></p>
<p>Rummel, R. J. (1970). Applied Factor Analyis. Evanston,IL: Northwestern University
Press.</p>
<!--chapter:end:02-Varsayimlar2.Rmd-->
</div>
</div>
</div>
<div id="cr" class="section level1" number="3">
<h1><span class="header-section-number">3</span> CR</h1>
<!--chapter:end:03-CR.Rmd-->
</div>
<!--bookdown:body:end-->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;

    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    $(solveme[i]).after(" <span class='webex-icon'></span>");
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    $(selects[i]).after(" <span class='webex-icon'></span>");
  }

  update_total_correct();
}

</script>
<script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );

  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });

  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>OLC733</strong>: R ile Çok Değişkenli İstatistik ve Ölçme Uygulamaları" was written by Kubra Atalay Kabasakal. It was last built on 2024-02-20.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


</body>

</html>
